---
title: "simulating preparation"
author: "renyan"
date: "2022/4/16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


- 目标：为了检查 `fmrs` 包返回空值情况，进行检验.
- 结论：如果数据出现共线性，会导致返回结果为空，可能的方法是先回归得到 X,Z 的结果，然后再用拟合的残差拟合 W

```{r}
library(Matrix)
library(MASS)
library(fmrs)
source("sim.r")

n <- 120                         # The sample size
p <- 50                           # The dimension of x
q <- 30                         # The dimension of z
pq <- q*p                        # The dimension of each sample
# dim_nonzero_x <- 2                         # The dimension of non-zero coefficients of x
# dim_nonzero_z <- 4                        # The dimension of non-zero coefficients of z
# E.cat <- 2                       # The dimension of non-zero coefficients of z
mu <- 2                      # The signal intensity of non-zero coefficients
balance <- T                     # Balanced/Imbalanced subgroup
gr_num_main <- 2                     # The number of rough subgroup 
gr_num_sub <- 4                       # The number of refined subgroup 
hier_struc <- list(c(1,2),c(3,4))  # Hierarchical subgroup structure
# sd.epsi<-0.5                     # The residual error
# corZX <- F                       # Correlated/Uncorrelated X and Z
intercorr0<-"AR1"                # The correlation structure of Z
signal_its <- 2 # signal intensity
K <- gr_num_sub


# ------------ Necessary parameters to support algorithm implementation --------
comb_pair <- combn(K,2)
H_3 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(pq)))
H_1 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(p)))
H_2 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(q)))
# one_matrix <- bdiag(rep(list(rep(1,pq)),(K*(K-1)/2)))
# one_matrix_x <- bdiag(rep(list(rep(1,q)),(K*(K-1)/2)))
# one_matrix_z <- bdiag(rep(list(rep(1,p)),(K*(K-1)/2)))

# ------------ Generate the regression coefficients -----------
coef_main_value <- c(-signal_its,signal_its)
coef_sub_value <- c(-1.5*signal_its,-0.5*signal_its,1.5*signal_its,0.5*signal_its)
if(balance){pr_sub<-rep(1/gr_num_sub,gr_num_sub)}else{pr_sub<-c(1/6,1/6,1/3,1/3)}

ci <- ci_generate(n, pr_sub, hier_struc)
ci_main <- ci$ci_main
ci_sub <- ci$ci_sub

coef_true <- generate_coef_true(n, p, q, ci_main, ci_sub, coef_main_value, coef_sub_value)

# ------------ Generate data ------------ 
whole.data <- generate_sim_data(n, p, q, coef_true, cotype_x="AR_E", cotype_z="AR_E")
```




```{r}
K_up <- 2
coef_rough_init <- rep(1, (p+q+1)*K_up)
res.mle <- fmrs.mle(
  y = whole.data$data_y,
  x = whole.data$X_main,
  delta = rep(0, length(whole.data$data_y)),
  nComp = K_up,
  disFamily = "norm",
  initCoeff = coef_rough_init,
  initDispersion = rep(1, K_up),
  initmixProp = rep(1 / K_up, K_up),
  nIterNR = 200
)
res.lam <- fmrs.tunsel(y = whole.data$data_y, 
                       x =whole.data$X_main,
                       delta = rep(0,length(whole.data$data_y)),
                       nComp = K_up, 
                       disFamily = "norm",
                       initCoeff = c(coefficients(res.mle)),
                       initDispersion = dispersion(res.mle),
                       initmixProp = mixProp(res.mle),
                       penFamily = "adplasso",nIterNR = 200)
res.var <- fmrs.varsel(y = whole.data$data_y, 
                       x =whole.data$X_main, 
                       delta = rep(0,length(whole.data$data_y)),
                       nComp = ncomp(res.mle), 
                       disFamily = "norm",
                       initCoeff=c(coefficients(res.mle)),
                       initDispersion = dispersion(res.mle),
                       initmixProp = mixProp(res.mle),
                       penFamily = "adplasso",
                       lambPen = slot(res.lam, "lambPen"),nIterNR = 200)
```






