---
title: "迭代test"
author: "renyan"
date: "2022/5/16"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r, echo = FALSE}
rm(list = ls(all = TRUE))
ls()
setwd("D:/Ryanna/RUC_courses/Y1_2/Group/code")
library(Matrix)
library(MASS)
library(fmrs)
library(ggplot2)
library(corrplot)
library(dplyr)
library(reshape2)
source("sim.r")
source("func.r")
```

```{r}
n <- 20                         # The sample size
p <- 4                           # The dimension of x
q <- 3                         # The dimension of z
pq <- q*p                        # The dimension of each sample
dim_nonzero_beta <- 2                         # The dimension of non-zero coefficients of x
dim_nonzero_alpha <- 2                        # The dimension of non-zero coefficients of z
dim_nonzero_gamma <- 4
balance <- T                     # Balanced/Imbalanced subgroup
gr_num_main <- 2                     # The number of rough subgroup 
gr_num_sub <- 4                       # The number of refined subgroup 
hier_struc <- list(c(1,2),c(3,4))  # Hierarchical subgroup structure
# sd.epsi<-0.5                     # The residual error
# corZX <- F                       # Correlated/Uncorrelated X and Z
intercorr0<-"AR1"                # The correlation structure of Z
signal_its <- 2 # signal intensity
K <- gr_num_sub
iter_max <- 10
eps <- 0.001
incl_inter <- FALSE               # 模拟实验数据生成时候是否要包含交互项

lambda_1 <- 0
lambda_2 <- 0
lambda_3 <- 0
a <- 3
iter_max <- 10
K_up <- 4
tau <- 1 

# ------------ Necessary parameters to support algorithm implementation --------
comb_pair <- combn(K,2)
H_3 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(pq)))
H_1 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(p)))
H_2 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(q)))

# ------------ Generate the regression coefficients -----------
coef_main_value <- c(signal_its, -signal_its)
# coef_main_value <- c(signal_its, 2signal_its)
coef_sub_value <- c(1.5*signal_its, 0.5*signal_its, -0.5*signal_its, -1.5*signal_its)
# coef_sub_value <- c(1*signal_its, 2*signal_its, 3*signal_its, 4*signal_its)
if(balance){pr_sub<-rep(1/gr_num_sub,gr_num_sub)}else{pr_sub<-c(1/6,1/6,1/3,1/3)}

# true main groups & subgroups
set.seed(999)
ci <- ci_generate(n, pr_sub, hier_struc)
ci_sim <- rep(0, n) # true label
for(i in 1:K){
  ci_sim[ci$ci_sub[[i]]] <- i
}

# true coefficients
set.seed(999)
coef_true <- generate_coef_true(n, p, q, ci$ci_main, ci$ci_sub, 
                                coef_main_value,  coef_sub_value, incl_inter,
                                dim_nonzero_beta, dim_nonzero_alpha, dim_nonzero_gamma)
# Generate data
whole.data <- generate_sim_data(n, p, q, coef_true, cotype_x="AR_E", cotype_z="AR_E")
```

### 检查不同类别 y 的分布

小样本量时不进行该检验

```{r}
# df <- data.frame(y = whole.data$data_y)
# ci_tmp <- rep(1, n)
# for(i in 2:K_up){ ci_tmp[ci$ci_sub[[i]]] <- i }
# df$ci <- factor(ci_tmp)
# df %>% group_by(ci) %>% summarise(mu_true = mean(y))
# ggplot(df, aes(x = y, fill = ci)) +
#   geom_histogram(position = "dodge") +
#   theme_minimal()
```

### 检查y计算是否正确

```{r}
idx <- 1
t <- cbind(whole.data$X, whole.data$Z, whole.data$W)
ci_sim[idx]

sum(t[idx,] * coef_true$coef_true_K[,ci_sim[idx]]) # data_y
whole.data$data_y[idx]
t[idx,] * coef_true$coef_true_K[,ci_sim[idx]]
# data_y
coef_beta <- as.vector(coef_true$beta_true_mat)
coef_alpha <- as.vector(coef_true$alpha_true_mat)
coef_gamma <- as.vector(coef_true$gamma_true_mat)
coef_eta <- kronecker(coef_beta, matrix(1, q, 1)) * coef_gamma


# r1 <- whole.data$data_X[,1:p] %*% coef_beta[1:p]
r1 <- whole.data$data_X %*% coef_beta
r1[idx]
r2 <- whole.data$data_Z %*% coef_alpha
r2[idx]
r <-  whole.data$data_X %*% coef_beta + whole.data$data_Z %*% coef_alpha
r[idx]
# tmp <-  whole.data$data_X %*% coef_beta + whole.data$data_Z %*% coef_alpha + 
#   whole.data$data_W %*% coef_eta
```

```{r}
coef_init <- whole.data$coef_true
```

```{r}
# 按列索引
idx_X <- c(1:(p))
idx_Z <- c((p+1):((p+q)))
idx_W <- c(((p+q)+1):((p+q+pq)))
idx_X_full <- sort(rep((0:(K-1))*(p+q+pq), p)) + idx_X
idx_Z_full <- sort(rep((0:(K-1))*(p+q+pq), q)) + idx_Z
idx_W_full <- sort(rep((0:(K-1))*(p+q+pq), pq)) + idx_W
coef_init_beta <- coef_init[idx_X_full]
coef_init_alpha <- coef_init[idx_Z_full]
coef_init_eta <- coef_init[idx_W_full]
coef_init_gamma <- coef_init_eta/kronecker(coef_init_beta+eps, matrix(1, nrow=q, ncol=1))

X <- whole.data$X_all
y <- whole.data$data_y

####################### Initialize coef ######################
# group
# *1 sgeMatrix
u_init <- H_1 %*% coef_init_beta
v_init <- H_2 %*% coef_init_alpha
w_init <- H_3 %*% coef_init_gamma
# *1 sgeMatrix
xi_init <- Matrix(0, ncol=1, nrow=p*K*(K-1)/2, sparse=T)
zeta_init <- Matrix(0, ncol=1, nrow=q*K*(K-1)/2, sparse=T)
eta_init <- Matrix(0, ncol=1, nrow=pq*K*(K-1)/2, sparse=T) # 字母有混淆，暂且这么记

# iteration
# weight/res 相关选择在这里修改
# 根据分析暂时选择使用 res 相关
iter <- 1
coef_beta_est_list <- vector(mode="list", length=iter_max)
coef_alpha_est_list <- vector(mode="list", length=iter_max)
coef_eta_est_list <- vector(mode="list", length=iter_max)
coef_gamma_est_list <- vector(mode="list", length=iter_max)
coef_beta_est_list[[iter]] <- coef_init_beta
coef_alpha_est_list[[iter]] <- coef_init_alpha
coef_eta_est_list[[iter]] <- coef_init_eta
coef_gamma_est_list[[iter]] <- coef_init_gamma

mu_est_list <- vector(mode="list", length=iter_max)
mu_est_list[[iter]] <- matrix(0, nrow=n, ncol=K_up) # 暂时

rho_est_list <- vector(mode="list", length=iter_max)
mean_rho <- 1/sd(whole.data$data_y-mu_est_list[[iter]])
rho_est_list[[iter]] <- rep(mean_rho, 4)

pi_est_list <- vector(mode="list", length=iter_max)
pi_est_list[[iter]] <- pr_sub
```

## 最最简单-单类别

```{r}
get_q_c_matrix <- function(n, K_up, ci_sim){
  q_c_matrix <- matrix(0, nrow = n, ncol = K_up)
  for(i in 1:n){
    q_c_matrix[i,ci_sim[i]] <- 1
  }
  return(q_c_matrix)
}
# get_q_c_matrix(n, K_up, ci_sim)
```


```{r}
q_c_matrix <- matrix(0, nrow = n, ncol = K_up)
ci_sim
for(i in 1:n){
  q_c_matrix[i,ci_sim[i]] <- 1
}
q_c_matrix
```

```{r}
slice_matrix <- function(mat, ci_sim){
  res <- c()
  for(i in 1:nrow(mat)){
    res <- c(res, mat[i,ci_sim[i]])
  }
  return(res)
}
```

```{r}
y2 <- as.numeric(whole.data$data_y) - whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p)
y2 <- slice_matrix(y2, ci_sim)
# y2
# slice_matrix(whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q), ci_sim)
alpha2 <-  solve(t(whole.data$Z) %*% (whole.data$Z)) %*% t(whole.data$Z) %*% y2
H <- whole.data$Z %*% solve(t(whole.data$Z) %*% (whole.data$Z)) %*% t(whole.data$Z)
alpha2
plot(y2, whole.data$Z %*% alpha2)
qr.solve(whole.data$Z, y2)
Z <- whole.data$Z
```

```{r}
class1 <- ci$ci_sub[[1]]
y2_1 <- y2[class1]
Z <- whole.data$Z[class1,]
solve(t(Z) %*% Z) %*% t(Z) %*% y2_1
qr.solve(Z, y2_1)
```

## 最最简单-多类别

```{r}
for(k in 1:4){
  y2_full <- (y2 * q_c_matrix)[,k]
  # (whole.data$Z %*% coef_true$alpha_true_K) * q_c_matrix
  alpha_k <- qr.solve(whole.data$Z * as.numeric(q_c_matrix[,k]), y2_full)
  print(alpha_k)
}
```


## 最简单-把前一项加进去


```{r}
for(k in 1:4){
  y2 <- as.numeric(whole.data$data_y) - whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) # n*k
  y2 <- y2 * q_c_matrix
  alpha_k <- qr.solve(whole.data$Z * as.numeric(q_c_matrix[,k]), y2[,k])
  print(alpha_k)
}
```


## 最简单-对q进行微小扰动

```{r}
get_q_c_matrix_r <- function(q_c_matrix, seed_num = 999){
  set.seed(seed_num)
  q_c_matrix_r <- q_c_matrix + matrix(rnorm(n*K_up, mean = 0.2, sd = 0.1), nrow = n)
  q_c_matrix_r <- q_c_matrix_r/apply(q_c_matrix_r, 1, sum)
  return(q_c_matrix_r)
}
get_q_c_matrix_r(get_q_c_matrix(n, K_up, ci_sim))
```


```{r}
set.seed(999)
q_c_matrix_r <- q_c_matrix + matrix(rnorm(n*k, mean = 0.2, sd = 0.1), nrow = n)
# apply(q_c_matrix_r, 1, scale)
q_c_matrix_r <- q_c_matrix_r/apply(q_c_matrix_r, 1, sum)
ci_sim
q_c_matrix_r
```

```{r}
for(k in 1:4){
  y2 <- as.numeric(whole.data$data_y) - whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) # n*k
  y2 <- y2 * q_c_matrix_r
  alpha_k <- qr.solve(whole.data$Z * as.numeric(q_c_matrix_r[,k]), y2[,k])
  print(alpha_k)
}
```

系数已经偏离真实值较大


## 迭代更新两个参数

用现有更新公式尝试带入原模型，看参数估计还会不会出现膨胀很大的现象，注意在多分组的设定且不考虑惩罚项的条件下，理想的初始值与 `q_c_matrix` 有关。


```{r}
q_c_matrix <- get_q_c_matrix_r(get_q_c_matrix(n, K_up, ci_sim))
iter <- 2
# alpha_k
alpha_new <- matrix(0, nrow = q, ncol = K_up)
for(k in 1:K_up){
  y2 <- as.numeric(whole.data$data_y) - whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) # n*k
  y2 <- y2 * q_c_matrix
  alpha_k <- qr.solve(whole.data$Z * as.numeric(q_c_matrix[,k]), y2[,k])
  alpha_new[,k] <- alpha_k
  coef_alpha_est_list[[iter]] <- as.vector(alpha_new)
}
# beta_k
beta_new <- matrix(0, nrow = p, ncol = K_up)
for(k in 1:K_up){
  y2 <- as.numeric(whole.data$data_y) - whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q) # n*k
  y2 <- y2 * q_c_matrix
  beta_k <- qr.solve(whole.data$X * as.numeric(q_c_matrix[,k]), y2[,k])
  beta_new[,k] <- beta_k
  coef_beta_est_list[[iter]] <- as.vector(beta_new)
}
# mu
mu_est_list[[iter]] <- whole.data$X %*% beta_new + whole.data$Z %*% alpha_new
# mu_est_list[[iter]] <- apply(mu_est_list[[iter]], 2, mean)
# q_c_matrix 更新
pi_k <- pi_est_list[[iter-1]]
q_c_matrix <- matrix(0, nrow = n, ncol = K_up)
for(k in 1:K_up){
  q_c_matrix[,k] <- dnorm(whole.data$data_y,
                          mean = mu_est_list[[iter]][,k],
                          sd = 1/rho_est_list[[1]][k]) # 待修正
}
q_c_matrix <- q_c_matrix * kronecker(matrix(1, nrow = n, ncol = 1), matrix(pi_k, nrow = 1))
q_c_matrix <- q_c_matrix/apply(q_c_matrix, 1, sum)
pi_est_list[[iter]] <- apply(q_c_matrix, 2, mean)
```

```{r}
coef_alpha_est_list
coef_beta_est_list
```


```{r}
q_c_matrix <- get_q_c_matrix_r(get_q_c_matrix(n, K_up,ci_sim))
# for(iter in 2:iter_max){
for(iter in 2:100){
  for(k in 1:K_up){
    y2 <- as.numeric(whole.data$data_y) - whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) # n*k
    y2 <- y2 * q_c_matrix
    alpha_k <- qr.solve(whole.data$Z * as.numeric(q_c_matrix[,k]), y2[,k])
    alpha_new[,k] <- alpha_k
    coef_alpha_est_list[[iter]] <- as.vector(alpha_new)
  }
  # beta_k
  beta_new <- matrix(0, nrow = p, ncol = K_up)
  for(k in 1:K_up){
    y2 <- as.numeric(whole.data$data_y) - whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q) # n*k
    y2 <- y2 * q_c_matrix
    beta_k <- qr.solve(whole.data$X * as.numeric(q_c_matrix[,k]), y2[,k])
    beta_new[,k] <- beta_k
    coef_beta_est_list[[iter]] <- as.vector(beta_new)
  }
  # mu
  mu_est_list[[iter]] <- whole.data$X %*% beta_new + whole.data$Z %*% alpha_new
  # mu_est_list[[iter]] <- apply(mu_est_list[[iter]], 2, mean)
  # q_c_matrix 更新
  pi_k <- pi_est_list[[iter-1]]
  q_c_matrix <- matrix(0, nrow = n, ncol = K_up)
  for(k in 1:K_up){
    q_c_matrix[,k] <- dnorm(whole.data$data_y,
                            mean = mu_est_list[[iter]][,k],
                            sd = 1/rho_est_list[[1]][k]) # 待修正
  }
  q_c_matrix <- q_c_matrix * kronecker(matrix(1, nrow = n, ncol = 1), matrix(pi_k, nrow = 1))
  q_c_matrix <- q_c_matrix/apply(q_c_matrix, 1, sum)
  pi_est_list[[iter]] <- apply(q_c_matrix, 2, mean)
}
```

```{r}
cal_coef_diff <- function(coef_est, coef){
  return(sqrt(mean((coef - coef_est)**2)))
}
```

```{r}
# iter_tmp <- iter_max
iter_tmp <- 100
dif_alpha <- lapply(coef_alpha_est_list[2:iter_tmp], cal_coef_diff, coef_alpha_est_list[[1]])
plot(2:iter_tmp, unlist(dif_alpha))

dif_beta <- lapply(coef_beta_est_list[2:iter_tmp], cal_coef_diff, coef_beta_est_list[[1]])
plot(2:iter_tmp, unlist(dif_beta))
```

```{r}
iter_tmp <- iter_max
dif_alpha <- lapply(coef_alpha_est_list[2:iter_tmp], cal_coef_diff, coef_alpha_est_list[[1]])
plot(2:iter_tmp, unlist(dif_alpha))

dif_beta <- lapply(coef_beta_est_list[2:iter_tmp], cal_coef_diff, coef_beta_est_list[[1]])
plot(2:iter_tmp, unlist(dif_beta))
```


```{r}
coef_alpha_est_list
coef_beta_est_list
pi_est_list
```

## 上述基础上加上交互项

此部分需要重新生成数据，注意从现在开始 `whole.data` 发生改变

```{r}
# true coefficients
set.seed(999)
coef_true <- generate_coef_true(n, p, q, ci$ci_main, ci$ci_sub, 
                                coef_main_value,  coef_sub_value, incl_inter,
                                dim_nonzero_beta, dim_nonzero_alpha, dim_nonzero_gamma)
# Generate data
whole.data <- generate_sim_data(n, p, q, coef_true, cotype_x="AR_E", cotype_z="AR_E")
```

---


```{r}
mu_est_list[[iter]] <- apply((whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) +
  whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q)) * q_c_matrix, 1, sum)
y_mu_diff <- as.numeric(whole.data$data_y) - mu_est_list[[iter]]
rho_est_list[[iter]] <- sqrt(n / apply(q_c_matrix*y_mu_diff**2, 2, sum))
pi_est_list[[iter]] <- apply(q_c_matrix, 2, mean)
```














```{r}
# 检查残差
as.numeric(whole.data$data_y)
(whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) +
  whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q))
```




```{r}
iter <- 2
W <- q_c_matrix %*% t(q_c_matrix)
# y_tilde <- as.numeric(whole.data$data_y) - 
#   (whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) +
#   whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q)) 
y_tilde <- as.numeric(whole.data$data_y) -
  (whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p))
coef_alpha_est_list[[iter]] <- solve(t(whole.data$Z) %*% W %*% whole.data$Z) %*% 
  t(whole.data$Z) %*% W %*% y_tilde
 solve(t(whole.data$Z) %*% whole.data$Z) %*% 
  t(whole.data$Z) %*% y_tilde
```

```{r}
whole.data$data_y
as.numeric(whole.data$data_y) - (whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) + whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q)) * q_c_matrix
```




```{r}
denominator <- t(whole.data$Z) %*% q_c_matrix
numerator <- ((as.numeric(whole.data$data_y) - 
                 whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p)) * q_c_matrix) %>% 
  apply(2, sum)
coef_alpha_est_list[[iter]] <- as.vector(t(matrix(rep(numerator, q), ncol=q))/denominator)
print(t(matrix(rep(numerator, q), ncol=q)))
print(denominator)
print(t(matrix(rep(numerator, q), ncol=q))/denominator)
```






```{r}
for(iter in 2:4){
  pi_k <- pi_est_list[[iter-1]]
  q_c_matrix <- matrix(0, nrow = n, ncol = K_up)
  for(k in 1:K_up){
    q_c_matrix[,k] <- dnorm(whole.data$data_y,
                            mean = mu_est_list[[iter-1]][k],
                            sd = 1/rho_est_list[[iter-1]][k])
  }
  q_c_matrix <- q_c_matrix * kronecker(matrix(1, nrow = n, ncol = 1), matrix(pi_k, nrow = 1))
  q_c_matrix <- q_c_matrix/apply(q_c_matrix, 1, sum)
  
  # alpha_k
  denominator <- t(whole.data$Z) %*% q_c_matrix
  numerator <- ((as.numeric(whole.data$data_y) - 
                   whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p)) * q_c_matrix) %>% 
    apply(2, sum)
  coef_alpha_est_list[[iter]] <- as.vector(t(matrix(rep(numerator, q), ncol=q))/denominator)
  
  # beta_k
  denominator <- t(whole.data$X) %*% q_c_matrix
  numerator <- ((as.numeric(whole.data$data_y) - 
                   whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q)) * q_c_matrix) %>% 
    apply(2, sum)
  coef_beta_est_list[[iter]] <- as.vector(t(matrix(rep(numerator, p), ncol=p))/denominator)
  
  mu_est_list[[iter]] <- apply((whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) +
    whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q)) * q_c_matrix, 1, sum)
  y_mu_diff <- as.numeric(whole.data$data_y) - mu_est_list[[iter]]
  rho_est_list[[iter]] <- sqrt(n / apply(q_c_matrix*y_mu_diff**2, 2, sum))
  pi_est_list[[iter]] <- apply(q_c_matrix, 2, mean)
}
```

```{r}
coef_alpha_est_list
coef_beta_est_list
```



```{r}
iter <- 2
pi_k <- pi_est_list[[iter-1]]
q_c_matrix <- matrix(0, nrow = n, ncol = K_up)
for(k in 1:K_up){
  q_c_matrix[,k] <- dnorm(whole.data$data_y,
                          mean = mu_est_list[[iter-1]][k],
                          sd = 1/rho_est_list[[iter-1]][k])
}
q_c_matrix <- q_c_matrix * kronecker(matrix(1, nrow = n, ncol = 1), matrix(pi_k, nrow = 1))
q_c_matrix <- q_c_matrix/apply(q_c_matrix, 1, sum)
```


```{r}
# ======================================= PART 1 =======================================
# b_k_common <- 1/tau * sum(q_c_matrix[,k] *
#                             rho_est_list[[iter-1]][k]**2 *
#                             (whole.data$data_y - mu_est_list[[iter-1]][k]))
# -------------------------------------- PART 1.1 --------------------------------------
# alpha_k
denominator <- t(whole.data$Z) %*% q_c_matrix
numerator <- ((as.numeric(whole.data$data_y) - 
                 whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p)) * q_c_matrix) %>% 
  apply(2, sum)
coef_alpha_est_list[[iter]] <- as.vector(t(matrix(rep(numerator, q), ncol=q))/denominator)
print(t(matrix(rep(numerator, q), ncol=q)))
print(denominator)
print(coef_alpha_est_list[[iter]])
```

```{r}
ci_sim
```
      1 4 2 1 3 2 1 3 1 2 3 4 3 1 2 4 3 4 2 4

```{r}
q_c_matrix
```


```{r}
as.numeric(whole.data$data_y) - whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p)
```

```{r}
((as.numeric(whole.data$data_y) - 
                 whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p)) * q_c_matrix)
```


```{r}
whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q)
```


```{r}
# -------------------------------------- PART 1.2 --------------------------------------
# beta_k
denominator <- t(whole.data$X) %*% q_c_matrix
numerator <- ((as.numeric(whole.data$data_y) - 
                 whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q)) * q_c_matrix) %>% 
  apply(2, sum)
coef_beta_est_list[[iter]] <- as.vector((matrix(rep(numerator, p), ncol=p) %>% t())/denominator)
```








```{r}
# ======================================= PART 4 =======================================
# rho
mu_est_list[[iter]] <- apply((whole.data$X %*% matrix(coef_beta_est_list[[iter-1]], nrow=p) +
  whole.data$Z %*% matrix(coef_alpha_est_list[[iter-1]], nrow=q) +
  whole.data$W %*% matrix(coef_eta_est_list[[iter-1]], nrow=pq)) * q_c_matrix, 1, sum)

y_mu_diff_k <- kronecker(whole.data$data_y, matrix(1, nrow=1, ncol=K_up)) -
         kronecker(matrix(mu_est_list[[iter-1]], nrow=1), matrix(1, nrow=n, ncol=1))
rho_est_list[[iter]] <- sqrt(apply(q_c_matrix, 2, sum) / apply(q_c_matrix*y_mu_diff_k**2, 2, sum))

# ====================================== E 步补充 ======================================
# 此步更新，mu，qc 更新在 M 步之前完成
pi_est_list[[iter]] <- apply(q_c_matrix, 2, mean)
```



