---
title: "FMR compare"
author: "renyan"
date: "2022/6/21"
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```

```{r, echo = FALSE}
rm(list = ls(all = TRUE))
ls()
setwd("D:/Ryanna/RUC_courses/Y1_2/Group/code")
library(Matrix)
library(MASS)
library(fmrs)
library(ggplot2)
library(corrplot)
library(dplyr)
library(reshape2)
source("sim.r")
source("func.r")
```

```{r}
n <- 200                         # The sample size
p <- 4                           # The dimension of x
q <- 3                         # The dimension of z
pq <- q*p                        # The dimension of each sample
dim_nonzero_beta <- 2                         # The dimension of non-zero coefficients of x
dim_nonzero_alpha <- 2                        # The dimension of non-zero coefficients of z
dim_nonzero_gamma <- 4
balance <- T                     # Balanced/Imbalanced subgroup
gr_num_main <- 2                     # The number of rough subgroup 
gr_num_sub <- 4                       # The number of refined subgroup 
hier_struc <- list(c(1,2),c(3,4))  # Hierarchical subgroup structure
# sd.epsi<-0.5                     # The residual error
# corZX <- F                       # Correlated/Uncorrelated X and Z
intercorr0<-"AR1"                # The correlation structure of Z
signal_its <- 2 # signal intensity
K <- gr_num_sub
iter_max <- 10
eps <- 0.001
incl_inter <- FALSE               # 模拟实验数据生成时候是否要包含交互项

lambda_1 <- 0
lambda_2 <- 0
lambda_3 <- 0
a <- 3
iter_max <- 10
K_up <- 4
tau <- 1 

# ------------ Necessary parameters to support algorithm implementation --------
comb_pair <- combn(K,2)
H_3 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(pq)))
H_1 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(p)))
H_2 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(q)))

# ------------ Generate the regression coefficients -----------
coef_main_value <- c(signal_its, -signal_its)
# coef_main_value <- c(signal_its, 2signal_its)
coef_sub_value <- c(1.5*signal_its, 0.5*signal_its, -0.5*signal_its, -1.5*signal_its)
# coef_sub_value <- c(1*signal_its, 2*signal_its, 3*signal_its, 4*signal_its)
if(balance){pr_sub<-rep(1/gr_num_sub,gr_num_sub)}else{pr_sub<-c(1/6,1/6,1/3,1/3)}

# true main groups & subgroups
set.seed(999)
ci <- ci_generate(n, pr_sub, hier_struc)
ci_sim <- rep(0, n) # true label
for(i in 1:K){
  ci_sim[ci$ci_sub[[i]]] <- i
}

# true coefficients
set.seed(999)
coef_true <- generate_coef_true(n, p, q, ci$ci_main, ci$ci_sub, 
                                coef_main_value,  coef_sub_value, incl_inter,
                                dim_nonzero_beta, dim_nonzero_alpha, dim_nonzero_gamma)
# Generate data
whole.data <- generate_sim_data(n, p, q, coef_true, cotype_x="AR_E", cotype_z="AR_E")
```

```{r}
# ci_sim
# as.numeric(whole.data$data_y) - whole.data$X %*% coef_true$beta_true_K
# whole.data$Z %*% coef_true$alpha_true_K
y2_k <- as.numeric(whole.data$data_y) - whole.data$X %*% coef_true$beta_true_K # 模拟真实值情况
y2 <- NULL
for(i in 1:length(ci_sim)){
  y2[i] <- y2_k[i,ci_sim[i]]
}
# 模型变为 y = z alpha 的最简单情况
```


## fmrs package

```{r}
library(fmrs)
```


We use EM and Newton-Raphson algorithms in our method to find the maximizer of above Log-Likelihood.

需要 y 均为真实值

```{r}
# 初始化为真实系数
K_up <- 4
int_rm <- TRUE
as <- matrix(1, nrow = q + 1, ncol = K_up) # activeset parameter in fmrs package
if (int_rm) { as[1, ] <- 0 }
# init of init
coef_rough_init <- rbind(matrix(0, nrow=1, ncol=K_up), coef_true$alpha_true_K)
res.mle <- fmrs.mle(y = y2,
                  x = whole.data$Z,
                  delta = rep(1, length(y2)),
                  nComp = K_up,
                  disFamily = "norm",
                  initCoeff = coef_rough_init,
                  initDispersion = rep(1, K_up),
                  # initDispersion = rep(1, K_up),
                  initmixProp = rep(1 / K_up, K_up),
                  # nIterNR = 1000,
                  activeset = as)
coefficients(res.mle)
dispersion(res.mle)
mixProp(res.mle)
```

即使较大扰动也可以计算出正确结果

```{r}
# 初始化为扰动后的系数
# 参数扰动
disturb <- function(x, sd = 0.1, seed = 999){
  set.seed(999)
  return(x + rnorm(length(x), mean=0, sd = sd))
}

K_up <- 4
int_rm <- TRUE
as <- matrix(1, nrow = q + 1, ncol = K_up) # activeset parameter in fmrs package
if (int_rm) { as[1, ] <- 0 }
# init of init
coef_rough_init <- rbind(matrix(0, nrow=1, ncol=K_up), coef_true$alpha_true_K)
coef_rough_init <- disturb(coef_rough_init, sd = 0.1)
res.mle <- fmrs.mle(y = y2,
                  x = whole.data$Z,
                  delta = rep(1, length(y2)),
                  nComp = K_up,
                  disFamily = "norm",
                  initCoeff = coef_rough_init,
                  # initDispersion = rep(1, K_up),
                  initmixProp = rep(1 / K_up, K_up),
                  # nIterNR = 1000,
                  activeset = as)
coefficients(res.mle)
dispersion(res.mle)
mixProp(res.mle)
```

# flexmix package


- 虽然设置类别为 4 类，只得到两类，已经进行变量选择
- 不需要设置初始值
- 无法取消常数项

```{r}
library("flexmix")
X <- whole.data$Z
df_tmp <- data.frame(y=y2, x1=X[,1], x2=X[,2], x3=X[,3])
model <- flexmix(y~0+x1+x2+x3, data = df_tmp, k = K_up) # 0 去除常数项
parameters(model)
```


# 自己算

用加权最小二乘方法

```{r}
# 无扰动
X <- whole.data$Z
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
alpha <- matrix(0, nrow=q, ncol=K_up)
for(k in 1:4){
  W <- diag(q_c_matrix[,k])
  alpha_k <- solve(t(X)%*%W%*%X)%*%t(X)%*%W%*%y2
  alpha[,k] <- alpha_k
}
alpha

# 有扰动，需要继续迭代
X <- whole.data$Z
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
q_c_matrix <- get_q_c_matrix_r(q_c_matrix)
alpha <- matrix(0, nrow=q, ncol=K_up)
for(k in 1:4){
  W <- diag(q_c_matrix[,k])
  alpha_k <- solve(t(X)%*%W%*%X)%*%t(X)%*%W%*%y2
  alpha[,k] <- alpha_k
}
alpha
```

```{r}
get_diff <- function(x1, x2){
  dif <- sqrt(sum((as.vector(x1) - as.vector(x2))**2))
  return(dif)
}
```

## 真实分布-直接计算

得到正确结果

```{r}
X <- whole.data$Z
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
pi_k <- rep(1/K_up, K_up)
# update alpha
alpha <- matrix(0, nrow=q, ncol=K_up)
for(k in 1:4){
  W <- diag(q_c_matrix[,k])
  alpha_k <- solve(t(X)%*%W%*%X)%*%t(X)%*%W%*%y2
  alpha[,k] <- alpha_k
}
# updata q_c_matrix
q_c_matrix <- matrix(0, nrow = n, ncol = K_up)
for(k in 1:K_up){
  q_c_matrix[,k] <- dnorm(y2, mean = X %*% alpha[,k], sd = 1) # 待修正
}
q_c_matrix <- q_c_matrix * kronecker(matrix(1, nrow = n, ncol = 1), matrix(pi_k, nrow = 1))
q_c_matrix <- q_c_matrix/apply(q_c_matrix, 1, sum)
pi_k <- apply(q_c_matrix, 2, mean)
alpha
```

## 近似分布-迭代求解

即使很大扰动也可以很快收敛，结果接近真实值但是无法得到完全准确的结果

```{r}
X <- whole.data$Z
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
q_c_matrix <- get_q_c_matrix_r(q_c_matrix, 10)
pi_k <- rep(1/K_up, K_up)
scores <- NULL
alpha_init <- disturb(coef_true$alpha_true_K, sd = 0.1)
alpha <- alpha_init
# alpha <- coef_rough_init[2:4,]
for(i in 1:20){
  # updata q_c_matrix
  q_c_matrix <- dnorm(y2, mean = X %*% alpha, sd = 1) 
  q_c_matrix <- q_c_matrix * kronecker(matrix(1, nrow = n, ncol = 1), matrix(pi_k, nrow = 1))
  q_c_matrix <- q_c_matrix/apply(q_c_matrix, 1, sum)
  pi_k <- apply(q_c_matrix, 2, mean)
  print(pi_k)
  scores[i] <- get_diff(alpha, coef_true$alpha_true_K)
  # update alpha
  for(k in 1:4){
    W <- diag(q_c_matrix[,k])
    alpha_k <- solve(t(X)%*%W%*%X)%*%t(X)%*%W%*%y2
    alpha[,k] <- alpha_k
  }
}
scores
```


```{r}
alpha
```

```{r}
alpha
```



# 两部分依次计算

```{r}
ci_sim[1:10]
whole.data$data_y[1:10]
(whole.data$X %*% matrix(coef_true$beta_true_K, ncol=K_up) + whole.data$Z %*% matrix(coef_true$alpha_true_K, ncol=K_up))[1:10,]
```









