---
title: "Gradient_descent"
author: "任焱"
date: "2022-10-04"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE}
rm(list = ls(all = TRUE))
# setwd("D:/Ryanna/RUC_courses/Y1_2/Group/code")
library(Matrix)
library(MASS)
library(fmrs)
library(flexmix)
library(ggplot2)
library(corrplot)
library(dplyr)
library(reshape2)
library(latex2exp)
source("sim.r")
source("func.r")
source("estimate.r")
```


```{r}
n <- 200                         # The sample size
p <- 4                           # The dimension of x
q <- 3                         # The dimension of z
pq <- q*p                        # The dimension of each sample
dim_nonzero_beta <- 2                         # The dimension of non-zero coefficients of x
dim_nonzero_alpha <- 2                        # The dimension of non-zero coefficients of z
dim_nonzero_gamma <- 4
balance <- T                     # Balanced/Imbalanced subgroup
gr_num_main <- 2                     # The number of rough subgroup 
gr_num_sub <- 4                       # The number of refined subgroup 
hier_struc <- list(c(1,2),c(3,4))  # Hierarchical subgroup structure
# sd.epsi<-0.5                     # The residual error
# corZX <- F                       # Correlated/Uncorrelated X and Z
intercorr0<-"AR1"                # The correlation structure of Z
signal_its <- 2 # signal intensity
K <- gr_num_sub
iter_max <- 10
eps <- 0.001
incl_inter <- TRUE               # 模拟实验数据生成时候是否要包含交互项
tol <- 1e-5

lambda_1 <- 0
lambda_2 <- 0
lambda_3 <- 0
a <- 3
iter_max <- 20
K_up <- 4
tau <- 1 

# ------------ Necessary parameters to support algorithm implementation --------
comb_pair <- combn(K,2)
H_3 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(pq)))
H_1 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(p)))
H_2 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(q)))

# ------------ Generate the regression coefficients -----------
coef_main_value <- c(signal_its, -signal_its)
# coef_main_value <- c(signal_its, 2signal_its)
coef_sub_value <- c(1.5*signal_its, 0.5*signal_its, -0.5*signal_its, -1.5*signal_its)
# coef_sub_value <- c(1*signal_its, 2*signal_its, 3*signal_its, 4*signal_its)
if(balance){pr_sub<-rep(1/gr_num_sub,gr_num_sub)}else{pr_sub<-c(1/6,1/6,1/3,1/3)}

# true main groups & subgroups
set.seed(11)
ci <- ci_generate(n, pr_sub, hier_struc)
ci_sim <- rep(0, n) # true label
for(i in 1:K){
  ci_sim[ci$ci_sub[[i]]] <- i
}

# true coefficients
set.seed(11)
coef_true <- generate_coef_true(n, p, q, ci$ci_main, ci$ci_sub, 
                                coef_main_value,  coef_sub_value, incl_inter,
                                dim_nonzero_beta, dim_nonzero_alpha, dim_nonzero_gamma)
# Generate data
# whole.data <- generate_sim_data(n, p, q, coef_true, cotype_x="AR_E", cotype_z="AR_E")
whole.data <- generate_sim_data(n, p, q, coef_true, cotype_x="En", cotype_z="En")
```

非零版本

```{r}
p <- 2
q <- 2
x <- whole.data$X[,(1:p)]
z <- whole.data$Z[,(1:q)]
w <- matrix(0, n, p*q)
  for(i in 1:n){
    w[i,] <- kronecker(z[i,], x[i,])
  }
X <- cbind(x, z, w)
# 稠密真实参数
# 注意计算 y 时总要转化为 eta 版本
# coef_* 系列值总是 gamma 版本而非 eta
coef_true <- rbind(t(matrix(rep(c(2,2,-2,-2),4), 4)),
                   t(matrix(rep(c(3,1,-1,-3),4), 4)))
# y_true
y2 <- X %*% coef_gamma2eta(coef_true, p, q)
y <- NULL
for(i in 1:length(ci_sim)){ y[i] <- y2[i,ci_sim[i]] }
```


在进行以下实验之前现在 one_class 文件中多尝试异常情况并且记录

# 更新 $\eta$ 检查数据生成是不是有问题

```{r}
# 真值
coef_split_all <- coef_split(coef_true, p, q)
coef_beta_true <- coef_split_all[[1]]
coef_alpha_true <- coef_split_all[[2]]
coef_gamma_true <- coef_split_all[[3]]
coef_eta_true <- coef_split(coef_gamma2eta(coef_true, p, q), p, q)[[3]]
coef_true_v2 <- coef_gamma2eta(coef_true, p, q)
```



```{r}
iter_max <- 200
par(mfrow=c(2,2))
coef_est_v2 <- coef_true - coef_true

for(k in 1:K_up){
  y_one <- y[ci_sim == k]
  
  coef_alpha_one <- coef_alpha_true[,k] 
  coef_beta_one <- coef_beta_true[,k]
  coef_gamma_one <- coef_gamma_true[,k]
  coef_eta_one <- coef_eta_true[,k] 
  
  # 初始化
  coef_beta_one <- coef_beta_true[,k] -  coef_beta_true[,k] 
  coef_eta_one <- coef_eta_true[,k] - coef_eta_true[,k] 
  W <- diag(1, length(y_one))
  x_alpha_k <- z[ci_sim == k,]
  y_alpha_k <- y_one
  coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k 
  
  coef_dist <- NULL
  evs <- NULL
  for(iter in 1:iter_max){
    ev <- NULL
    coef_old <- c(coef_alpha_one, coef_beta_one, coef_eta_one)
    coef_dist[[iter]] <- sum((coef_true_v2[,k]-
                                c(coef_beta_one, coef_alpha_one, coef_eta_one))**2)
    W <- diag(1, length(y_one))
    
    print(iter)
    print(matrix(c(coef_beta_one, coef_alpha_one, coef_eta_one), ncol=1))
    
    # beta
    x_beta_k <- x[ci_sim == k,] 
    y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_one - w[ci_sim == k,]%*%coef_eta_one
    coef_beta_one <- solve(t(x_beta_k)%*%W%*%x_beta_k+diag(0.1,p))%*%t(x_beta_k)%*%W%*%y_beta_k
    
    # eta
    x_eta_k <- w[ci_sim == k,]
    y_eta_k <- y_one - x[ci_sim == k,]%*%coef_beta_one - z[ci_sim == k,]%*%coef_alpha_one
    coef_eta_one <- solve(t(x_eta_k)%*%W%*%x_eta_k+diag(0.1,p*q))%*%t(x_eta_k)%*%W%*%y_eta_k
    
    # alpha
    x_alpha_k <- z[ci_sim == k,]
    y_alpha_k <- y_one - x_beta_k%*%coef_beta_one - x_eta_k%*%coef_eta_one
    coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k
    
    ev <- c(ev, eigen(t(x_beta_k)%*%W%*%x_beta_k)$val)
    ev <- c(ev, eigen(t(x_alpha_k)%*%W%*%x_alpha_k)$val)
    ev <- c(ev, eigen(t(x_eta_k)%*%W%*%x_eta_k)$val)
    evs[[iter]] <- ev
    
    coef_cur <- c(coef_alpha_one, coef_beta_one, coef_eta_one)
    coef_est_v2[,k] <- coef_cur
    coef_est <- coef_eta2gamma(coef_est_v2, p, q)
    if(sum((coef_cur - coef_old)**2) < 1e-5){
      print("converge with no coef change")
      # return()
      break()
    }
  }
  # "Coef Distance (Est from True)\n",
  plot(1:length(coef_dist), unlist(coef_dist), main = paste("Coef Distance K =", k),
       xlab = "Iteration", ylab = "Distance")
}
print(coef_est)
```

直接更新 $\eta$ 不会出现上述问题，此时为凸问题，且回解 $\gamma$ 时也不会出问题


```{r}
iter_max <- 200
par(mfrow=c(2,2))
coef_est <- coef_true - coef_true

for(k in 1:K_up){
  y_one <- y[ci_sim == k]
  
  coef_alpha_one <- coef_alpha_true[,k] 
  coef_beta_one <- coef_beta_true[,k]
  coef_gamma_one <- coef_gamma_true[,k]
  coef_eta_one <- coef_eta_true[,k] 
  
  # 初始化
  coef_beta_one <- coef_beta_true[,k] -  coef_beta_true[,k] 
  coef_gamma_one <- coef_gamma_true[,k] - coef_gamma_true[,k] 
  W <- diag(1, length(y_one))
  x_alpha_k <- z[ci_sim == k,]
  y_alpha_k <- y_one
  coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k 
  
  coef_dist <- NULL
  evs <- NULL
  for(iter in 1:iter_max){
    ev <- NULL
    coef_old <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
    coef_dist[[iter]] <- sum((coef_true[,k]-
                                c(coef_beta_one, coef_alpha_one, coef_gamma_one))**2)
    W <- diag(1, length(y_one))
    
    print(iter)
    print(matrix(c(coef_beta_one, coef_alpha_one, coef_gamma_one), ncol=1))
    
    # beta
    x_beta_k <- x[ci_sim == k,] + t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_one))
    y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_one
    coef_beta_one <- solve(t(x_beta_k)%*%W%*%x_beta_k+diag(0.1,p))%*%t(x_beta_k)%*%W%*%y_beta_k
    
    # gamam
    x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_one))
    y_gamma_k <- y_one - x[ci_sim == k,]%*%coef_beta_one - z[ci_sim == k,]%*%coef_alpha_one
    coef_gamma_one <- solve(t(x_gamma_k)%*%W%*%x_gamma_k+diag(0.1,p*q))%*%t(x_gamma_k)%*%W%*%y_gamma_k
    
    # alpha
    x_alpha_k <- z[ci_sim == k,]
    y_alpha_k <- y_one - x_beta_k%*%coef_beta_one
    coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k
    
    ev <- c(ev, eigen(t(x_beta_k)%*%W%*%x_beta_k)$val)
    ev <- c(ev, eigen(t(x_alpha_k)%*%W%*%x_alpha_k)$val)
    ev <- c(ev, eigen(t(x_gamma_k)%*%W%*%x_gamma_k)$val)
    evs[[iter]] <- ev
    
    coef_cur <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
    coef_est[,k] <- coef_cur
    if(sum((coef_cur - coef_old)**2) < 1e-5){
      print("converge with no coef change")
      # return()
      break()
    }
  }
  # "Coef Distance (Est from True)\n",
  plot(1:length(coef_dist), unlist(coef_dist), main = paste("Coef Distance K =", k),
       xlab = "Iteration", ylab = "Distance")
}
print(coef_est)
```



# 梯度下降

结论几乎一致，问题的根源应该不在于矩阵求逆

```{r}
f <- function(X,y,b) {
   (1/2)*norm(y-X%*%b,"F")^{2}
}
grad_f <- function(X,y,b) {
   t(X)%*%(X%*%b - y)
}
```


```{r}
library(gettingtothebottom)

iter_max <- 20
par(mfrow=c(2,2))
coef_est <- coef_true - coef_true

for(k in 1:K_up){
  y_one <- y[ci_sim == k]
  
  coef_alpha_one <- coef_alpha_true[,k] 
  coef_beta_one <- coef_beta_true[,k]
  coef_gamma_one <- coef_gamma_true[,k]
  coef_eta_one <- coef_eta_true[,k] 
  
  # 初始化
  coef_beta_one <- coef_beta_true[,k] -  coef_beta_true[,k] 
  coef_gamma_one <- coef_gamma_true[,k] - coef_gamma_true[,k] 
  W <- diag(1, length(y_one))
  x_alpha_k <- z[ci_sim == k,]
  y_alpha_k <- y_one
  coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k 
  
  coef_dist <- NULL
  evs <- NULL
  for(iter in 1:iter_max){
    ev <- NULL
    coef_old <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
    coef_dist[[iter]] <- sum((coef_true[,k]-
                                c(coef_beta_one, coef_alpha_one, coef_gamma_one))**2)
    W <- diag(1, length(y_one))
    
    print(iter)
    print(matrix(c(coef_beta_one, coef_alpha_one, coef_gamma_one), ncol=1))
    
    # beta
    x_beta_k <- x[ci_sim == k,] + t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_one))
    y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_one
    # coef_beta_one <- solve(t(x_beta_k)%*%W%*%x_beta_k+diag(0.1,p))%*%t(x_beta_k)%*%W%*%y_beta_k
    gd_beta <- gdescent(f,grad_f,x_beta_k,y_beta_k,0.01,intercept = FALSE)
    coef_beta_one <- gd_beta$b[,gd_beta$iter-1]
    
    # gamam
    x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_one))
    y_gamma_k <- y_one - x[ci_sim == k,]%*%coef_beta_one - z[ci_sim == k,]%*%coef_alpha_one
    # coef_gamma_one <- solve(t(x_gamma_k)%*%W%*%x_gamma_k+diag(0.1,p*q))%*%t(x_gamma_k)%*%W%*%y_gamma_k
    gd_gamma <- gdescent(f,grad_f,x_gamma_k,y_gamma_k,0.01,intercept = FALSE)
    coef_gamma_one <- gd_gamma$b[,gd_gamma$iter-1]
    
    # alpha
    x_alpha_k <- z[ci_sim == k,]
    y_alpha_k <- y_one - x_beta_k%*%coef_beta_one
    coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k
    
    ev <- c(ev, eigen(t(x_beta_k)%*%W%*%x_beta_k)$val)
    ev <- c(ev, eigen(t(x_alpha_k)%*%W%*%x_alpha_k)$val)
    ev <- c(ev, eigen(t(x_gamma_k)%*%W%*%x_gamma_k)$val)
    evs[[iter]] <- ev
    
    coef_cur <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
    coef_est[,k] <- coef_cur
    if(sum((coef_cur - coef_old)**2) < 1e-5){
      print("converge with no coef change")
      # return()
      break()
    }
  }
  # "Coef Distance (Est from True)\n",
  plot(1:length(coef_dist), unlist(coef_dist), main = paste("Coef Distance K =", k),
       xlab = "Iteration", ylab = "Distance")
}
print(coef_est)
```

# 再细看错误例子


用矩阵取逆的方法至少参数距离真值会越来越近，但是如果使用梯度下降的方法，参数离真值的距离反而会线性增长

## 检查单个类别中相对自变量计算正确性

```{r}
# 检查 gamma 相关自变量计算正确性
# 等价
k <- 4
y_one <- y[ci_sim == k]
x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_true[,k]))
y_one_est <- z[ci_sim == k,]%*%coef_alpha_true[,k] +
  x[ci_sim == k,]%*%coef_beta_true[,k] +
  x_gamma_k%*%coef_gamma_true[,k]
hist(y_one-y_one_est)
```

```{r}
# 以下二者等价
# t1 <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_true[,k]))
# t2 <- t(apply(w, 1, get_gamma_var_fromlast, p, q, coef_beta_true[,k]))
# t1 == t2[ci_sim == k,]
```


```{r}
# 检查 beta 相关自变量计算正确性
# 等价，但要记得加上 x
k <- 4
y_one <- y[ci_sim == k]
x_beta_k <- t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_true[,k]))
y_one_est <- z[ci_sim == k,]%*%coef_alpha_true[,k] +
  (x[ci_sim == k,] + x_beta_k)%*%coef_beta_true[,k]
hist(y_one-y_one_est)
```




```{r}
# main --------------------------------------------------------------------
k <- 4
y_one <- y[ci_sim == k]

coef_alpha_one <- coef_alpha_true[,k] 
coef_beta_one <- coef_beta_true[,k]
coef_gamma_one <- coef_gamma_true[,k]
coef_eta_one <- coef_eta_true[,k] 

# 初始化
coef_beta_one <- coef_beta_true[,k] -  coef_beta_true[,k] 
coef_gamma_one <- coef_gamma_true[,k] - coef_gamma_true[,k] 
W <- diag(1, length(y_one))
x_alpha_k <- z[ci_sim == k,]
y_alpha_k <- y_one
coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k 


W <- diag(1, length(y_one))
# beta
x_beta_k <- x[ci_sim == k,] + t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_one))
y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_one
coef_beta_one <- solve(t(x_beta_k)%*%W%*%x_beta_k+diag(0.1,p))%*%t(x_beta_k)%*%W%*%y_beta_k
# gd_beta <- gdescent(f,grad_f,x_beta_k,y_beta_k,0.01,intercept = FALSE)
# coef_beta_one <- gd_beta$b[,gd_beta$iter-1]
# main --------------------------------------------------------------------
```

```{r}
# beta
par(mfrow = c(2, 1))
W <- diag(1, length(y_one))
x_beta_k <- x[ci_sim == k,] + 
  t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_true[,k]))
y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_true[,k]
y_beta_true <- x_beta_k%*%coef_beta_true[,k]
y_beta_est <- x_beta_k%*%coef_beta_one
hist(y_beta_k - y_beta_true)
hist(y_beta_k - y_beta_est)
sum((y_beta_k - y_beta_true)**2)
sum((y_beta_k - y_beta_est)**2)

par(mfrow = c(2, 1))
W <- diag(1, length(y_one))
x_beta_k <- x[ci_sim == k,] + 
  t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_one))
y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_one
y_beta_true <- x_beta_k%*%coef_beta_true[,k]
y_beta_est <- x_beta_k%*%coef_beta_one
hist(y_beta_k - y_beta_true)
hist(y_beta_k - y_beta_est)
sum((y_beta_k - y_beta_true)**2)
sum((y_beta_k - y_beta_est)**2)
```

```{r}
# gamam
x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_one))
y_gamma_k <- y_one - x[ci_sim == k,]%*%coef_beta_one - z[ci_sim == k,]%*%coef_alpha_one
coef_gamma_one <- solve(t(x_gamma_k)%*%W%*%x_gamma_k+diag(0.1,p*q))%*%t(x_gamma_k)%*%W%*%y_gamma_k
# gd_gamma <- gdescent(f,grad_f,x_gamma_k,y_gamma_k,0.01,intercept = FALSE)
# coef_gamma_one <- gd_gamma$b[,gd_gamma$iter-1]
```


```{r}
# gamma
par(mfrow = c(2, 1))
W <- diag(1, length(y_one))
x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_true[,k]))
y_gamma_k <- y_one - x[ci_sim == k,]%*%coef_beta_true[,k] - z[ci_sim == k,]%*%coef_alpha_true[,k]
y_gamma_true <- x_gamma_k%*%coef_gamma_true[,k]
y_gamma_est <- x_gamma_k%*%coef_gamma_one
hist(y_gamma_k - y_gamma_true)
hist(y_gamma_k - y_gamma_est)
sum((y_gamma_k - y_gamma_true)**2)
sum((y_gamma_k - y_gamma_est)**2)

par(mfrow = c(2, 1))
W <- diag(1, length(y_one))
x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_one))
y_gamma_k <- y_one - x[ci_sim == k,]%*%coef_beta_one - z[ci_sim == k,]%*%coef_alpha_one
y_gamma_true <- x_gamma_k%*%coef_gamma_true[,k]
y_gamma_est <- x_gamma_k%*%coef_gamma_one
hist(y_gamma_k - y_gamma_true)
hist(y_gamma_k - y_gamma_est)
sum((y_gamma_k - y_gamma_true)**2)
sum((y_gamma_k - y_gamma_est)**2)
```



```{r}
# main --------------------------------------------------------------------
coef_dist <- NULL
evs <- NULL
for(iter in 1:10){
  ev <- NULL
  coef_old <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
  coef_dist[[iter]] <- sum((coef_true[,k]-
                              c(coef_beta_one, coef_alpha_one, coef_gamma_one))**2)
  W <- diag(1, length(y_one))
  
  print(iter)
  print(matrix(c(coef_beta_one, coef_alpha_one, coef_gamma_one), ncol=1))
  
  # beta
  x_beta_k <- x[ci_sim == k,] + t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_one))
  y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_one
  coef_beta_one <- solve(t(x_beta_k)%*%W%*%x_beta_k+diag(0.1,p))%*%t(x_beta_k)%*%W%*%y_beta_k
  # gd_beta <- gdescent(f,grad_f,x_beta_k,y_beta_k,0.01,intercept = FALSE)
  # coef_beta_one <- gd_beta$b[,gd_beta$iter-1]
  
  # gamam
  x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_one))
  y_gamma_k <- y_one - x[ci_sim == k,]%*%coef_beta_one - z[ci_sim == k,]%*%coef_alpha_one
  coef_gamma_one <- solve(t(x_gamma_k)%*%W%*%x_gamma_k+diag(0.1,p*q))%*%t(x_gamma_k)%*%W%*%y_gamma_k
  # gd_gamma <- gdescent(f,grad_f,x_gamma_k,y_gamma_k,0.01,intercept = FALSE)
  # coef_gamma_one <- gd_gamma$b[,gd_gamma$iter-1]
  
  # alpha
  x_alpha_k <- z[ci_sim == k,]
  y_alpha_k <- y_one - x_beta_k%*%coef_beta_one
  coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k
  
  ev <- c(ev, eigen(t(x_beta_k)%*%W%*%x_beta_k)$val)
  ev <- c(ev, eigen(t(x_alpha_k)%*%W%*%x_alpha_k)$val)
  ev <- c(ev, eigen(t(x_gamma_k)%*%W%*%x_gamma_k)$val)
  evs[[iter]] <- ev
  
  coef_cur <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
  coef_est[,k] <- coef_cur
  if(sum((coef_cur - coef_old)**2) < 1e-5){
    print("converge with no coef change")
    # return()
    break()
  }
}
# "Coef Distance (Est from True)\n",
plot(1:length(coef_dist), unlist(coef_dist), main = paste("Coef Distance K =", k),
     xlab = "Iteration", ylab = "Distance")
```

# 尝试多组初始值

框架不改变，但对于改组数据使用多次随机的初始值

```{r}
# 仅对于单类设定几组初始值
# y_one 是为了固定初始化的 alpha 传递，其他地方不需要
# 固定初始化效果较稳定，首先进行检验
coef_est_init <- function(y_one, p, q, seeds = c(1), sd = 0.1){
  coef_est_list <- NULL
  # 固定初始化
  coef_beta_one <- rep(0, p)
  coef_gamma_one <- rep(0, p*q)
  x_alpha_k <- z[ci_sim == k,]
  y_alpha_k <- y_one
  coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k 
  coef_est_list[[1]] <- c(coef_beta_one, coef_alpha_one, coef_gamma_one)
  # 随机初始化
  for(init_idx in 2:(length(seeds)+1)){
    set.seed(seeds[init_idx])
    coef_est_list[[init_idx]] <- rnorm(p+q+p*q, mean = 0, sd = sd)
  }
  return(coef_est_list)
}
```


```{r}
library(itertools)
iter_max <- 200
k <- 2
y_one <- y[ci_sim == k]

# par(mfrow = c(4, 4))
# coef_init_sets <- coef_est_init(y_one, p, q, (2:8)*8)
seeds_list <- (2:100)*8
coef_init_sets <- coef_est_init(y_one, p, q, seeds_list)
mse_list <- NULL
coef_est_list <- NULL
for(coef_idx in 1:length(coef_init_sets)){
  coef_est <- coef_init_sets[[coef_idx]]
  print(coef_est)
  coef_beta_one <- coef_est[1:p]
  coef_alpha_one <- coef_est[(p+1):(p+q)]
  coef_gamma_one <- coef_est[(p+q+1):(p+q+p*q)]
  
  coef_dist <- NULL
  for(iter in 1:iter_max){
    coef_old <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
    coef_dist[[iter]] <- sum((coef_true[,k]-
                                c(coef_beta_one, coef_alpha_one, coef_gamma_one))**2)
    W <- diag(1, length(y_one))
    
    # print(iter)
    # print(matrix(c(coef_beta_one, coef_alpha_one, coef_gamma_one), ncol=1))
    
    # beta
    x_beta_k <- x[ci_sim == k,] + t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_one))
    y_beta_k <- y_one - z[ci_sim == k,]%*%coef_alpha_one
    coef_beta_one <- solve(t(x_beta_k)%*%W%*%x_beta_k+diag(0.1,p))%*%t(x_beta_k)%*%W%*%y_beta_k
    # gd_beta <- gdescent(f,grad_f,x_beta_k,y_beta_k,0.01,intercept = FALSE)
    # coef_beta_one <- gd_beta$b[,gd_beta$iter-1]
    
    # gamam
    x_gamma_k <- t(apply(w[ci_sim == k,], 1, get_gamma_var_fromlast, p, q, coef_beta_one))
    y_gamma_k <- y_one - x[ci_sim == k,]%*%coef_beta_one - z[ci_sim == k,]%*%coef_alpha_one
    coef_gamma_one <- solve(t(x_gamma_k)%*%W%*%x_gamma_k+diag(0.1,p*q))%*%t(x_gamma_k)%*%W%*%y_gamma_k
    # gd_gamma <- gdescent(f,grad_f,x_gamma_k,y_gamma_k,0.01,intercept = FALSE)
    # coef_gamma_one <- gd_gamma$b[,gd_gamma$iter-1]
    
    # alpha
    x_alpha_k <- z[ci_sim == k,]
    y_alpha_k <- y_one - x_beta_k%*%coef_beta_one
    coef_alpha_one <- solve(t(x_alpha_k)%*%W%*%x_alpha_k+diag(0.1,q))%*%t(x_alpha_k)%*%W%*%y_alpha_k
    
    coef_cur <- c(coef_alpha_one, coef_beta_one, coef_gamma_one)
    if(sum((coef_cur - coef_old)**2) < 1e-5){
      print("converge with no coef change")
      # return()
      break()
    }
  }
  # "Coef Distance (Est from True)\n",
  # plot(1:length(coef_dist), unlist(coef_dist), main = paste("Coef Distance K =", k),
  #      xlab = "Iteration", ylab = "Distance")
  # 
  x_beta_k <- x[ci_sim == k,] + t(apply(w[ci_sim == k,], 1, get_beta_var_fromlast, p, q, coef_gamma_one))
  y_est <- z[ci_sim == k,]%*%coef_alpha_one + x_beta_k%*%coef_beta_one
  # hist(y_est - y_one, main = paste0("Residual histogram with MSE: ", sum((y_est - y_one)**2)))
  # print("******************************")
  # print(coef_cur)
  
  mse_list[[coef_idx]] <- sum((y_est - y_one)**2)
  coef_est_list[[coef_idx]] <- coef_cur
  
  if(sum((y_est - y_one)**2) < 1){
    print("Find the ideal coef!")
    return()
  }
}


# 迭代到较好结果，提前终止循环，理想情况应当出现该类情况
if(coef_idx < length(coef_init_sets)){
  coef_est_one <- coef_est_list[[which.min(unlist(mse_list))]]
}else{
  print("No ideal results. Check the plot.")
}
plot(unlist(mse_list), main = "MSE of Different Initial Values", ylab = "MSE")
coef_est_one
```








