---
title: "2022-08-19"
author: "renyan"
date: '2022-08-19'
date: '2022-08-11'
output: 
  prettydoc::html_pretty:
    theme: cayman
    highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
```


```{r, echo = FALSE}
rm(list = ls(all = TRUE))
# setwd("D:/Ryanna/RUC_courses/Y1_2/Group/code")
library(Matrix)
library(MASS)
library(fmrs)
library(flexmix)
library(ggplot2)
library(corrplot)
library(dplyr)
library(reshape2)
source("sim.r")
source("func.r")
source("estimate.r")
```


```{r}
n <- 200                         # The sample size
p <- 4                           # The dimension of x
q <- 3                         # The dimension of z
pq <- q*p                        # The dimension of each sample
dim_nonzero_beta <- 2                         # The dimension of non-zero coefficients of x
dim_nonzero_alpha <- 2                        # The dimension of non-zero coefficients of z
dim_nonzero_gamma <- 4
balance <- T                     # Balanced/Imbalanced subgroup
gr_num_main <- 2                     # The number of rough subgroup 
gr_num_sub <- 4                       # The number of refined subgroup 
hier_struc <- list(c(1,2),c(3,4))  # Hierarchical subgroup structure
# sd.epsi<-0.5                     # The residual error
# corZX <- F                       # Correlated/Uncorrelated X and Z
intercorr0<-"AR1"                # The correlation structure of Z
signal_its <- 2 # signal intensity
K <- gr_num_sub
iter_max <- 10
eps <- 0.001
incl_inter <- FALSE               # 模拟实验数据生成时候是否要包含交互项
tol <- 1e-5

lambda_1 <- 0
lambda_2 <- 0
lambda_3 <- 0
a <- 3
iter_max <- 20
K_up <- 4
tau <- 1 

# ------------ Necessary parameters to support algorithm implementation --------
comb_pair <- combn(K,2)
H_3 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(pq)))
H_1 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(p)))
H_2 <- kronecker(Matrix(t(apply(comb_pair,2,dMatrixFun)),sparse = T),bdiag(diag(q)))

# ------------ Generate the regression coefficients -----------
coef_main_value <- c(signal_its, -signal_its)
# coef_main_value <- c(signal_its, 2signal_its)
coef_sub_value <- c(1.5*signal_its, 0.5*signal_its, -0.5*signal_its, -1.5*signal_its)
# coef_sub_value <- c(1*signal_its, 2*signal_its, 3*signal_its, 4*signal_its)
if(balance){pr_sub<-rep(1/gr_num_sub,gr_num_sub)}else{pr_sub<-c(1/6,1/6,1/3,1/3)}

# true main groups & subgroups
set.seed(999)
ci <- ci_generate(n, pr_sub, hier_struc)
ci_sim <- rep(0, n) # true label
for(i in 1:K){
  ci_sim[ci$ci_sub[[i]]] <- i
}

# true coefficients
set.seed(999)
coef_true <- generate_coef_true(n, p, q, ci$ci_main, ci$ci_sub, 
                                coef_main_value,  coef_sub_value, incl_inter,
                                dim_nonzero_beta, dim_nonzero_alpha, dim_nonzero_gamma)
# Generate data
whole.data <- generate_sim_data(n, p, q, coef_true, cotype_x="AR_E", cotype_z="AR_E")
```



# $y = X\beta$

## package

以下为简单情况的单独设定

```{r}
beta_true <- t(matrix(rep(c(-2,-1,1,2),4), 4))
x <- whole.data$X
X <- x
y2 <- x %*% beta_true
y <- NULL
for(i in 1:length(ci_sim)){ y[i] <- y2[i,ci_sim[i]] }
```

fmrs 如果稍微进行扰动很那到真实情况

```{r}
K_up <- 4
xdim <- p
int_rm <- TRUE
as <- matrix(1, nrow = xdim+1, ncol = K_up) # activeset parameter in fmrs package
if (int_rm) { as[1, ] <- 0 }
# init of init
# beta_init <- beta_true
set.seed(999)
beta_init <- beta_true - beta_true + rnorm(length(beta_true), mean = 0, sd = 4)
coef_rough_init <- rbind(matrix(0, nrow=1, ncol=K_up), beta_init)
# coef_rough_init <- disturb(coef_rough_init, sd = 1)
res.mle <- fmrs.mle(y = y,
                  x = x,
                  delta = rep(1, n),
                  nComp = K_up,
                  disFamily = "norm",
                  initCoeff = coef_rough_init,
                  # initDispersion = rep(1, K_up),
                  initmixProp = rep(1 / K_up, K_up),
                  # nIterNR = 1000,
                  activeset = as)
coefficients(res.mle)
print("dispersion")
dispersion(res.mle)
print("mixprop")
mixProp(res.mle)
```

```{r}
colnames(x) <- paste0("X", 1:(xdim))
df_tmp <- cbind(data.frame(y=y), x)
model <- flexmix(y~0+., data = df_tmp, k = K_up) # 0 去除常数项
parameters(model)
```

## 迭代-同$\rho$

```{r}
# 同 rho 版本
coef_true <- beta_true
set.seed(999)
# 完全随机
# coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 4)
coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 0.01)
# 基于正确答案进行干扰
# coef_init <- coef_true + rnorm(length(coef_true), mean = 0, sd = 1) # 在真值附近很容易收敛
coef_est <- coef_init

pi_est <- rep(1/K_up, K_up)
pi_est_list <- list(pi_est)

rho_est_list <- list(c(1,1,1,1))

X <- x
print(coef_est)
for (iter in 2:100) {
 
  # ********************* 更新后验概率矩阵 *********************
  if (iter == 2) {
    q_c_matrix <- t(t(matrix(1 / (y - (X %*% coef_est))**2, ncol = K_up)) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  } else {
    q_c_matrix <- t(t(dnorm(y, mean = X %*% coef_est, 
                            sd = 1 / mean(rho_est_list[[iter - 1]]))) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
    vanishidx <- which(apply(q_c_matrix, 1, function(x) { sum(x) %>% is.na()}))
    if (!identical(vanishidx, integer(0))) {
      print(paste("******************", vanishidx, "****************"))
      # 若有密度消失样本，归为距离均值最近的类别
      # 应再处理 rho 暂时忽略这步
      q_c_matrix_addin <- t(t(matrix(1 / (y[vanishidx] - (X %*% coef_est)[vanishidx, ])**2, ncol = K_up)) * pi_est_list[[iter - 1]])
      q_c_matrix_addin <- q_c_matrix_addin / apply(q_c_matrix_addin, 1, sum)
      q_c_matrix[vanishidx, ] <- q_c_matrix_addin
    }
  }
  
  # *************************** 更新 pi ******************************
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_est_list[[iter]] <- pi_est
  
  # *************************** 更新参数 ******************************
  coef_old <- coef_est
  for (k in 1:K_up) {
    W <- diag(q_c_matrix[, k])
    coef_k <- solve(t(X) %*% W %*% X) %*% t(X) %*% W %*% y
    coef_est[, k] <- coef_k
  }
  rho_est <- rep(sqrt(n / sum((y - X %*% coef_est)**2 * q_c_matrix)), 4)
  rho_est_list[[iter]] <- rho_est
  
  # *************************** 判断收敛 ******************************
  if (sum((y - X %*% coef_est)**2 * q_c_matrix) < 1e-8) {
    print("converge")
    return()
  }else if(sum((coef_est - coef_old)**2) < 1e-15){
    print('converge with no coef change')
    return()
  }
  # print(iter)
  # print(beta_est)
  # print(rho_est)
  ci_est <- apply(q_c_matrix, 1, which.max)
  # print(right_class_ratio(ci_sim, ci_est))
  print(plot_classdis(20, coef_est, rho_est_list[[iter-1]]))
}
```

## 迭代-不同$\rho$

```{r}
# 不同 rho 版本
coef_true <- beta_true
set.seed(999)
# 完全随机
# coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 4)
coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 0.01)
# 基于正确答案进行干扰
# coef_init <- coef_true + rnorm(length(coef_true), mean = 0, sd = 1) # 在真值附近很容易收敛
coef_est <- coef_init

pi_est <- rep(1/K_up, K_up)
pi_est_list <- list(pi_est)

rho_est_list <- list(c(1,1,1,1))

X <- x
print(coef_est)
for (iter in 2:100) {
 
  # ********************* 更新后验概率矩阵 *********************
  if (iter == 2) {
    q_c_matrix <- t(t(matrix(1 / (y - (X %*% coef_est))**2, ncol = K_up)) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  } else {
    q_c_matrix <- t(t(dnorm(y, mean = X %*% coef_est, 
                            sd = 1 / mean(rho_est_list[[iter - 1]]))) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
    vanishidx <- which(apply(q_c_matrix, 1, function(x) { sum(x) %>% is.na()}))
    if (!identical(vanishidx, integer(0))) {
      print(paste("******************", vanishidx, "****************"))
      # 若有密度消失样本，归为距离均值最近的类别
      # 应再处理 rho 暂时忽略这步
      q_c_matrix_addin <- t(t(matrix(1 / (y[vanishidx] - (X %*% coef_est)[vanishidx, ])**2, ncol = K_up)) * pi_est_list[[iter - 1]])
      q_c_matrix_addin <- q_c_matrix_addin / apply(q_c_matrix_addin, 1, sum)
      q_c_matrix[vanishidx, ] <- q_c_matrix_addin
    }
  }
  
  # *************************** 更新 pi ******************************
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_est_list[[iter]] <- pi_est
  
  # *************************** 更新参数 ******************************
  coef_old <- coef_est
  for (k in 1:K_up) {
    W <- diag(q_c_matrix[, k])
    coef_k <- solve(t(X) %*% W %*% X) %*% t(X) %*% W %*% y
    coef_est[, k] <- coef_k
  }
  rho_est <- sqrt(apply(q_c_matrix, 2, sum) / apply((y - X %*% coef_est)**2 * q_c_matrix, 2, sum))
  rho_est_list[[iter]] <- rho_est
  
  # *************************** 判断收敛 ******************************
  if (sum((y - X %*% coef_est)**2 * q_c_matrix) < 1e-8) {
    print("converge")
    return()
  }else if(sum((coef_est - coef_old)**2) < 1e-15){
    print('converge with no coef change')
    return()
  }
  # print(iter)
  # print(beta_est)
  # print(rho_est)
  ci_est <- apply(q_c_matrix, 1, which.max)
  # print(right_class_ratio(ci_sim, ci_est))
  print(plot_classdis(20, coef_est, rho_est_list[[iter-1]]))
}
```


# $y = X\beta + Z\alpha$

```{r}
beta_true <- rbind(t(matrix(rep(c(-2,-1,1,2),2), 4)), 
                   t(matrix(rep(c(0,0,0,0),p-2), 4)))
alpha_true <- rbind(t(matrix(rep(c(-2,-1,1,2),2), 4)), 
                   t(matrix(rep(c(0,0,0,0),q-2), 4)))
coef_true <- rbind(beta_true, alpha_true)
x <- whole.data$X
z <- whole.data$Z
X <- cbind(x, z)
y2 <- X %*% coef_true
y <- NULL
for(i in 1:length(ci_sim)){ y[i] <- y2[i,ci_sim[i]] }
```

## 整体

### package

作为对照组

```{r}
K_up <- 4
xdim <- p+q
int_rm <- TRUE
as <- matrix(1, nrow = xdim+1, ncol = K_up) # activeset parameter in fmrs package
if (int_rm) { as[1, ] <- 0 }
# init of init
coef_init <- coef_true
set.seed(999)
coef_init <- coef_true + rnorm(length(coef_true))
coef_rough_init <- rbind(matrix(0, nrow=1, ncol=K_up), coef_init)
res.mle <- fmrs.mle(y = y,
                  x = X,
                  delta = rep(1, n),
                  nComp = K_up,
                  disFamily = "norm",
                  initCoeff = coef_rough_init,
                  # initDispersion = rep(1, K_up),
                  initmixProp = rep(1 / K_up, K_up),
                  # nIterNR = 1000,
                  activeset = as)
coefficients(res.mle)
print("dispersion")
dispersion(res.mle)
print("mixprop")
mixProp(res.mle)
```
```{r}
colnames(X) <- paste0("X", 1:(xdim))
df_tmp <- cbind(data.frame(y=y), X)
model <- flexmix(y~0+., data = df_tmp, k = K_up) # 0 去除常数项
parameters(model)
```

### 迭代-同$\rho$


```{r}
# 同 rho 版本
set.seed(999)
# 完全随机
# coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 4)
coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 0.01)
# 基于正确答案进行干扰
# coef_init <- coef_true + rnorm(length(coef_true), mean = 0, sd = 1) # 在真值附近很容易收敛
coef_est <- coef_init

pi_est <- rep(1/K_up, K_up)
pi_est_list <- list(pi_est)

rho_est_list <- list(c(1,1,1,1))

print(coef_est)
for (iter in 2:100) {
 
  # ********************* 更新后验概率矩阵 *********************
  if (iter == 2) {
    q_c_matrix <- t(t(matrix(1 / (y - (X %*% coef_est))**2, ncol = K_up)) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  } else {
    q_c_matrix <- t(t(dnorm(y, mean = X %*% coef_est, 
                            sd = 1 / mean(rho_est_list[[iter - 1]]))) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
    vanishidx <- which(apply(q_c_matrix, 1, function(x) { sum(x) %>% is.na()}))
    if (!identical(vanishidx, integer(0))) {
      print(paste("******************", vanishidx, "****************"))
      # 若有密度消失样本，归为距离均值最近的类别
      # 应再处理 rho 暂时忽略这步
      q_c_matrix_addin <- t(t(matrix(1 / (y[vanishidx] - (X %*% coef_est)[vanishidx, ])**2, ncol = K_up)) * pi_est_list[[iter - 1]])
      q_c_matrix_addin <- q_c_matrix_addin / apply(q_c_matrix_addin, 1, sum)
      q_c_matrix[vanishidx, ] <- q_c_matrix_addin
    }
  }
  
  # *************************** 更新 pi ******************************
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_est_list[[iter]] <- pi_est
  
  # *************************** 更新参数 ******************************
  coef_old <- coef_est
  for (k in 1:K_up) {
    W <- diag(q_c_matrix[, k])
    coef_k <- solve(t(X) %*% W %*% X) %*% t(X) %*% W %*% y
    coef_est[, k] <- coef_k
  }
  rho_est <- rep(sqrt(n / sum((y - X %*% coef_est)**2 * q_c_matrix)), 4)
  rho_est_list[[iter]] <- rho_est
  
  # *************************** 判断收敛 ******************************
  if (sum((y - X %*% coef_est)**2 * q_c_matrix) < 1e-8) {
    print("converge")
    return()
  }else if(sum((coef_est - coef_old)**2) < 1e-15){
    print('converge with no coef change')
    return()
  }
  # print(iter)
  # print(beta_est)
  # print(rho_est)
  ci_est <- apply(q_c_matrix, 1, which.max)
  # print(right_class_ratio(ci_sim, ci_est))
  print(plot_classdis(20, coef_est, rho_est_list[[iter-1]]))
}
```

### 迭代-不同$\rho$

```{r}
# 不同 rho 版本
set.seed(999)
# 完全随机
# coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 4)
coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 0.01)
# 基于正确答案进行干扰
# coef_init <- coef_true + rnorm(length(coef_true), mean = 0, sd = 1) # 在真值附近很容易收敛
coef_est <- coef_init

pi_est <- rep(1/K_up, K_up)
pi_est_list <- list(pi_est)

rho_est_list <- list(c(1,1,1,1))

print(coef_est)
for (iter in 2:100) {
 
  # ********************* 更新后验概率矩阵 *********************
  if (iter == 2) {
    q_c_matrix <- t(t(matrix(1 / (y - (X %*% coef_est))**2, ncol = K_up)) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  } else {
    q_c_matrix <- t(t(dnorm(y, mean = X %*% coef_est, 
                            sd = 1 / mean(rho_est_list[[iter - 1]]))) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
    vanishidx <- which(apply(q_c_matrix, 1, function(x) { sum(x) %>% is.na()}))
    if (!identical(vanishidx, integer(0))) {
      print(paste("******************", vanishidx, "****************"))
      # 若有密度消失样本，归为距离均值最近的类别
      # 应再处理 rho 暂时忽略这步
      q_c_matrix_addin <- t(t(matrix(1 / (y[vanishidx] - (X %*% coef_est)[vanishidx, ])**2, ncol = K_up)) * pi_est_list[[iter - 1]])
      q_c_matrix_addin <- q_c_matrix_addin / apply(q_c_matrix_addin, 1, sum)
      q_c_matrix[vanishidx, ] <- q_c_matrix_addin
    }
  }
  
  # *************************** 更新 pi ******************************
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_est_list[[iter]] <- pi_est
  
  # *************************** 更新参数 ******************************
  coef_old <- coef_est
  for (k in 1:K_up) {
    W <- diag(q_c_matrix[, k])
    coef_k <- solve(t(X) %*% W %*% X) %*% t(X) %*% W %*% y
    coef_est[, k] <- coef_k
  }
  rho_est <- sqrt(apply(q_c_matrix, 2, sum) / apply((y - X %*% coef_est)**2 * q_c_matrix, 2, sum))
  rho_est_list[[iter]] <- rho_est
  
  # *************************** 判断收敛 ******************************
  if (sum((y - X %*% coef_est)**2 * q_c_matrix) < 1e-8) {
    print("converge")
    return()
  }else if(sum((coef_est - coef_old)**2) < 1e-15){
    print('converge with no coef change')
    return()
  }
  # print(iter)
  # print(beta_est)
  # print(rho_est)
  ci_est <- apply(q_c_matrix, 1, which.max)
  # print(right_class_ratio(ci_sim, ci_est))
  print(plot_classdis(20, coef_est, rho_est_list[[iter-1]]))
}
```


## 依次迭代

### 迭代-同$\rho$

```{r}
# 同 rho 版本
iter_max <- 100
set.seed(999)
# 完全随机
# coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 4)
coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 0.01)
# 基于正确答案进行干扰
coef_init <- coef_true + rnorm(length(coef_true), mean = 0, sd = 1) # 在真值附近很容易收敛
coef_est <- coef_init
beta_est <- coef_est[1:p,]
alpha_est <- coef_est[(p+1):(p+q),]

pi_est <- rep(1/K_up, K_up)
pi_est_list <- list(pi_est)

rho_est_list <- list(c(1,1,1,1))

print(beta_est)
print(alpha_est)
coef_dist <- sum((coef_est - coef_true)**2)
for (iter in 2:iter_max) {
 
  # ********************* 更新后验概率矩阵 *********************
  if (iter == 2) {
    q_c_matrix <- t(t(matrix(1 / (y - (x%*%beta_est+z%*%alpha_est))**2, ncol = K_up)) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  } else {
    q_c_matrix <- t(t(dnorm(y, mean = x%*%beta_est+z%*%alpha_est, 
                            sd = 1 / mean(rho_est_list[[iter - 1]]))) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
    vanishidx <- which(apply(q_c_matrix, 1, function(x) { sum(x) %>% is.na()}))
    if (!identical(vanishidx, integer(0))) {
      print(paste("******************", vanishidx, "****************"))
      # 若有密度消失样本，归为距离均值最近的类别
      # 应再处理 rho 暂时忽略这步
      q_c_matrix_addin <- t(t(matrix(1 / (y[vanishidx] - (x%*%beta_est+z%*%alpha_est)[vanishidx, ])**2, ncol = K_up)) * pi_est_list[[iter - 1]])
      q_c_matrix_addin <- q_c_matrix_addin / apply(q_c_matrix_addin, 1, sum)
      q_c_matrix[vanishidx, ] <- q_c_matrix_addin
    }
  }
  
  # *************************** 更新 pi ******************************
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_est_list[[iter]] <- pi_est
  
  # *************************** 更新参数 ******************************
  beta_old <- beta_est
  alpha_old <- alpha_est
  y_beta <- y - z%*%alpha_est
  y_alpha <- y - x%*%beta_est
  for (k in 1:K_up) {
     W <- diag(q_c_matrix[,k])
    # update \beta_k
    beta_k <- solve(t(x)%*%W%*%x)%*%t(x)%*%W%*%y_beta[,k]
    beta_est[,k] <- beta_k
    # udpate \alpha_k
    alpha_k <- solve(t(z)%*%W%*%z)%*%t(z)%*%W%*%y_alpha[,k]
    alpha_est[,k] <- alpha_k
  }
  coef_est <- rbind(beta_est, alpha_est)
  rho_est <- rep(sqrt(n / sum((y - x%*%beta_est-z%*%alpha_est)**2 * q_c_matrix)), 4)
  rho_est_list[[iter]] <- rho_est
  
  # *************************** 判断收敛 ******************************
  if(sum((y - x%*%beta_est - z%*%alpha_est)**2 * q_c_matrix) < 1e-4){
      print('converge')
      return()
  }else if(sum((beta_est - beta_old)**2) + sum((alpha_est - alpha_old)**2) < 1e-20){
    print('converge with no coef change')
    return()
  }
  print(iter)
  print(coef_est)
  print(rho_est)
  ci_est <- apply(q_c_matrix, 1, which.max)
  coef_dist[iter] <- sum((coef_est - coef_true)**2)
  # print(right_class_ratio(ci_sim, ci_est))
  print(plot_classdis(20, coef_est, rho_est_list[[iter-1]]))
}
plot(1:(iter-1), coef_dist)
```
### 迭代-不同$\rho$


```{r}
iter_max <- 100
set.seed(999)
# 完全随机
# coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 4)
coef_init <- coef_true - coef_true + rnorm(length(coef_true), mean = 0, sd = 0.01)
# 基于正确答案进行干扰
coef_init <- coef_true + rnorm(length(coef_true), mean = 0, sd = 1) # 在真值附近很容易收敛
coef_est <- coef_init
beta_est <- coef_est[1:p,]
alpha_est <- coef_est[(p+1):(p+q),]

pi_est <- rep(1/K_up, K_up)
pi_est_list <- list(pi_est)

rho_est_list <- list(c(1,1,1,1))

print(beta_est)
print(alpha_est)
coef_dist <- sum((coef_est - coef_true)**2)
for (iter in 2:iter_max) {
 
  # ********************* 更新后验概率矩阵 *********************
  if (iter == 2) {
    q_c_matrix <- t(t(matrix(1 / (y - (x%*%beta_est+z%*%alpha_est))**2, ncol = K_up)) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  } else {
    q_c_matrix <- t(t(dnorm(y, mean = x%*%beta_est+z%*%alpha_est, 
                            sd = 1 / mean(rho_est_list[[iter - 1]]))) * pi_est_list[[iter - 1]])
    q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
    vanishidx <- which(apply(q_c_matrix, 1, function(x) { sum(x) %>% is.na()}))
    if (!identical(vanishidx, integer(0))) {
      print(paste("******************", vanishidx, "****************"))
      # 若有密度消失样本，归为距离均值最近的类别
      # 应再处理 rho 暂时忽略这步
      q_c_matrix_addin <- t(t(matrix(1 / (y[vanishidx] - (x%*%beta_est+z%*%alpha_est)[vanishidx, ])**2, ncol = K_up)) * pi_est_list[[iter - 1]])
      q_c_matrix_addin <- q_c_matrix_addin / apply(q_c_matrix_addin, 1, sum)
      q_c_matrix[vanishidx, ] <- q_c_matrix_addin
    }
  }
  
  # *************************** 更新 pi ******************************
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_est_list[[iter]] <- pi_est
  
  # *************************** 更新参数 ******************************
  beta_old <- beta_est
  alpha_old <- alpha_est
  y_beta <- y - z%*%alpha_est
  y_alpha <- y - x%*%beta_est
  for (k in 1:K_up) {
     W <- diag(q_c_matrix[,k])
    # update \beta_k
    beta_k <- solve(t(x)%*%W%*%x)%*%t(x)%*%W%*%y_beta[,k]
    beta_est[,k] <- beta_k
    # udpate \alpha_k
    alpha_k <- solve(t(z)%*%W%*%z)%*%t(z)%*%W%*%y_alpha[,k]
    alpha_est[,k] <- alpha_k
  }
  coef_est <- rbind(beta_est, alpha_est)
  rho_est <- sqrt(apply(q_c_matrix, 2, sum) / apply((y - x%*%beta_est - z%*%alpha_est)**2 * q_c_matrix, 2, sum))
  rho_est_list[[iter]] <- rho_est
  
  # *************************** 判断收敛 ******************************
  if(sum((y - x%*%beta_est - z%*%alpha_est)**2 * q_c_matrix) < 1e-4){
      print('converge')
      return()
  }else if(sum((beta_est - beta_old)**2) + sum((alpha_est - alpha_old)**2) < 1e-20){
    print('converge with no coef change')
    return()
  }
  print(iter)
  print(rbind(beta_est, alpha_est))
  print(rho_est)
  ci_est <- apply(q_c_matrix, 1, which.max)
  coef_dist[iter] <- sum((coef_est - coef_true)**2)
  # print(right_class_ratio(ci_sim, ci_est))
  print(plot_classdis(20, coef_est, rho_est_list[[iter-1]]))
}
```












