---
title: "beta alpha"
author: "任焱"
date: "2022-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls(all = TRUE))
library(ggplot2)
library(dplyr)
library(flexmix)
library(ADMM)
source("sim.R")
source("tools.R")
```

```{r}
# 超参数设定
n <- 400
p <- 20
q <- 20
cotype_x <- "En"
cotype_z <- "En"
epsilon_sd <- 0.0
beta_nonzero <- c(-2, -2, 2, 2) # 长度应和真实 group_num_sub 保持一致
beta_nonzero <- c(-3, -1, 1, 3) # 长度应和真实 group_num_sub 保持一致
# alpha_nonzero <- c(-3, -1, 1, 3)
alpha_nonzero <- c(-3, -1, 1, 3) # 验证最简单情况不需要 alpha
# alpha_nonzero <- c(0, 0, 0, 0) # 验证最简单情况不需要 alpha
beta_vlen <- 3
alpha_vlen <- 2

K_up <- 4  # 估计时的最大类别，应该不少于 group_num_sub
group_num_main <- 2                    
group_num_sub <- 4    
hier_struc <- list(c(1,2),c(3,4))
prob_sub <- rep(1/group_num_sub, group_num_sub)  
reverse = FALSE

aa <- 1.2
lambda_1 <- 0.2
```

```{r}
set.seed(7)
whole.data <- generate_all_data(n, p, q, prob_sub, hier_struc, 
                  beta_nonzero, alpha_nonzero, beta_vlen, alpha_vlen, 
                  cotype_x, cotype_z, epsilon_sd, reverse)
X <- whole.data$data$X
Z <- whole.data$data$Z
data <- whole.data$data$data_full
coef <- whole.data$coef
ci_sim <- whole.data$ci_sim
y <- whole.data$y
```

## 1. 观察条件取值

```{r}
get_coef_onedim <- function(upper, lower, aa, lambda_1, n){
  res <- mcp_solution(lower/n, upper/lower, aa, lambda_1)
  return(res)
}
```

```{r}
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
j <- 1 # 1:p 取值均可
k <- 1 # 1:K_up 均可
coef_full <- coef$coef_full
coef_beta <- coef_full[1:p,]
coef_alpha <- coef_full[(p+1):(p+q),]

rho_est <- c(1, 1, 1, 1)
rho_k <- rho_est[k]
W_k <- diag(q_c_matrix[,k])

# update beta
for(j in 1:p){
  upper <- t(rho_k*y - X[,-j]%*%(coef_beta[-j,k]) - Z%*%coef_alpha[,k]) %*% W_k %*% X[,j]
  lower <- t(X[,j]) %*% W_k %*% X[,j]
  coef_beta_kj <- get_coef_onedim(upper, lower, aa, lambda_1, n)
  coef_beta[j,k] <- coef_beta_kj
  print(as.numeric(coef_beta_kj))
}
# update alpha
for(s in 1:q){
  upper <- t(rho_k*y - Z[,-s]%*%(coef_alpha[-s,k]) - X%*%coef_beta[,k]) %*% W_k %*% Z[,s]
  lower <- t(Z[,s]) %*% W_k %*% Z[,s]
  coef_alpha_ks <- get_coef_onedim(upper, lower, aa, lambda_1, n)
  coef_alpha[s,k] <- coef_alpha_ks
  print(as.numeric(coef_alpha_ks))
}
```

## 2. 迭代求解整个向量

```{r}
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
rho_est <- c(1, 1, 1, 1)/0.5
rho_k <- rho_est[k]
coef_full_est <- coef$coef_full - coef$coef_full
coef_beta_est <- coef_full_est[1:p,]
coef_alpha_est <- coef_full_est[(p+1):(p+q),]

aa <- 1.2
lambda_1 <- 0.1

for(k in 1:K_up){
  rho_k <- rho_est[k]
  W_k <- diag(q_c_matrix[,k])
  for(tt in 1:10){
    for(j in 1:p){
      upper <- t(rho_k*y - X[,-j]%*%(coef_beta_est[-j,k]) -
                   Z%*%coef_alpha_est[,k]) %*% W_k %*% X[,j]
      lower <- t(X[,j]) %*% W_k %*% X[,j]
      coef_beta_kj <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    for(s in 1:q){
      upper <- t(rho_k*y - Z[,-s]%*%(coef_alpha_est[-s,k]) -
                   X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      lower <- t(Z[,s]) %*% W_k %*% Z[,s]
      coef_alpha_ks <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
    # print(rbind(coef_beta_est[,], coef_alpha_est[,])/rho_k)
  }
}
rbind(coef_beta_est[,], coef_alpha_est[,])/rho_k
```

## 3. q_c 的估计也纳入其中

### 真 q_c 更新 rho_k

```{r}
extend_x_to_row <- function(x, row_to){
  K_up <- length(x)
  return(matrix(kronecker(rho_est, matrix(1, nrow=row_to)), ncol = K_up))
}
```


```{r}
coef_list <- NULL
rho_est <- c(1, 1, 1, 1)/0.5
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
coef_full_est <- coef$coef_full - coef$coef_full
coef_beta_est <- coef_full_est[1:p,]
coef_alpha_est <- coef_full_est[(p+1):(p+q),]

aa <- 1.2
lambda_1 <- 0.1

for(tt in 1:50){
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    rho_k <- rho_est[k]
    # beta
    for(j in 1:p){
      upper <- t(rho_k*y - X[,-j]%*%(coef_beta_est[-j,k]) -
                   Z%*%coef_alpha_est[,k]) %*% W_k %*% X[,j]
      lower <- t(X[,j]) %*% W_k %*% X[,j]
      coef_beta_kj <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    # alpha
    for(s in 1:q){
      upper <- t(rho_k*y - Z[,-s]%*%(coef_alpha_est[-s,k]) -
                   X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      lower <- t(Z[,s]) %*% W_k %*% Z[,s]
      coef_alpha_ks <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
    coef_full_est[,k] <- c(coef_beta_est[,k], coef_alpha_est[,k])
    # 更新 rho_k
    A <- -y%*%W_k%*%y
    B <- t(data%*%coef_full_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  coef_list[[tt]] <- coef_full_est/extend_x_to_row(rho_est, p+q)
}
coef_list[[tt]]
plot(unlist(lapply(coef_list, coef_dist, coef$coef_full)))
```


### 全更新

```{r}
# 初始化
aa <- 1.2
lambda_1 <- 0.15
rho_init <- c(1, 1, 1, 1)/0.5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
set.seed(999)
# 真值附近
# q_c_matrix <- abs(get_q_c_matrix(n, K_up, ci_sim) + rnorm(n*K_up, mean = 1, sd = .1))
# 全随机
q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) +
                  rnorm(n*K_up, mean = 0, sd = .1))
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

# coef full
coef_full_init <- coef$coef_full - coef$coef_full
coef_full_list <- list(coef_full_init)
coef_full_ori_list <- list(coef_full_init/t(kronecker(rho_init, 
                                                      matrix(1, ncol = p+q))))
for(iter in 2:200){
  rho_est <- rho_list[[iter-1]]
  coef_full_est <- coef_full_list[[iter-1]]
  coef_beta_est <- coef_full_est[1:p,]
  coef_alpha_est <- coef_full_est[(p+1):(p+q),]
  
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    rho_k <- rho_est[k]
    # beta
    for(j in 1:p){
      upper <- t(rho_k*y - X[,-j]%*%(coef_beta_est[-j,k]) -
                   Z%*%coef_alpha_est[,k]) %*% W_k %*% X[,j]
      lower <- t(X[,j]) %*% W_k %*% X[,j]
      coef_beta_kj <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    # alpha
    for(s in 1:q){
      upper <- t(rho_k*y - Z[,-s]%*%(coef_alpha_est[-s,k]) -
                   X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      lower <- t(Z[,s]) %*% W_k %*% Z[,s]
      coef_alpha_ks <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
    coef_full_est[,k] <- c(coef_beta_est[,k], coef_alpha_est[,k])
    # 更新 rho_k
    A <- -y%*%W_k%*%y
    B <- t(data%*%coef_full_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  rho_list[[iter]] <- rho_est
  coef_full_list[[iter]] <- coef_full_est
  coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est, p+q)
  
  # update q_c matrix
  q_c_matrix <- dnorm(y, 
                      mean = data%*%coef_full_ori_list[[iter]], 
                      sd = 1/extend_x_to_row(rho_est, n)) *
    extend_x_to_row(pi_list[[iter-1]], n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  coef_diff_std <- (sum(coef_full_list[[iter]]-coef_full_list[[iter-1]])**2)/
     (sum(coef_full_list[[iter]])**2 + 1e-4)
  if(coef_diff_std < 1e-7){
    return()
  }
}
coef_full_list[[iter]]
coef_full_ori_list[[iter]]
plot(unlist(lapply(coef_full_ori_list, coef_dist, coef$coef_full)), ylab = "")
coef_dist(coef_full_ori_list[[iter]], coef$coef_full)
```


## 4. 包结果

```{r}
pi_init <- rep(1/K_up, K_up)
set.seed(999) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
m_glm <- flexmix(y~cbind(X, Z)-1, k = 4, cluster = q_c_matrix,
                 model = FLXMRglm(),
             control = list())
coef_init <- parameters(m_glm)[1:(p+q),]
colnames(coef_init) <- NULL
rownames(coef_init) <- NULL
coef_init
coef_dist(coef$coef_beta, parameters(m_glm)[1:p,])
```

## 5. 借助包结果初始化

```{r}
# 初始化
aa <- 1.2
lambda_1 <- 0.2
rho_init <- c(1, 1, 1, 1)/0.5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)

# coef full
coef_full_init <- coef_init * t(kronecker(rho_init, matrix(1, ncol = p+q)))
coef_full_list <- list(coef_full_init)
coef_full_ori_list <- list(coef_init)

set.seed(999) # just in case
q_c_matrix <- dnorm(y, 
                    mean = data %*% coef_full_ori_list[[1]], 
                    sd = 1/extend_x_to_row(rho_init, n)) *
  extend_x_to_row(pi_init, n)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

for(iter in 2:100){
  coef_full_est <- coef_full_list[[iter-1]]
  coef_beta_est <- coef_full_est[1:p,]
  coef_alpha_est <- coef_full_est[(p+1):(p+q),]
  rho_est <- rho_list[[iter-1]]
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    rho_k <- rho_est[k]
    # beta
    for(j in 1:p){
      upper <- t(rho_k*y - X[,-j]%*%(coef_beta_est[-j,k]) -
                   Z%*%coef_alpha_est[,k]) %*% W_k %*% X[,j]
      lower <- t(X[,j]) %*% W_k %*% X[,j]
      coef_beta_kj <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    # alpha
    for(s in 1:q){
      upper <- t(rho_k*y - Z[,-s]%*%(coef_alpha_est[-s,k]) -
                   X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      lower <- t(Z[,s]) %*% W_k %*% Z[,s]
      coef_alpha_ks <- get_coef_onedim(upper, lower, aa, lambda_1, n)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
    coef_full_est[,k] <- c(coef_beta_est[,k], coef_alpha_est[,k])
    # 更新 rho_k
    A <- -y%*%W_k%*%y
    B <- t(data%*%coef_full_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  rho_list[[iter]] <- rho_est
  coef_full_list[[iter]] <- coef_full_est
  coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est, p+q)
  
  q_c_matrix <- dnorm(y, 
                      mean = data %*% coef_full_ori_list[[iter]], 
                      sd = 1/extend_x_to_row(rho_est, n)) *
    extend_x_to_row(pi_list[[iter-1]], n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  coef_diff_std <- (sum(coef_full_list[[iter]]-coef_full_list[[iter-1]])**2)/
     (sum(coef_full_list[[iter]])**2 + 1e-4)
  if(coef_diff_std < 1e-5){
    return()
  }
}
coef_full_list[[iter]]
coef_full_ori_list[[iter]]
plot(unlist(lapply(coef_full_ori_list, coef_dist, coef$coef_full)), ylab = "")
coef_dist(coef_full_ori_list[[iter]], coef$coef_full)
```

```{r}

```













