---
title: "flexmix"
author: "任焱"
date: "2022-10-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls(all = TRUE))
library(ggplot2)
library(dplyr)
library(flexmix)
library(ADMM)
source("sim.R")
source("tools.R")
# library(glmnet)
```

```{r}
# 超参数设定
n <- 400
# p <- 40
q <- 10
cotype_x <- "En"
cotype_z <- "En"
epsilon_sd <- 0.5
beta_nonzero <- c(-2, -2, 2, 2) # 长度应和真实 group_num_sub 保持一致
beta_nonzero <- c(-3, -1, 1, 3) # 长度应和真实 group_num_sub 保持一致
# alpha_nonzero <- c(-3, -1, 1, 3)
alpha_nonzero <- c(0, 0, 0, 0) # 验证最简单情况不需要 alpha
# beta_vlen <- 5
alpha_vlen <- 2

K_up <- 4  # 估计时的最大类别，应该不少于 group_num_sub
group_num_main <- 2                    
group_num_sub <- 4    
hier_struc <- list(c(1,2),c(3,4))
prob_sub <- rep(1/group_num_sub, group_num_sub)  

aa <- 2
lambda_1 <- 0.8
```

# 概览

每种 p 和是否进行变量选择的设定都有三组实验

1. flexmix 包结果
2. 估计 q_c 但是用 admm.lasso 进行参数估计
3. 参数也自己估计

# p->3/8 不选择

不选择相当于不惩罚

```{r}
p <- 40
beta_vlen <- 3

set.seed(7)
whole.data <- generate_all_data(n, p, q, prob_sub, hier_struc, 
                  beta_nonzero, alpha_nonzero, beta_vlen, alpha_vlen, 
                  cotype_x, cotype_z, epsilon_sd)
X <- whole.data$data$X
Z <- whole.data$data$Z
data <- whole.data$data$data_full
coef <- whole.data$coef
ci_sim <- whole.data$ci_sim
y <- whole.data$y
```

## flexmix

```{r}
# FLXMRglm() 为默认模型
pi_init <- rep(1/K_up, K_up)
set.seed(999) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
m_glm <- flexmix(y~X-1, k = 4, cluster = q_c_matrix,
                 model = FLXMRglm(),
             control = list())
parameters(m_glm)
coef_dist(coef$coef_beta, parameters(m_glm)[1:p,])
```

## 估计 q_c

```{r}
coef_beta_init <- coef$coef_beta - coef$coef_beta
coef_beta_list <- list(coef_beta_init)
rho_init <- c(1,1,1,1)/5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
coef_beta_ori_list <- list(coef_beta_init/t(kronecker(rho_init, matrix(1, ncol = p))))

set.seed(999) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

res_list <- list(1)
for(iter in 2:50){
  coef_beta_est <- coef_beta_list[[iter-1]]
  rho_est <- rho_list[[iter-1]]
  pi_est <- pi_list[[iter-1]]
  
  # 参数更新
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    # output <- admm.lasso(W_k%*%X, W_k_prime%*%y, lambda = 1)
    # coef_beta_est[,k] <- output$x
    coef_beta_est[,k] <- coef(lm(W_k_prime%*%y~W_k%*%X-1)) # 与下等价
    # coef_beta_est[,k] <- solve(t(W_k%*%X)%*%(W_k%*%X))%*%t(W_k%*%X)%*%(W_k_prime%*%y)
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 0.05)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 1)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  
  # print(sum((q_c_matrix - get_q_c_matrix(n, K_up, ci_sim))**2))
  q_c_matrix <- dnorm(y, mean = X %*% (coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))), 
                            sd = 1 / matrix(rep(rho_list[[iter-1]], each = n), nrow=n)) *
    rep(pi_list[[iter-1]], each = n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  ci_est <- apply(q_c_matrix, 1, which.max)
  
  # print(rho_est)
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta_ori_list[[iter]] <- coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- mse_2(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
  
  # 迭代终止条件
  if(sum((coef_beta_list[[iter]] - coef_beta_list[[iter-1]])**2)/sum((coef_beta_list[[iter-1]])**2) < 1e-4){
    return()
  }
}
coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
coef_dist(coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))), coef$coef_beta)
# unlist(rho_list)
# plot(unlist(lapply(coef_beta_ori_list, coef_dist, coef$coef_beta)), ylab = "")
# plot(unlist(res_list))
```


# p->3/8 选择

## flexmix

```{r}
set.seed(999) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

m_select <- flexmix(y~X, k = 4, 
                    cluster = q_c_matrix,
             model = FLXMRglmnet(intercept = FALSE, adaptive = FALSE), 
             control = list(minprior = 0.0))
coef_est <- parameters(m_select)
coef_est <- coef_est[2:(nrow(coef_est)-1),]
coef_est
coef_dist(coef_est, coef$coef_beta)
```

## 估计 q_c 调包 Lasso


```{r}
coef_beta_init <- coef$coef_beta - coef$coef_beta
coef_beta_list <- list(coef_beta_init)
rho_init <- c(1,1,1,1)/5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
coef_beta_ori_list <- list(coef_beta_init/t(kronecker(rho_init, matrix(1, ncol = p))))

set.seed(999) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

res_list <- list(1)
for(iter in 2:50){
  coef_beta_est <- coef_beta_list[[iter-1]]
  rho_est <- rho_list[[iter-1]]
  pi_est <- pi_list[[iter-1]]
  
  # 参数更新
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    # output <- admm.lasso(W_k%*%X, W_k_prime%*%y, lambda = 2, alpha = 1.95)
    # coef_beta_est[,k] <- output$x
    ls <- admm_lasso(W_k%*%X, W_k_prime%*%y, intercept = FALSE)
    output <- ls$penalty(0.02)$fit()
    coef_beta_est[,k] <- output$beta[2:(p+1)]
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 1)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  
  # print(sum((q_c_matrix - get_q_c_matrix(n, K_up, ci_sim))**2))
  q_c_matrix <- dnorm(y, mean = X %*% (coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))), 
                            sd = 1 / matrix(rep(rho_list[[iter-1]], each = n), nrow=n)) *
    rep(pi_list[[iter-1]], each = n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  ci_est <- apply(q_c_matrix, 1, which.max)
  
  # print(rho_est)
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta_ori_list[[iter]] <- coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- mse_2(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
  
  # 迭代终止条件
  if(sum((coef_beta_list[[iter]] - coef_beta_list[[iter-1]])**2)/sum((coef_beta_list[[iter-1]])**2) < 1e-4){
    return()
  }
}
coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
coef_dist(coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))), coef$coef_beta)
# unlist(rho_list)
plot(unlist(lapply(coef_beta_ori_list, coef_dist, coef$coef_beta)), ylab = "")
plot(unlist(res_list))
```

## 估计 q_c & 参数

```{r}
lambda_1 <- 0.1

coef_beta_init <- coef$coef_beta - coef$coef_beta
coef_beta_list <- list(coef_beta_init)
coef_beta2_init <- coef$coef_beta - coef$coef_beta
coef_beta2_list <- list(coef_beta2_init)
tau_init <- coef$coef_beta - coef$coef_beta
tau_list <- list(tau_init)
lgv_para <- c(1, 1, 1, 1)/10

rho_init <- c(1,1,1,1)/5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
coef_beta_ori_list <- list(coef_beta_init/t(kronecker(rho_init, matrix(1, ncol = p))))

# set.seed(999) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

res_list <- list(1)
for(iter in 2:50){
  coef_beta_est <- coef_beta_list[[iter-1]]
  rho_est <- rho_list[[iter-1]]
  pi_est <- pi_list[[iter-1]]
  
  coef_beta2_est <- coef_beta2_list[[iter-1]]
  tau_est <- tau_list[[iter-1]]
  
  # 参数更新
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    for(i in 1:5){
      # beta
      coef_beta_k_est <- solve(1/n*t(X)%*%W_k%*%X + lgv_para[k]*diag(1,p)) %*%
        (1/n*t(X)%*%W_k_prime%*%y + lgv_para[k]*coef_beta2_est[,k] - tau_est[,k])
      coef_beta_est[,k] <- coef_beta_k_est
      # theta
      z_k <- coef_beta_k_est + tau_est[,k]/lgv_para[k]
      coef_beta2_k_est <- rep(0, p)
      for(j in 1:p){
        coef_beta2_k_est[j] <- mcp_solution(theta = lgv_para[k], 
                                       a = z_k[j], gamma = aa, 
                                       lambda = lambda_1)
      }
      coef_beta2_est[,k] <- coef_beta2_k_est
      # tau
      tau_est[,k] <- tau_est[,k] + lgv_para[k]*(coef_beta_k_est - coef_beta2_k_est)
    
    }
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 1)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta2_list[[iter]] <- coef_beta2_est
  tau_list[[iter]] <- tau_est
  
  # print(sum((q_c_matrix - get_q_c_matrix(n, K_up, ci_sim))**2))
  q_c_matrix <- dnorm(y, mean = X %*% (coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))), 
                            sd = 1 / matrix(rep(rho_list[[iter-1]], each = n), nrow=n)) *
    rep(pi_list[[iter-1]], each = n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  ci_est <- apply(q_c_matrix, 1, which.max)
  
  # print(rho_est)
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta_ori_list[[iter]] <- coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- mse_2(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
  
  # 迭代终止条件
  if(sum((coef_beta_list[[iter]] - coef_beta_list[[iter-1]])**2)/sum((coef_beta_list[[iter-1]])**2) < 1e-4){
    return()
  }
}
coef_beta2_est/t(kronecker(rho_est, matrix(1, ncol = p)))
coef_dist(coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))), coef$coef_beta)
# unlist(rho_list)
plot(unlist(lapply(coef_beta_ori_list, coef_dist, coef$coef_beta)), ylab = "")
plot(unlist(res_list))
```


```{r}

```














