---
title: "Untitled"
author: "任焱"
date: "2022-10-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls(all = TRUE))
library(ggplot2)
library(dplyr)
library(flexmix)
library(ADMM)
source("sim.R")
source("tools.R")
```

对比文章发现重参数化过程错误，可能导致 $\rho_k$ 的更新失败，以下为本文档两大内容

1. flemix 包的使用
2. 自己更新流程的重参数化

# Data

```{r}
# 超参数设定
n <- 400
p <- 40
q <- 10
cotype_x <- "En"
cotype_z <- "En"
epsilon_sd <- 0.5
beta_nonzero <- c(-2, -2, 2, 2) # 长度应和真实 group_num_sub 保持一致
beta_nonzero <- c(-3, -1, 1, 3) # 长度应和真实 group_num_sub 保持一致
# alpha_nonzero <- c(-3, -1, 1, 3)
alpha_nonzero <- c(0, 0, 0, 0) # 验证最简单情况不需要 alpha
beta_vlen <- 5
alpha_vlen <- 2

K_up <- 4  # 估计时的最大类别，应该不少于 group_num_sub
group_num_main <- 2                    
group_num_sub <- 4    
hier_struc <- list(c(1,2),c(3,4))
prob_sub <- rep(1/group_num_sub, group_num_sub)  

aa <- 2
lambda_1 <- 0.8
```

```{r}
set.seed(7)
whole.data <- generate_all_data(n, p, q, prob_sub, hier_struc, 
                  beta_nonzero, alpha_nonzero, beta_vlen, alpha_vlen, 
                  cotype_x, cotype_z, epsilon_sd)
X <- whole.data$data$X
Z <- whole.data$data$Z
data <- whole.data$data$data_full
coef <- whole.data$coef
ci_sim <- whole.data$ci_sim
y <- whole.data$y
```

# Flexmix

包得到的结果也没有很准确

```{r}
# m <- flexmix(formula = y~X+Z, k = 4)
m <- flexmix(formula = y~X, k = 4)
summary(m)
# cbind(matrix(parameters(m, component = 1)),
#       matrix(parameters(m, component = 2)))
cbind(matrix(parameters(m, component = 1)),
      matrix(parameters(m, component = 2)),
      matrix(parameters(m, component = 3)),
      matrix(parameters(m, component = 4)))[2:(length(parameters(m, component = 1))-1),]
# 包会直接进行类别压缩
# cbind(matrix(parameters(m, component = 3)),
#       matrix(parameters(m, component = 4)))
```

```{r}
set.seed(99) # 9,
q_c_matrix <- t(kronecker(rep(1/K_up, K_up), matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
# 随机给定初始化所属分类
m <- flexmix(formula = y~X, k = 4, cluster = q_c_matrix, model = FLXMRglmnet(intercept = FALSE, adaptive = FALSE))
summary(m)
cbind(matrix(parameters(m, component = 1)),
      matrix(parameters(m, component = 2)),
      matrix(parameters(m, component = 3)),
      matrix(parameters(m, component = 4)))[1:(length(parameters(m, component = 1))-1),]
```



```{r}
# coef_beta_init <- cbind(matrix(parameters(m, component = 1)),
#       matrix(parameters(m, component = 2)))[2:(length(parameters(m, component = 1))-1),]
# coef_beta_init <- cbind(coef_beta_init, coef_beta_init)
# coef_beta_init
```


# Lasso Package

## true q_c

### 确定类别框架

- 不更新 rho，正常收敛，不会出现某一轮次参数估计突然很离谱的情况

```{r}
# 残差平方和，越小越好
get_sumsquare_residual <- function(q_c_matrix, y, X, coef_beta_est){
  n <- nrow(q_c_matrix)
  K_up <- ncol(q_c_matrix)
  res <- NULL
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    res[k] <- t(y-X%*%coef_beta_est[,k])%*%W_k%*%(y-X%*%coef_beta_est[,k])
  }
  return(sum(res)/n)
}
```


```{r}
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
coef_beta_est <- coef$coef_beta - coef$coef_beta # 实际没有初值
rho_est <- c(1,1,1,1)/1
rho_list <- list(rho_est)
coef_beta_list <- list(coef_beta_est)
res_list <- list(1)

for(iter in 2:10){
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    output <- admm.lasso(W_k%*%X, W_k_prime%*%y, lambda = 1)
    coef_beta_est[,k] <- output$x
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- get_sumsquare_residual(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
}

coef_beta_est / t(kronecker(rho_est, matrix(1, ncol = p)))
unlist(rho_list)
# plot(unlist(lapply(coef_beta_list, function(x){sum((x-coef$coef_beta)**2)})), ylab = "")
# plot(unlist(lapply(rho_list, function(x){sum(x**2)})))
plot(unlist(res_list))
```


### 原本框架


```{r}
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)

set.seed(999)
coef_beta_init <- coef$coef_beta - coef$coef_beta
coef_beta_list <- list(coef_beta_init)
rho_init <- c(1,1,1,1)/5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
coef_beta_ori_list <- list(coef_beta_init)

res_list <- list(1)
for(iter in 2:5){
  coef_beta_est <- coef_beta_list[[iter-1]]
  rho_est <- rho_list[[iter-1]]
  pi_est <- pi_list[[iter-1]]
  
  # 参数更新
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    output <- admm.lasso(W_k%*%X, W_k_prime%*%y, lambda = 1)
    coef_beta_est[,k] <- output$x
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 0.05)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 1)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  # print(rho_est)
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta_ori_list[[iter]] <- coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- get_sumsquare_residual(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
}
coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
unlist(rho_list)
plot(unlist(lapply(coef_beta_ori_list, function(x){sum((x-coef$coef_beta)**2)})), ylab = "")
```

### q_c 扰动

```{r}

coef_beta_init <- coef$coef_beta - coef$coef_beta
coef_beta_list <- list(coef_beta_init)
rho_init <- c(1,1,1,1)/5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
coef_beta_ori_list <- list(coef_beta_init)

set.seed(100)
q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim) + rnorm(n*K_up, mean = 500, sd = 5)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

ci_est <- apply(q_c_matrix, 1, which.max)
ci_est2 <- ifelse(ci_est %in% c(1, 2), 1, 3)
ci_sim2 <- ifelse(ci_sim %in% c(1, 2), 1, 3)
sum(ci_sim2 == ci_est2)

res_list <- list(1)
for(iter in 2:25){
  coef_beta_est <- coef_beta_list[[iter-1]]
  rho_est <- rho_list[[iter-1]]
  pi_est <- pi_list[[iter-1]]
  
  # 参数更新
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    output <- admm.lasso(W_k%*%X, W_k_prime%*%y, lambda = 1)
    coef_beta_est[,k] <- output$x
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 0.05)
    rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 1)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  # print(sum((q_c_matrix - get_q_c_matrix(n, K_up, ci_sim))**2))
  q_c_matrix <- dnorm(y, mean = X %*% (coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))), 
                            sd = 1 / matrix(rep(rho_list[[iter-1]], each = n), nrow=n)) *
    rep(pi_list[[iter-1]], each = n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  # print(rho_est)
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta_ori_list[[iter]] <- coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- get_sumsquare_residual(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
  
  # 迭代终止条件
  if(sum((coef_beta_est[[iter]] - coef_beta_est[[iter-1]])**2)/sum((coef_beta_est[[iter-1]])**2) < 1e-2){
    return()
  }
}
coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
unlist(rho_list)
plot(unlist(lapply(coef_beta_ori_list, function(x){sum((x-coef$coef_beta)**2)})), ylab = "")
plot(unlist(res_list))
```


## estimate q_c

更改 EM 算法更新顺序

```{r}
coef_beta_init <- coef$coef_beta - coef$coef_beta
coef_beta_list <- list(coef_beta_init)
rho_init <- c(1,1,1,1)/5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
coef_beta_ori_list <- list(coef_beta_init)

set.seed(999) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

ci_est <- apply(q_c_matrix, 1, which.max)
ci_est2 <- ifelse(ci_est %in% c(1, 2), 1, 3)
ci_sim2 <- ifelse(ci_sim %in% c(1, 2), 1, 3)
sum(ci_sim == ci_est)
sum(ci_sim2 == ci_est2)

res_list <- list(1)
for(iter in 2:50){
  coef_beta_est <- coef_beta_list[[iter-1]]
  rho_est <- rho_list[[iter-1]]
  pi_est <- pi_list[[iter-1]]
  
  # 参数更新
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    output <- admm.lasso(W_k%*%X, W_k_prime%*%y, lambda = 1)
    coef_beta_est[,k] <- output$x
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 0.05)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 1)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  
  # print(sum((q_c_matrix - get_q_c_matrix(n, K_up, ci_sim))**2))
  q_c_matrix <- dnorm(y, mean = X %*% (coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))), 
                            sd = 1 / matrix(rep(rho_list[[iter-1]], each = n), nrow=n)) *
    rep(pi_list[[iter-1]], each = n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  ci_est <- apply(q_c_matrix, 1, which.max)
  
  # print(rho_est)
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta_ori_list[[iter]] <- coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- get_sumsquare_residual(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
  
  # 迭代终止条件
  if(sum((coef_beta_est[[iter]] - coef_beta_est[[iter-1]])**2)/sum((coef_beta_est[[iter-1]])**2) < 1e-3){
    return()
  }
}
coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
unlist(rho_list)
plot(unlist(lapply(coef_beta_ori_list, function(x){sum((x-coef$coef_beta)**2)})), ylab = "")
plot(unlist(res_list))
```


## estimate all

```{r}
lambda_1 <- 1e-5

coef_beta_init <- coef$coef_beta - coef$coef_beta
coef_beta_list <- list(coef_beta_init)
coef_beta2_init <- coef$coef_beta - coef$coef_beta
coef_beta2_list <- list(coef_beta2_init)
tau_init <- coef$coef_beta - coef$coef_beta
tau_list <- list(tau_init)
lgv_para <- c(1, 1, 1, 1)/10

rho_init <- c(1,1,1,1)/0.5
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
coef_beta_ori_list <- list(coef_beta_init)

set.seed(9) # 9,
q_c_matrix <- t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = .5, sd = .1)
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

ci_est <- apply(q_c_matrix, 1, which.max)
ci_est2 <- ifelse(ci_est %in% c(1, 2), 1, 3)
ci_sim2 <- ifelse(ci_sim %in% c(1, 2), 1, 3)
sum(ci_sim == ci_est)
sum(ci_sim2 == ci_est2)

res_list <- list(1)
for(iter in 2:20){
  coef_beta_est <- coef_beta_list[[iter-1]]
  rho_est <- rho_list[[iter-1]]
  pi_est <- pi_list[[iter-1]]
  coef_beta2_est <- coef_beta2_list[[iter-1]]
  tau_est <- tau_list[[iter-1]]
  
  # 参数更新
  for(k in 1:K_up){
    W_k_prime <- diag(q_c_matrix[,k]) * rho_est[k]
    W_k <- diag(q_c_matrix[,k])
    # output <- admm.lasso(W_k%*%X, W_k_prime%*%y, lambda = 1)
    # coef_beta_est[,k] <- output$x
    # beta
    coef_beta_k_est <- solve(1/n*t(X)%*%W_k%*%X + lgv_para[k]*diag(1,p)) %*%
      (1/n*t(X)%*%W_k_prime%*%y + lgv_para[k]*coef_beta2_est[,k] - tau_est[,k])
    coef_beta_est[,k] <- coef_beta_k_est
    # theta
    z_k <- coef_beta_k_est + tau_est[,k]/lgv_para[k]
    coef_beta2_k_est <- mcp_solution(theta = lgv_para[k], 
                                     a = z_k, gamma = aa, lambda = lambda_1)
    coef_beta2_est[,k] <- coef_beta2_k_est
    # tau
    tau_est[,k] <- tau_est[,k] + lgv_para[k]*(coef_beta_k_est - coef_beta2_k_est)
    
    
    A <- -y%*%W_k%*%y
    B <- t(X%*%coef_beta_est[,k]) %*% W_k %*% y
    C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 0.05)
    # rho_est[k] <- max((-B - sqrt(B**2-4*A*C)) / (A*2), 1)
    rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta2_list[[iter]] <- coef_beta2_est
  tau_list[[iter]] <- tau_est
  
  # print(sum((q_c_matrix - get_q_c_matrix(n, K_up, ci_sim))**2))
  q_c_matrix <- dnorm(y, mean = X %*% (coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))), 
                            sd = 1 / matrix(rep(rho_list[[iter-1]], each = n), nrow=n)) *
    rep(pi_list[[iter-1]], each = n) + 1e-4
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  ci_est <- apply(q_c_matrix, 1, which.max)
  
  # print(rho_est)
  # udpate
  coef_beta_list[[iter]] <- coef_beta_est
  coef_beta_ori_list[[iter]] <- coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
  rho_list[[iter]] <- rho_est
  res_list[[iter]] <- get_sumsquare_residual(q_c_matrix, y, X, 
                                             coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p))))
  
  # 迭代终止条件
  if(sum((coef_beta_est[[iter]] - coef_beta_est[[iter-1]])**2)/sum((coef_beta_est[[iter-1]])**2) < 1e-4){
    return()
  }
}
coef_beta_est/t(kronecker(rho_est, matrix(1, ncol = p)))
unlist(rho_list)
plot(unlist(lapply(coef_beta_ori_list, function(x){sum((x-coef$coef_beta)**2)})), ylab = "")
plot(unlist(res_list))
```


```{r}

```






