---
title: "修改后纯验证"
author: "Yan Ren"
date: "2023-08-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

> 进行单轮实验，分析封装函数的具体表现

```{r}
library(ggplot2)
library(dplyr)
library(Matrix)
library(flexmix)
library(readr)
source("sim.R")
source("tools.R")
source("func.R")
```

```{r}
n <- 500
p <- 80
q <- 4
epsilon_sd <- 0.5
sigma_est <- as.numeric(epsilon_sd)
signal_size <- 1
beta_vlen <- 3
alpha_vlen <- 2
save_path <- "temp.csv"
dt_seed <- 49
K_up <- 6  # 估计时的最大类别，应该不少于 group_num_sub

cotype_x <- "En"
cotype_z <- "En"
# epsilon_sd <- 0.5
beta_nonzero <- c(-2, -2, 2, 2)*signal_size # 长度应和真实 group_num_sub 保持一致
# beta_nonzero <- c(-3, -1, 1, 3) # 长度应和真实 group_num_sub 保持一致
alpha_nonzero <- c(-3, -1, 1, 3)*signal_size
# alpha_nonzero <- c(-2, -2, 2, 2) # 验证最简单情况不需要 alpha
# alpha_nonzero <- c(0, 0, 0, 0) # 验证最简单情况不需要 alpha
# beta_vlen <- 3
# alpha_vlen <- 2

q_c_seed_max <- 20
group_num_main <- 2                    
group_num_sub <- 4    
hier_struc <- list(c(1,2),c(3,4))
prob_sub <- rep(1/group_num_sub, group_num_sub)  
reverse <- FALSE
```

```{r}
whole.data <- generate_all_data(dt_seed, n, p, q, prob_sub, hier_struc, 
                                beta_nonzero, alpha_nonzero, beta_vlen, alpha_vlen, 
                                cotype_x, cotype_z, epsilon_sd, reverse)
X <- whole.data$data$X
Z <- whole.data$data$Z
data <- whole.data$data$data_full
coef <- whole.data$coef
# coefv <- lapply(coef, as.vector) # 按照类别拉长
ci_sim <- whole.data$ci_sim
y <- matrix(whole.data$y, ncol=1)

# =============================== prepare =================================
comb_pair <- combn(K_up, 2)
H_p <- kronecker(t(apply(comb_pair, 2, get_e_mat, K_up)),
                 diag(p)) %>% Matrix(sparse = TRUE)
H_q <- kronecker(t(apply(comb_pair, 2, get_e_mat, K_up)),
                 diag(q)) %>% Matrix(sparse = TRUE)


# =============================== result =================================
colnames_all <- c("dt_seed", "q_c_seed", "aa", "tau", "l1", "l2", "l3",
                  "cdist", "ci_prob_mean", "mse", "sc", "fit_sum", "fit_mean",
                  "penal", "bic_sum", "bic_mean", "main_grn", "sub_grn", "valid_hier", 
                  "group_detail", paste0("case_", 1:4), "tag")


result <- as.data.frame(matrix(NaN, nrow = 2, ncol = length(colnames_all)))
colnames(result) <- colnames_all
result$dt_seed <- dt_seed
```

# 初始化

```{r}
q_c_seed <- 9
minprior_value <- 0
set.seed(q_c_seed)
pi_init <- rep(1/K_up, K_up)
rho_init <- rep(1, K_up)/sigma_est
q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = 0, sd = .1))
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

tryCatch({
    flemix_forinit <- flexmix_init(q_c_seed, 0)
  }, error = function(err) {
    cat("Random Init\n")
    flemix_forinit <- random_init(q_c_seed)
  })

m_glm <- tryCatch({
  flexmix(y~cbind(X, Z)-1, cluster = q_c_matrix,
          model = FLXMRglm(),
          control = list(minprior = minprior_value))
}, error = function(err) {
  cat("Error occurred:", conditionMessage(err), "\n")
  flexmix(y~cbind(X, Z)-1, k = K_up,
          model = FLXMRglm(),
          control = list(minprior = minprior_value))
})
```


```{r}
q_c_seed <- 1
# 为初始化的不可以压缩类别
flemix_forinit <- flexmix_init(q_c_seed, 0)
result[1,'q_c_seed'] <- q_c_seed
result[1,'sub_grn'] <- flemix_forinit$est_sub_grn
result[1,'sc'] <- flemix_forinit$sc_score
result[1,'cdist'] <- flemix_forinit$cdist
result[1,'tag'] <- flemix_forinit$tag

# 作为对比使用的 flexmix 结果应该呈现其最好结果，允许类别压缩
flemix_best <- flexmix_init(q_c_seed, 0.1)
result[2,'q_c_seed'] <- q_c_seed
result[2,'sub_grn'] <- flemix_best$est_sub_grn
result[2,'sc'] <- flemix_best$sc_score
result[2,'cdist'] <- flemix_best$cdist
result[2,'tag'] <- flemix_best$tag
```


# 调参

如果为了单独进行一两组实验，验证封装函数的正确性，不需要这一步，直接跳到下面

```{r}
# # l2_seq <- c(0, 1, 2, 4, 6)
# # l3_seq <- c(0, 1, 2, 4, 6)
# l2_seq <- c(0, 1, 2)
# l3_seq <- c(0, 1, 2)
# fix_para <- list(dt_seed = dt_seed, q_c_seed = q_c_seed, lambda_1 = 0.3,
#                  aa = 1.2, tau = 1)
# # fix_para <- expand.grid(list(dt_seed = dt_seed, q_c_seed = q_c_seed, lambda_1 = 0.3,
# #                  aa = 1.2, tau = 1, lambda_2 = l2_seq, lambda_3 = l3_seq))
# temp <- tuning_hyper(l2_seq, l3_seq, fix_para, flemix_forinit$coef_full_ori, save_all = TRUE)
# # result <- rbind(result, 
# #                 tuning_hyper(l2_seq, l3_seq, fix_para, flemix_forinit$coef_full_ori))
```


# 单独实验


dt_seed 9 q_c_seed 1 l1 0.3 l2 0.3 l3 0.3 tau 1 a 1.2 
**** result: est_main_grn 2 est_sub_grn 4 mse 20.6995674980019 sc 0.761370741482966 BIC.var 6.49021359385721 BIC.o 3.42784772453573 valid_hier TRUE group_detail (1,1)(3,1)(4,1)(2,2)(1,3)(3,3)(4,3)(1,4)(3,4)(4,4) 

dt_seed 9 q_c_seed 1 l1 0.3 l2 0.3 l3 0.3 tau 1 a 1.2 
**** result: est_main_grn 1 est_sub_grn 4 mse 19.2231234115282 sc 0.64910621242485 BIC.var 5.55118948945863 BIC.o 3.25441508746752 valid_hier TRUE group_detail (1,1)(2,1)(3,1)(4,1)(1,2)(2,2)(3,2)(4,2)(1,3)(2,3)(3,3)(4,3)(1,4)(2,4)(3,4)(4,4) 



```{r}
# result <- NULL
fix_para <- list(dt_seed = dt_seed, q_c_seed = q_c_seed, lambda_1 = 0.3,
                 aa = 1.2, tau = 1)
# l2_seq <- c(4, 6, 8)
# l3_seq <- c(4, 5, 6, 7, 8)

l2_seq <- c(3)
l3_seq <- c(5)
trail_set <- expand.grid(list(l3 = l3_seq, l2 = l2_seq))

trail_num <- nrow(trail_set)
bic_record <- rep(-Inf, trail_num)
bico_record <- rep(-Inf, trail_num)
trail_record <- vector(mode = "list",length = trail_num)
coef_full_init <- flemix_forinit$coef_full_ori

trail_idx <- 1
for(trail_idx in 1:trail_num){
  lambda_2 <- trail_set$l2[trail_idx]
  lambda_3 <- trail_set$l3[trail_idx]
  
  trail <- ADMM_trail(aa = fix_para$aa,
                      tau = fix_para$tau,
                      lambda_1 = fix_para$lambda_1,
                      lambda_2 = lambda_2,
                      lambda_3 = lambda_3,
                      q_c_seed = fix_para$q_c_seed,
                      coef_full_init = coef_full_init)
  trail_record[[trail_idx]] <- trail
  
  result <- rbind(result, c(fix_para$dt_seed,
              fix_para$q_c_seed,
              fix_para$aa,
              fix_para$tau,
              fix_para$lambda_1,
              lambda_2,
              lambda_3,
              trail$cdist,
              trail$ci_prob_mean,
              trail$mse,
              trail$sc_score,
              trail$BIC.var,
              trail$fit_sum,
              trail$fit_mean,
              trail$penal,
              trail$bic_sum,
              trail$bic_mean,
              trail$est_main_grn,
              trail$est_sub_grn,
              trail$valid_hier,
              trail$group_detail,
              trail$case_table_full,
              "hier"))
}
```











```{r}
Cn <- log(n*(p+q))
q_c_matrix <- trail$q_c_matrix
coef_est <- trail$coef_full_ori
K_main <- trail$est_main_grn
K_sub <- trail$est_sub_grn
rho_est <- trail$rho_est
y <- whole.data$y

fit_error_mat = matrix(0, n, K_sub)
pi_est <- apply(q_c_matrix, 2, sum)/n
fit_matrix <- dnorm(y, mean = data%*%coef_est, sd = 1/extend_x_to_row(rho_est, n)) *
      extend_x_to_row(pi_est, n)
fit_prob <- apply(fit_matrix, 1, sum)
fit_error <- -2 * sum(log(fit_prob + min(fit_prob[fit_prob>0])))
bic_sum <- fit_error + Cn*log(n)/n*(K_main*p+K_sub*q)
bic_mean <- fit_error/n + Cn*log(n)/n*(K_main*p+K_sub*q)
```

```{r}
fit_error
fit_error/n
bic_sum
bic_mean
```


```{r}
fit_error
fit_error/n
bic_sum
bic_mean
```



```{r}
data %*% trail$coef_full_ori
```




