---
title: "结果分析"
author: "Yan Ren"
date: "2023-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# terminal generator

## oracle

```{r}
library(glue)
n <- 500
p <- 80
q <- 40
epsilon_sd <- 0.5
epsilon_sd_init <- 0.5
signal_size <- 1
beta_vlen <- 20
alpha_vlen <- 10
rho_ratio <- 0.0
balance <- 1
cotype <- 'En'
# dt_seed <- 9
K_up <- 4

prefix <- "hierarchical-gene/code_v2/"
prefix <- ""
path_pre <- glue("{prefix}{Sys.Date()}_n{n}_p{p}_q{q}_b{balance}_ss{signal_size}_bl{beta_vlen}_al{alpha_vlen}_eps{epsilon_sd}_epi{epsilon_sd_init}_rr{rho_ratio}_Kup{K_up}_ct{cotype}_oracle")
# path_pre <- glue("2023-07-31_n{n}_p{p}_q{q}_bl{beta_vlen}_al{alpha_vlen}_eps{epsilon_sd}_fminit")
cmd <- glue("Rscript --verbose {prefix}oracle.R -n {n} -p {p} -q {q} -b {balance} -e {epsilon_sd} --epsilon_sd_init {epsilon_sd_init} --rho_ratio {rho_ratio} --signal_size {signal_size} --beta_vlen {beta_vlen} --alpha_vlen {alpha_vlen} --K_up {K_up} --cotype {cotype} --path {path_pre}.csv >> {path_pre}_log.out")
print(cmd)
```


## sim

Rscript --verbose test.R -n 500 --dt_seed 9 -p 8 -q 4 -e 0.5 --beta_vlen 3 --alpha_vlen 2 --K_up 4 --path 2023-11-28_n500_p8_q4_bl3_al2_eps0.5_Kup4_fminit.csv >> 2023-11-28_n500_p8_q4_bl3_al2_eps0.5_Kup4_fminit_log.out


```{r}
library(glue)
n <- 500
p <- 80
q <- 40
epsilon_sd <- 0.5
epsilon_sd_init <- 0.5
signal_size <- 2
beta_vlen <- 20
alpha_vlen <- 10
rho_ratio <- 0.1
balance <- 1
cotype <- 'En'
# dt_seed <- 9
K_up <- 6


# n <- 500
# p <- 8
# q <- 40
# epsilon_sd <- 0.5
# epsilon_sd_init <- 0.5
# signal_size <- 1
# beta_vlen <- 4
# alpha_vlen <- 16
# rho_ratio <- 0.1
# balance <- 1
# cotype <- 'En'
# # dt_seed <- 9
# K_up <- 4

for(dt_seed in seq(9, 99, 10)){
  prefix <- "hierarchical-gene/code_v2/"
  # prefix <- ""
    path_pre <- glue("{prefix}{Sys.Date()}_n{n}_p{p}_q{q}_b{balance}_ss{signal_size}_bl{beta_vlen}_al{alpha_vlen}_eps{epsilon_sd}_epi{epsilon_sd_init}_rr{rho_ratio}_Kup{K_up}_ct{cotype}_fminit")
  # path_pre <- glue("2023-07-31_n{n}_p{p}_q{q}_bl{beta_vlen}_al{alpha_vlen}_eps{epsilon_sd}_fminit")
  cmd <- glue("Rscript --verbose {prefix}test.R -n {n} --dt_seed {dt_seed} -p {p} -q {q} -b {balance} -e {epsilon_sd} --epsilon_sd_init {epsilon_sd_init} --rho_ratio {rho_ratio} --signal_size {signal_size} --beta_vlen {beta_vlen} --alpha_vlen {alpha_vlen} --K_up {K_up} --cotype {cotype} --path {path_pre}.csv >> {path_pre}_log.out")
  print(cmd)
}
```

## real


```{r}
library(glue)
n <- 140
p <- 6
q <- 30
epsilon_sd <- 0.5
K_up <- 6
y_type <- "dlco"
prefix <- "hierarchical-gene/code_v2/"
prefix <- ""
# path_pre <- glue("{prefix}{Sys.Date()}_real_n{n}_p{p}_q{q}_eps{epsilon_sd}_Kup{K_up}_fminit")
path_pre <- glue("{prefix}{Sys.Date()}_real2_n{n}_p{p}_q{q}_eps{epsilon_sd}_Kup{K_up}_fminit_{y_type}")
# path_pre <- glue("2023-07-31_n{n}_p{p}_q{q}_bl{beta_vlen}_al{alpha_vlen}_eps{epsilon_sd}_fminit")
cmd <- glue("Rscript --verbose {prefix}real.R -n {n} -p {p} -q {q} -e {epsilon_sd} --K_up {K_up} --y_type {y_type} --path {path_pre}.csv >> {path_pre}_log.out")
print(cmd)
```


## log.out

```{r}
# 提取分析 .out 文件
# out <- read.delim("main_test2.out")
# library(stringr)
# info_qc <- str_extract_all(out, '(?<=q_c_seed )\\d')
# info_aa <- str_extract_all(out, '(?<= a )[\\d\\.]*')
# info_l1 <- str_extract_all(out, '(?<= l1 )[\\d\\.]*')
# info_l2 <- str_extract_all(out, '(?<= l2 )[\\d\\.]*')
# info_l3 <- str_extract_all(out, '(?<= l3 )[\\d\\.]*')
# info_tau <- str_extract_all(out, '(?<= tau )[\\d\\.e-]*')
# info_sc <- str_extract_all(out, '(?<=\\[1\\] )[\\d]*[\\.]+[\\d]*')
# 
# 
# 
# outres <- cbind(data.frame(q_c_seed = info_qc[[1]], 
#                            aa = info_aa[[1]],
#                            l1 = info_l1[[1]],
#                            l2 = info_l2[[1]],
#                            l3 = info_l3[[1]],
#                            tau = info_tau[[1]]), t(matrix(info_sc[[1]], nrow = 2)))
# colnames(outres) <- c("q_c_seed", 'aa', "l1", "l2", "l3", "tau", "cdist", "mse")
# write.csv(outres, file = "out.csv", row.names = F)
# 
# 
# plot(outres$mse, outres$cdist)
# par(mfrow = c(2,5))
# plot(outres$aa, outres$mse)
# plot(outres$l1, outres$mse)
# plot(outres$l2, outres$mse)
# plot(outres$l3, outres$mse)
# plot(outres$tau, outres$mse)
# 
# plot(outres$aa, outres$cdist)
# plot(outres$l1, outres$cdist)
# plot(outres$l2, outres$cdist)
# plot(outres$l3, outres$cdist)
# plot(outres$tau, outres$cdist)
```



# csv result

```{r}
library(ggplot2)
library(dplyr)
# library(plotly)
df <- read.csv("2024-02-26_n500_p8_q4_ss2_bl3_al2_eps0.5_epi0.5_rr0.2_Kup6_fminit.csv")
df <- read.csv("2024-02-27_n500_p8_q4_b3_ss2_bl3_al2_eps0.5_epi0.5_rr0.2_Kup4_ctEn_fminit.csv")
df <- read.csv("2024-02-28_n500_p8_q4_b3_ss2_bl3_al2_eps0.5_epi0.5_rr0.2_Kup4_ctAR3_fminit.csv")
df <- read.csv("2024-03-04_n500_p80_q40_b1_ss2_bl3_al2_eps0.5_epi0.5_rr0.1_Kup4_ctEn_fminit.csv")
df <- read.csv("2024-03-06_n500_p80_q40_b1_ss1_bl3_al2_eps0.5_epi0.5_rr0.1_Kup4_ctEn_fminit.csv")
df <- read.csv("2024-03-09_n500_p80_q40_b1_ss2_bl3_al2_eps0.5_epi0.5_rr0.1_Kup6_ctEn_fminit.csv")
df <- read.csv("2024-03-10_n500_p80_q40_b2_ss2_bl3_al2_eps0.5_epi0.5_rr0.1_Kup6_ctEn_fminit.csv")
df <- read.csv("2024-03-11_n500_p80_q40_b3_ss1_bl3_al2_eps0.5_epi0.5_rr0.1_Kup6_ctEn_fminit.csv")
df <- read.csv("2024-03-12_n500_p80_q40_b3_ss2_bl3_al2_eps0.5_epi0.5_rr0.1_Kup4_ctEn_fminit.csv")
df <- read.csv("2024-03-14_n500_p80_q40_b1_ss1_bl20_al10_eps0.5_epi0.5_rr0.1_Kup6_ctEn_fminit.csv")
df <- read.csv("2024-03-15_n500_p80_q40_b1_ss2_bl20_al10_eps0.5_epi0.5_rr0.1_Kup6_ctEn_fminit.csv")
# 以下方法过期，直接看 tag 列即可
# df <- df %>% mutate(method = ifelse(q_c_seed < 100, 1, 0))
# df$method <- ifelse(df$q_c_seed == 111, -1, df$method)
# df$method <- factor(df$method, levels = c(-1, 0, 1), labels = c("random", "flexmix", "our_method"))
# df %>% mutate(method = vec_case_when(q_c_seed < 100 ~ q_c_seed,
#                        q_c_seed == 111 ~ -1,
#                        q_c_seed == 999 ~ 0))
# df$method <- factor(as.integer(df$q_c_seed %in% c(111, 999)), levels = c(0,1), labels = c("our method", "flemix or random"))
```


```{r}
n <- 500
df <- df %>% mutate(bic_mean2 = fit_mean + penal/log(n))
df <- df %>% mutate(bic_mean2 = bic_mean)

df_report <- df %>% 
  select(dt_seed, q_c_seed, l2, l3, mse, 
         cdist, cdist_main, cdist_sub, sc, sc_main, sc_sub, 
         ari, ari_main, ari_sub,
         main_grn, sub_grn, fit_mean, penal, bic_sum, bic_mean2, tag) %>%
  filter(l2 > 0 & l3 > 0) %>%
  filter(tag == 'hier') %>%
  group_by(dt_seed, q_c_seed, tag) %>% 
  arrange(bic_mean2) %>%
  filter(row_number() == 7) %>%
  arrange(dt_seed, q_c_seed)
df_report2 <- df_report %>%
  group_by(dt_seed) %>%
  summarise(per_main = sum(main_grn == 2)/n(),
            per_sub = sum(sub_grn == 4)/n(),
            sc = mean(sc),
            sc_main = mean(sc_main),
            sc_sub = mean(sc_sub),
            ari = mean(ari),
            ari_main = mean(ari_main),
            ari_sub = mean(ari_sub),
            cdist = mean(cdist),
            cdist_main = mean(cdist_main, na.rm = T),
            cdist_sub = mean(cdist_sub, na.rm = T))
# df_report2
df_result <- colMeans(df_report2, na.rm = T)
df_result <- data.frame(t(df_result)) %>% select(-dt_seed) %>% round(3) %>%
  select(per_main, per_sub, sc_main, sc_sub, 
         ari_main, ari_sub, cdist_main, cdist_sub)
df_result
write.table(format(df_result, nsmall = 4), "clipboard", sep = "\t", row.names = FALSE, col.names = FALSE)
```

```{r}
df_compare <- df %>% 
  select(dt_seed, q_c_seed, mse, 
         cdist, cdist_main, cdist_sub, sc, sc_main, sc_sub, ari, ari_main, ari_sub,
         main_grn, sub_grn, bic_mean, tag) %>%
  filter(tag == 'flexmix') %>% 
  group_by(dt_seed) %>%
  summarise(per_main = sum(main_grn == 2)/n(),
            per_sub = sum(sub_grn == 4)/n(),
            sc = mean(sc),
            sc_main = mean(sc_main),
            sc_sub = mean(sc_sub),
            ari = mean(ari),
            ari_main = mean(ari_main),
            ari_sub = mean(ari_sub),
            cdist = mean(cdist),
            cdist_main = mean(cdist_main, na.rm = T),
            cdist_sub = mean(cdist_sub, na.rm = T))

df_compare <- colMeans(df_compare, na.rm = T)

df_compare <- data.frame(t(df_compare)) %>% select(-dt_seed) %>% round(3) %>%
  select(per_main, per_sub, sc_main, sc_sub, 
         ari_main, ari_sub, cdist_main, cdist_sub)
df_compare
write.table(format(df_compare, nsmall = 4), "clipboard", sep = "\t", row.names = FALSE, col.names = FALSE)
```


```{r}
df_report %>%
  group_by(dt_seed) %>%
  summarise(per_main = sum(main_grn == 2)/n(),
            per_sub = sum(sub_grn == 4)/n(),
            sc = max(sc),
            ari = max(ari))
```


```{r}
ggplot(df_report, aes(x = sc, fill = tag)) +
  geom_histogram(position = "identity")
```


```{r}
df_report %>% arrange(-sc)
```


```{r}
ggplot(df_report, aes(x = sc, y = cdist, col = tag)) +
  geom_point(aes(size = 2, alpha = 0.5)) +
  theme_bw() +
  facet_wrap(~ dt_seed) +
  guides(size = FALSE, alpha = FALSE)
```

# summary

直接使用汇总数据得到结果

```{r}
library(ggplot2)
library(ggpubr)
library(dplyr)
# df <- read.csv("summary_data/lowxz_b23.csv")
df <- read.csv("summary_data/highxz_b23.csv")
df <- df %>% filter(signal == 2, K_up == 4)
df$method <- factor(df$method, levels = c("proposed", "oracle", "FMR2", 
                                          "resiclust2", "respclust2",
                                          "FMR1", "resiclust1", "respclust1"))
```

```{r}
get_btype_plot <- function(btype){
  df_use <- df %>% filter(bl == btype)
  p_list <- NULL
  score_names <- c("per_main", "per_sub", "SC_main", "SC_sub", "MSE_main", "MSE_sub")
  for(i in 1:length(score_names)){
    col <- rlang::sym(score_names[i])
    p_list[[i]] <- ggplot(df_use, aes(x = method, y = !!col, 
                                      fill = method)) +
      geom_bar(stat = "identity",width = 1, col = "black") +
      scale_fill_brewer(palette = "Pastel1") +
      theme_minimal() +
      theme(axis.title.x = element_blank(),
            axis.text.x = element_blank())
  }
  return(p_list)
}
```

```{r}
p1_list <- get_btype_plot(1)
p2_list <- get_btype_plot(2)
p3_list <- get_btype_plot(3)
p_list <- c(p1_list, p2_list, p3_list)
```

```{r}
pdf('test.pdf',height = 10,width=14)
do.call("ggarrange", c(p_list, nrow = 3, ncol = 6, common.legend = TRUE, legend = "bottom"))
dev.off()
```



```{r}
# ggarrange(p1_list[[1]],p1_list[[2]],p1_list[[3]],
#           p1_list[[4]],p1_list[[5]],p1_list[[6]],
#           p2_list[[1]],p2_list[[2]],p2_list[[3]],
#           p2_list[[4]],p2_list[[5]],p2_list[[6]],
#           p3_list[[1]],p3_list[[2]],p3_list[[3]],
#           p3_list[[4]],p3_list[[5]],p3_list[[6]], 
#           nrow = 3, ncol = 6, common.legend = TRUE, legend = "bottom")
```

# score

```{r}
library(ggplot2)
library(dplyr)
library(plotly)
library(simplermarkdown)

# df <- read.csv("2023-11-30_n500_p8_q4_bl3_al2_eps0.5_Kup4_fminit.csv")
# df <- read.csv("2023-12-01_n500_p8_q4_bl3_al2_eps0.5_Kup6_fminit.csv")
# df <- read.csv("2023-12-06_n500_p40_q4_bl3_al2_eps0.5_Kup4_fminit.csv")
# df <- read.csv("2023-12-10_n500_p40_q4_bl3_al2_eps0.5_Kup6_fminit.csv")
# df <- read.csv("2023-12-12_n500_p80_q4_bl3_al2_eps0.5_Kup4_fminit.csv")
# df <- read.csv("2023-12-18_n500_p8_q40_bl3_al2_eps0.5_Kup4_fminit.csv")
# df <- read.csv("2023-12-18_n500_p8_q40_bl3_al2_eps0.5_Kup6_fminit.csv")
# df <- read.csv("2023-12-28_n500_p8_q40_bl3_al10_eps0.5_Kup4_fminit.csv")

df <- read.csv("2023-12-22_real_n160_p6_q20_eps0.5_Kup8_fminit.csv")
df <- read.csv("2023-12-29_real_n160_p6_q30_eps0.5_Kup8_fminit.csv")
# 以下废弃，仅针对很久版本的数据记录样式
# df <- df %>% mutate(method = ifelse(q_c_seed < 100, 1, 0))
# df$method <- ifelse(df$q_c_seed == 111, -1, df$method)
# df$method <- factor(df$method, levels = c(-1, 0, 1), labels = c("random", "flexmix", "hier"))
```

```{r}
df_tmp2 <- df %>%
  # group_by(dt_seed, q_c_seed) %>%
  group_by(dt_seed) %>%
  filter(bic_mean == min(bic_mean, na.rm = TRUE)) %>%
  mutate(filter_type = "bic_mean")

df_compare <- df %>%
  filter(tag == 'flexmix') %>%
  group_by(dt_seed) %>%
  filter(sc == min(sc)) %>%
  mutate(filter_type = "bic_mean") %>%
  select(dt_seed, sc) %>%
  rename(sc_flexmix = sc) %>%
  filter(row_number() == 1)
```

```{r}
df_report <- df_tmp %>% 
  select(dt_seed, q_c_seed, aa, tau, l1, l2, l3, cdist, sc, bic_mean, main_grn, sub_grn) %>%
  group_by(dt_seed) %>%
  filter(row_number() == 1) 

df_report <- merge(df_report, df_compare) %>%
  mutate(sc = round(sc, 3),
         sc_flexmix = round(sc_flexmix, 3),
         bic_mean = round(bic_mean, 3)) %>%
  rename(bic = bic_mean)
md_table(df_report)
```




```{r}
df1 <- df %>%
  group_by(q_c_seed) %>%
  filter(fit_sum == min(fit_sum, na.rm = TRUE)) %>%
  mutate(filter_type = "fit_sum")
df2 <- df %>%
  group_by(q_c_seed) %>%
  filter(fit_mean == min(fit_mean, na.rm = TRUE)) %>%
  mutate(filter_type = "fit_mean")
df3 <- df %>%
  group_by(q_c_seed) %>%
  filter(bic_sum == min(bic_sum, na.rm = TRUE)) %>%
  mutate(filter_type = "bic_sum")
df4 <- df %>%
  group_by(q_c_seed) %>%
  filter(bic_mean == min(bic_mean, na.rm = TRUE)) %>%
  mutate(filter_type = "bic_mean")
df_tmp <- rbind(df1, df2, df3, df4)
```


```{r}
# df$q_c_seed <- factor(df$q_c_seed)
# df_tmp$q_c_seed <- factor(df_tmp$q_c_seed)
# ggplot(df, aes(x = cdist, y = fit_sum)) +
#   geom_point(aes(alpha = 0.4)) +
#   theme_bw() +
#   facet_wrap(~ q_c_seed)
```







