---
title: "Trial"
author: "Yan Ren"
date: "2023-07-10"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
rm(list = ls(all = TRUE))
library(ggplot2)
library(dplyr)
library(Matrix)
library(flexmix)
source("sim.R")
source("tools.R")
source("func.R")
```



```{r}
# 超参数设定
n <- 200
p <- 8
q <- 4
cotype_x <- "En"
cotype_z <- "En"
epsilon_sd <- 0.0
beta_nonzero <- c(-2, -2, 2, 2) # 长度应和真实 group_num_sub 保持一致
# beta_nonzero <- c(-3, -1, 1, 3) # 长度应和真实 group_num_sub 保持一致
alpha_nonzero <- c(-3, -1, 1, 3)
# alpha_nonzero <- c(-2, -2, 2, 2) # 验证最简单情况不需要 alpha
# alpha_nonzero <- c(0, 0, 0, 0) # 验证最简单情况不需要 alpha
beta_vlen <- 3
alpha_vlen <- 2

K_up <- 4  # 估计时的最大类别，应该不少于 group_num_sub
group_num_main <- 2                    
group_num_sub <- 4    
hier_struc <- list(c(1,2),c(3,4))
prob_sub <- rep(1/group_num_sub, group_num_sub)  
reverse <- FALSE

aa <- 1.2
lambda_1 <- 0.2
```

```{r}
set.seed(9)
whole.data <- generate_all_data(n, p, q, prob_sub, hier_struc, 
                  beta_nonzero, alpha_nonzero, beta_vlen, alpha_vlen, 
                  cotype_x, cotype_z, epsilon_sd, reverse)
X <- whole.data$data$X
Z <- whole.data$data$Z
data <- whole.data$data$data_full
coef <- whole.data$coef
coefv <- lapply(coef, as.vector) # 按照类别拉长
ci_sim <- whole.data$ci_sim
y <- matrix(whole.data$y, ncol=1)
```


```{r}
comb_pair <- combn(K_up, 2)
H_p <- kronecker(t(apply(comb_pair, 2, get_e_mat, K_up)),
          diag(p)) %>% Matrix(sparse = TRUE)
H_q <- kronecker(t(apply(comb_pair, 2, get_e_mat, K_up)),
          diag(q)) %>% Matrix(sparse = TRUE)
```


# 完整框架

```{r}
q_c_seed <- 99
```


## flexmix 结果

```{r}
# rho_init <- c(1, 1, 1, 1)/1
# # 全随机
# set.seed(q_c_seed)
# pi_init <- rep(1/K_up, K_up)
# q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = 0, sd = .1))
# q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
# # flexmix 包结果
# m_glm <- flexmix(y~cbind(X, Z)-1, k = K_up, cluster = q_c_matrix,
#                  model = FLXMRglm(),
#              control = list(minprior = 0))
# coef_full_init <- parameters(m_glm)[1:(p+q),] *
#   t(kronecker(rho_init, matrix(1, ncol = p+q)))
# coef_full_init
# coef_dist(coef_full_init, coef$coef_full)
```



## hier 结果

```{r}
td <- ADMM_trail(aa = 1.2,
                   tau = 0,
                   lambda_1 = 0.7,
                   lambda_2 = 0,
                   lambda_3 = 0,
                   q_c_seed = 2)
a <- 1.2
tau <- 0
lambda_1 <- 0.7
lambda_2 <- 0
lambda_3 <- 0
q_c_seed <- 2
```


```{r}
para_set <- expand.grid(list(q_c_seed = 1:5,
                             lambda_1 = seq(0.1, 0.5, 0.1),
                             lambda_2 = seq(0.0, 2, 0.5),
                             lambda_3 = seq(0.0, 2, 0.5),
                             aa = seq(1.2, 2.4, 0.6),
                             tau = seq(0, 2, 0.5)))
result <- NULL
for(i in 1:nrow(para_set[,])){
  if(i%%10 == 0){print(i);print("*************")}
  para <- para_set[i,]
  td <- ADMM_trail(aa = para$aa,
                   tau = para$tau,
                   lambda_1 = para$lambda_1,
                   lambda_2 = para$lambda_2,
                   lambda_3 = para$lambda_3,
                   q_c_seed = para$q_c_seed)
  result <- rbind(result, c(td$cdist, td$ci_prob_mean, td$mse))
}
colnames(result) <- c("cdist", "ci_prob_mean", "mse")
res <- cbind(para_set[1:nrow(result),], result)
write.csv(res, file = "2023-07-15-trail.csv", row.names = F)
```


```{r}
ADMM_trail(aa=1.2, tau=0.5, lambda_1=0.08, lambda_2=2, lambda_3=0, q_c_seed=q_c_seed)
```
























两种初始化（0初始化，flexmix 初始化）在代码中进行调整

```{r}
eps <- 1e-7 # case 4 才使用
eps <- 0 # case 4 才使用
tau <- 0.5
tau <- ifelse(tau == 0, 1e-4, tau) # 防止 tau == 0 导致分母为0情况
aa <- 1.2
lambda_1 <- 0.08
# tau <- 1
# aa <- 1.2
# lambda_1 <- 0

lambda_2 <- 2
lambda_3 <- 0.0
rho_init <- c(1, 1, 1, 1)/1

kj <- function(dim) {return((k-1)*dim+j)}
ks <- function(dim) {return((k-1)*dim+s)}
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
set.seed(q_c_seed)
# q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
# 真值附近
# q_c_matrix <- abs(get_q_c_matrix(n, K_up, ci_sim) + rnorm(n*K_up, mean = 1, sd = .1))
# 全随机
q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = 0, sd = .1))
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

# coef full
coef_full_init <- coef$coef_full - coef$coef_full
# coef_full_init[(p+1):(p+q),] <- coef$coef_alpha
# coef_full_init[1:p,] <- coef$coef_beta
# coef_full_init <- coef$coef_full * t(kronecker(rho_init, matrix(1, ncol = p+q)))
coef_full_list <- list(coef_full_init)
coef_full_ori_list <- list(coef_full_init/t(kronecker(rho_init, 
                                                      matrix(1, ncol = p+q))))

# coef diff (v,w):=u
diff_v_init <- matrix(H_p %*% as.vector(coef_full_init[1:p,]), ncol = 1)
# diff_v_init <- matrix(H_p %*% as.vector(coef$coef_beta), ncol = 1)
diff_v_list <- list(diff_v_init)
diff_w_init <- matrix(H_q %*% as.vector(coef_full_init[(p+1):(p+q),]), ncol = 1)
# diff_w_init <- matrix(H_q %*% as.vector(coef$coef_alpha), ncol = 1)
diff_w_list <- list(diff_w_init)

# dual variable (xi,zeta):=eta
dual_xi_init <- matrix(0, nrow = (p)*K_up*(K_up-1)/2, ncol = 1)
dual_xi_list <- list(dual_xi_init)
dual_zeta_init <- matrix(0, nrow = (q)*K_up*(K_up-1)/2, ncol = 1)
dual_zeta_list <- list(dual_zeta_init)

case <- NULL
u_tracker <- NULL
v_tracker <- NULL
cu_tracker <- NULL
cv_tracker <- NULL

for(iter in 2:200){
  rho_est <- rho_list[[iter-1]]
  coef_full_est <- coef_full_list[[iter-1]]
  coef_beta_est <- coef_full_est[1:p,]
  coef_alpha_est <- coef_full_est[(p+1):(p+q),]
  
  diff_v_est <- diff_v_list[[iter-1]]
  diff_w_est <- diff_w_list[[iter-1]]
  
  dual_xi_est <- dual_xi_list[[iter-1]]
  dual_zeta_est <- dual_zeta_list[[iter-1]]
  
  # =========================== beta, alpha update =========================
  # beta,alpha （相比矩阵形式，只修改 beta,alpha 更新）
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    for(j in 1:p){
      lower_1 <- t(X[,j]) %*% W_k %*% X[,j]
      lower_2 <- (t(H_p)%*%H_p)[kj(p), kj(p)]
      # lower_2 <- 0
      Lower <- lower_1/n + tau*lower_2
      upper_1 <- t(X[,j]) %*% W_k %*% (rho_est[k]*y - X[,-j]%*%(coef_beta_est[-j,k]) - Z%*%coef_alpha_est[,k])
      upper_2 <- (t(H_p)%*%(diff_v_est-dual_xi_est/tau))[kj(p)] - 
        as.vector(coef_beta_est)[-kj(p)]%*%((t(H_p)%*%H_p)[kj(p),-kj(p)])
      # upper_2 <- 0
      Upper <- upper_1/n + tau*upper_2
      # coef_beta_kj <- Upper/Lower
      coef_beta_kj <- mcp_solution(Lower, Upper/Lower, aa, lambda_1)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    for(s in 1:q){
      lower_1 <- t(Z[,s]) %*% W_k %*% Z[,s]
      lower_2 <- (t(H_q)%*%H_q)[ks(q), ks(q)]
      # lower_2 <- 0
      Lower <- lower_1/n + tau*lower_2
      upper_1 <- t(rho_est[k]*y - Z[,-s]%*%(coef_alpha_est[-s,k]) - X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      upper_2 <- (t(H_q)%*%(diff_w_est-dual_zeta_est/tau))[ks(q)] - 
        as.vector(coef_alpha_est)[-ks(q)]%*%((t(H_q)%*%H_q)[ks(q),-ks(q)])
      # upper_2 <- 0
      Upper <- upper_1/n + tau*upper_2
      # coef_alpha_ks <- Upper/Lower
      coef_alpha_ks <- mcp_solution(Lower, Upper/Lower, aa, lambda_1)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
  }
  coef_full_est <- rbind(coef_beta_est, coef_alpha_est)
    
  
  # rho 的更新
  # rho_list[[iter]] <- rho_list[[iter-1]]
  # coef_full_list[[iter]] <- coef_full_est
  # coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est,p+q)
  rho_list[[iter]] <- rho_est
  coef_full_list[[iter]] <- coef_full_est
  coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est,p+q)
  
  diff_v_est <- matrix(H_p %*% as.vector(coef_beta_est), ncol = 1)
  diff_w_est <- matrix(H_q %*% as.vector(coef_alpha_est), ncol = 1)
  
  # v,w 的更新 2 means prime
  diff_v2_est <- H_p%*%as.vector(coef_beta_est) + 1/tau*dual_xi_est
  diff_w2_est <- H_q%*%as.vector(coef_alpha_est) + 1/tau*dual_zeta_est
  
  for(k1 in 1:(K_up-1)){
    for(k2 in (k1+1):K_up){
      ikk <- which(apply(comb_pair, 2, function(x){all(x==c(k1,k2))}))

      v_kk <- diff_v_est[((ikk-1)*p+1):(ikk*p)]
      w_kk <- diff_w_est[((ikk-1)*q+1):(ikk*q)]
      u_kk <- c(v_kk, w_kk)
      
      v_kk.F <- norm(matrix(v_kk), type = "2")
      w_kk.F <- norm(matrix(w_kk), type = "2")
      u_kk.F <- sqrt(v_kk.F**2 + w_kk.F**2)
      
      v_kk2 <- diff_v2_est[((ikk-1)*p+1):(ikk*p)]
      w_kk2 <- diff_w2_est[((ikk-1)*q+1):(ikk*q)]

      v_kk2.F <- norm(matrix(v_kk2), type = "2")
      w_kk2.F <- norm(matrix(w_kk2), type = "2")
      u_kk2.F <- sqrt(v_kk2.F**2 + w_kk2.F**2)

      cu <- positive_part(1-lambda_2/tau/u_kk2.F)/(1-1/aa/tau)
      cv <- positive_part(1-lambda_3/tau/v_kk2.F)/(1-1/aa/tau)
      if(is.na(cu)){ print(paste(iter, "cu na of k1 k2", k1, k2)); cu <- 0 }
      if(is.na(cv)){ print(paste(iter, "cv na of k1 k2", k1, k2)); cv <- 0 }
      # 判断压缩类别
      case_kk <- case_when(
        (u_kk2.F > aa*lambda_2) & (v_kk2.F > aa*lambda_3) ~ 1,
        (u_kk2.F <= aa*lambda_2) & (cu*v_kk2.F > aa*lambda_3) ~ 2,
        (w_kk2.F**2+(cv*v_kk2.F)**2 > (aa*lambda_2)**2) &
               (v_kk2.F <= aa*lambda_3) ~ 3,
        TRUE ~ 4
      )
      # tracker
      case <- c(case, case_kk)
      u_tracker <- c(u_tracker, u_kk2.F)
      v_tracker <- c(v_tracker, v_kk2.F)
      cu_tracker <- c(cu_tracker, cu)
      cv_tracker <- c(cv_tracker, cv)
      
      if(case_kk == 1){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2
      }else if(case_kk == 2){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- cu*v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- cu*w_kk2
      }else if(case_kk == 3){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- cv*v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2
      }else{
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- v_kk2/
          (1+mcp_d(u_kk.F,aa,lambda_2,TRUE)/tau/(u_kk.F+eps) +
             mcp_d(v_kk.F,aa,lambda_3,TRUE)/tau/(v_kk.F+eps))
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2/
          (1+mcp_d(u_kk.F,aa,lambda_2,TRUE)/tau/(u_kk.F+eps))
      }
    }
  }
  diff_v_list[[iter]] <- diff_v_est
  diff_w_list[[iter]] <- diff_w_est

  # xi,zeta 的更新
  dual_xi_list[[iter]] <- dual_xi_list[[iter-1]] +
    tau*(matrix(H_p%*%as.vector(coef_beta_est),ncol=1) - diff_v_list[[iter]])
  dual_zeta_list[[iter]] <- dual_zeta_list[[iter-1]] +
    tau*(matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) - diff_w_list[[iter]])
  
  # diff_v_list[[iter]] <- matrix(H_p%*%as.vector(coef_beta_est),ncol=1) + dual_xi_est/tau
  # diff_w_list[[iter]] <- matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) + dual_zeta_est/tau
  # dual_xi_list[[iter]] <- dual_xi_list[[iter-1]] +
  #   tau*(matrix(H_p%*%as.vector(coef_beta_est),ncol=1) - diff_v_list[[iter]])
  # dual_zeta_list[[iter]] <- dual_zeta_list[[iter-1]] +
  #   tau*(matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) - diff_w_list[[iter]])
  
  pi_est <- apply(q_c_matrix, 2, sum)/n
  pi_list[[iter]] <- pi_est
  
  # update q_c matrix
  # 用没有重参数化的形式
  q_c_matrix_back <- q_c_matrix
  q_c_matrix <- dnorm(y,
                      mean = data%*%coef_full_ori_list[[iter]],
                      sd = 1/extend_x_to_row(rho_est, n)) *
    extend_x_to_row(pi_list[[iter-1]], n)
  nan_id <- which(apply(q_c_matrix, 1, sum) == 0)
  if(length(nan_id == 0) > 0){ print(paste(iter, nan_id)) }
  q_c_matrix[nan_id,] <- q_c_matrix_back[nan_id,]
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  
  # coef_diff_std <- (sum(coef_full_list[[iter]]-coef_full_list[[iter-1]])**2)/
  #    (sum(coef_full_list[[iter]])**2 + 1e-4)
  # if(coef_diff_std < 1e-6){
  #   return()
  # }
}
coef_full_list[[iter]]
coef_full_ori_list[[iter]]
table(case)
plot(unlist(lapply(coef_full_ori_list, coef_dist, coef$coef_full)), ylab = "")
coef_dist(coef_full_ori_list[[iter]], coef$coef_full)
```


# 简单情况对照


## l2=l3=0

```{r}
# aa <- 1.2
# lambda_1 <- 0.08
rho_init <- c(1, 1, 1, 1)/1
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
set.seed(q_c_seed)
# 真值附近
# q_c_matrix <- abs(get_q_c_matrix(n, K_up, ci_sim) + rnorm(n*K_up, mean = 1, sd = .1))
# 全随机
q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) +
                  rnorm(n*K_up, mean = 0, sd = .1))
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

# coef full
coef_full_init <- coef$coef_full - coef$coef_full
coef_full_list <- list(coef_full_init)
coef_full_ori_list <- list(coef_full_init/t(kronecker(rho_init, 
                                                      matrix(1, ncol = p+q))))
for(iter in 2:200){
  rho_est <- rho_list[[iter-1]]
  coef_full_est <- coef_full_list[[iter-1]]
  coef_beta_est <- coef_full_est[1:p,]
  coef_alpha_est <- coef_full_est[(p+1):(p+q),]
  
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    rho_k <- rho_est[k]
    # beta
    for(j in 1:p){
      upper <- t(rho_k*y - X[,-j]%*%(coef_beta_est[-j,k]) -
                   Z%*%coef_alpha_est[,k]) %*% W_k %*% X[,j]
      lower <- t(X[,j]) %*% W_k %*% X[,j]
      # coef_beta_kj <- upper/lower
      coef_beta_kj <- mcp_solution(lower/n, upper/lower, aa, lambda_1)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    # alpha
    for(s in 1:q){
      upper <- t(rho_k*y - Z[,-s]%*%(coef_alpha_est[-s,k]) -
                   X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      lower <- t(Z[,s]) %*% W_k %*% Z[,s]
      # coef_alpha_ks <- upper/lower
      coef_alpha_ks <- mcp_solution(lower/n, upper/lower, aa, lambda_1)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
    coef_full_est[,k] <- c(coef_beta_est[,k], coef_alpha_est[,k])
    # 更新 rho_k
    # A <- -t(y)%*%W_k%*%y
    # B <- t(data%*%coef_full_est[,k]) %*% W_k %*% y
    # C <- matrix(1, ncol=n)%*%W_k%*%matrix(1, nrow=n)
    # rho_est[k] <- (-B - sqrt(B**2-4*A*C)) / (A*2)
  }
  rho_list[[iter]] <- rho_est
  coef_full_list[[iter]] <- coef_full_est
  coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est, p+q)
  
  # update q_c matrix
  q_c_matrix <- dnorm(y, 
                      mean = data%*%coef_full_ori_list[[iter]], 
                      sd = 1/extend_x_to_row(rho_est, n)) *
    extend_x_to_row(pi_list[[iter-1]], n)
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  pi_est <- apply(q_c_matrix, 2, sum) / n
  pi_list[[iter]] <- pi_est
  
  # coef_diff_std <- (sum(coef_full_list[[iter]]-coef_full_list[[iter-1]])**2)/
  #    (sum(coef_full_list[[iter]])**2 + 1e-4)
  # if(coef_diff_std < 1e-7){
  #   return()
  # }
}
coef_full_list[[iter]]
coef_full_ori_list[[iter]]
plot(unlist(lapply(coef_full_ori_list, coef_dist, coef$coef_full)), ylab = "")
coef_dist(coef_full_ori_list[[iter]], coef$coef_full)
```


















# test

```{r}
q_c_seed <- 4
set.seed(q_c_seed)
pi_init <- rep(1/K_up, K_up)
rho_init <- c(1, 1, 1, 1)/1
q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = 0, sd = .1))
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
m_glm <- flexmix(y~cbind(X, Z)-1, cluster = q_c_matrix,
                 model = FLXMRglm(),
                 control = list(minprior = 0.001))
coef_est <- parameters(m_glm)[1:(p+q),] *
  t(kronecker(rho_init, matrix(1, ncol = p+q)))
print(coef_est)
```




```{r}
source("func.R")
aa = 1.2
tau = 0.2
lambda_1 = 0.3
lambda_2 = 2
lambda_3 = 0.5
q_c_seed = 1
eps <- 1e-7
ADMM_trail(aa, tau, lambda_1, lambda_2, lambda_3, q_c_seed, coef$coef_full-coef$coef_full)
```


```{r}
aa = 1.2
tau = 0.5
lambda_1 = 0.3
lambda_2 = 0.1
lambda_3 = 2
q_c_seed = 1
eps <- 1e-7
set.seed(99)
# coef_full_init <- coef$coef_full - coef$coef_full
coef_full_init <- coef$coef_full - coef$coef_full  + rnorm(length(coef$coef_full), 0, 1)

tau <- ifelse(tau == 0, 1e-4, tau) # 防止 tau == 0 导致分母为0情况
rho_init <- c(1, 1, 1, 1)/1

kj <- function(dim) {return((k-1)*dim+j)}
ks <- function(dim) {return((k-1)*dim+s)}
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
set.seed(q_c_seed)
# q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
# 真值附近
# q_c_matrix <- abs(get_q_c_matrix(n, K_up, ci_sim) + rnorm(n*K_up, mean = 1, sd = .1))
# 全随机
q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = 0, sd = .1))
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

# coef full
# coef_full_init <- coef$coef_full - coef$coef_full

# coef_full_init[(p+1):(p+q),] <- coef$coef_alpha
# coef_full_init[1:p,] <- coef$coef_beta
# coef_full_init <- coef$coef_full * t(kronecker(rho_init, matrix(1, ncol = p+q)))
coef_full_list <- list(coef_full_init)
coef_full_ori_list <- list(coef_full_init/t(kronecker(rho_init, 
                                                      matrix(1, ncol = p+q))))



# coef diff (v,w):=u
diff_v_init <- matrix(H_p %*% as.vector(coef_full_init[1:p,]), ncol = 1)
# diff_v_init <- matrix(H_p %*% as.vector(coef$coef_beta), ncol = 1)
diff_v_list <- list(diff_v_init)
diff_w_init <- matrix(H_q %*% as.vector(coef_full_init[(p+1):(p+q),]), ncol = 1)
# diff_w_init <- matrix(H_q %*% as.vector(coef$coef_alpha), ncol = 1)
diff_w_list <- list(diff_w_init)

# dual variable (xi,zeta):=eta
dual_xi_init <- matrix(0, nrow = (p)*K_up*(K_up-1)/2, ncol = 1)
dual_xi_list <- list(dual_xi_init)
dual_zeta_init <- matrix(0, nrow = (q)*K_up*(K_up-1)/2, ncol = 1)
dual_zeta_list <- list(dual_zeta_init)

case <- NULL
cu_tracker <- NULL
cv_tracker <- NULL

for(iter in 2:100){
  rho_est <- rho_list[[iter-1]]
  coef_full_est <- coef_full_list[[iter-1]]
  coef_beta_est <- coef_full_est[1:p,]
  coef_alpha_est <- coef_full_est[(p+1):(p+q),]
  
  diff_v_est <- diff_v_list[[iter-1]]
  diff_w_est <- diff_w_list[[iter-1]]
  
  dual_xi_est <- dual_xi_list[[iter-1]]
  dual_zeta_est <- dual_zeta_list[[iter-1]]
  
  # =========================== beta, alpha update =========================
  # beta,alpha （相比矩阵形式，只修改 beta,alpha 更新）
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    for(j in 1:p){
      lower_1 <- t(X[,j]) %*% W_k %*% X[,j]
      lower_2 <- (t(H_p)%*%H_p)[kj(p), kj(p)]
      # lower_2 <- 0
      Lower <- lower_1/n + tau*lower_2
      upper_1 <- t(X[,j]) %*% W_k %*% (rho_est[k]*y - X[,-j]%*%(coef_beta_est[-j,k]) - Z%*%coef_alpha_est[,k])
      upper_2 <- (t(H_p)%*%(diff_v_est-dual_xi_est))[kj(p)] - 
        as.vector(coef_beta_est)[-kj(p)]%*%((t(H_p)%*%H_p)[kj(p),-kj(p)])
      # upper_2 <- 0
      Upper <- upper_1/n + tau*upper_2
      # coef_beta_kj <- Upper/Lower
      coef_beta_kj <- mcp_solution(Lower, Upper/Lower, aa, lambda_1)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    for(s in 1:q){
      lower_1 <- t(Z[,s]) %*% W_k %*% Z[,s]
      lower_2 <- (t(H_q)%*%H_q)[ks(q), ks(q)]
      # lower_2 <- 0
      Lower <- lower_1/n + tau*lower_2
      upper_1 <- t(rho_est[k]*y - Z[,-s]%*%(coef_alpha_est[-s,k]) - X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      upper_2 <- (t(H_q)%*%(diff_w_est-dual_zeta_est))[ks(q)] - 
        as.vector(coef_alpha_est)[-ks(q)]%*%((t(H_q)%*%H_q)[ks(q),-ks(q)])
      # upper_2 <- 0
      Upper <- upper_1/n + tau*upper_2
      # coef_alpha_ks <- Upper/Lower
      coef_alpha_ks <- mcp_solution(Lower, Upper/Lower, aa, lambda_1)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
  }
  coef_full_est <- rbind(coef_beta_est, coef_alpha_est)
  
  
  # rho 的更新
  # rho_list[[iter]] <- rho_list[[iter-1]]
  # coef_full_list[[iter]] <- coef_full_est
  # coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est,p+q)
  rho_list[[iter]] <- rho_est
  coef_full_list[[iter]] <- coef_full_est

  coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est,p+q)
  
  diff_v_est <- matrix(H_p %*% as.vector(coef_beta_est), ncol = 1)
  diff_w_est <- matrix(H_q %*% as.vector(coef_alpha_est), ncol = 1)
  diff_v_last <- diff_v_list[[iter-1]]
  diff_w_last <- diff_w_list[[iter-1]]
  
  # v,w 的更新 2 means prime
  diff_v2_est <- H_p%*%as.vector(coef_beta_est) + dual_xi_est
  diff_w2_est <- H_q%*%as.vector(coef_alpha_est) + dual_zeta_est
  
  for(k1 in 1:(K_up-1)){
    for(k2 in (k1+1):K_up){
      ikk <- which(apply(comb_pair, 2, function(x){all(x==c(k1,k2))}))
      
      v_kk <- diff_v_est[((ikk-1)*p+1):(ikk*p)]
      w_kk <- diff_w_est[((ikk-1)*q+1):(ikk*q)]
      u_kk <- c(v_kk, w_kk)
      
      v_kk_last <- diff_v_last[((ikk-1)*p+1):(ikk*p)]
      w_kk_last <- diff_w_last[((ikk-1)*q+1):(ikk*q)]
      u_kk_last <- c(v_kk_last, w_kk_last)
      
      v_kk.F <- norm(matrix(v_kk_last), type = "2")
      w_kk.F <- norm(matrix(w_kk_last), type = "2")
      u_kk.F <- sqrt(v_kk.F**2 + w_kk.F**2)
      
      v_kk2 <- diff_v2_est[((ikk-1)*p+1):(ikk*p)]
      w_kk2 <- diff_w2_est[((ikk-1)*q+1):(ikk*q)]
      
      v_kk2.F <- norm(matrix(v_kk2), type = "2")
      w_kk2.F <- norm(matrix(w_kk2), type = "2")
      u_kk2.F <- sqrt(v_kk2.F**2 + w_kk2.F**2)
      
      cu <- positive_part(1-lambda_2/tau/u_kk2.F)/(1-1/aa/tau)
      cv <- positive_part(1-lambda_3/tau/v_kk2.F)/(1-1/aa/tau)
      if(is.na(cu)){ print(paste(iter, "cu na of k1 k2", k1, k2)); cu <- 0 }
      if(is.na(cv)){ print(paste(iter, "cv na of k1 k2", k1, k2)); cv <- 0 }
      # 判断压缩类别
      case_kk <- case_when(
        (u_kk2.F > aa*lambda_2) & (v_kk2.F > aa*lambda_3) ~ 1,
        (u_kk2.F <= aa*lambda_2) & (cu*v_kk2.F > aa*lambda_3) ~ 2,
        (w_kk2.F**2+(cv*v_kk2.F)**2 > (aa*lambda_2)**2) &
          (v_kk2.F <= aa*lambda_3) ~ 3,
        TRUE ~ 4
      )
      # tracker
      case <- c(case, case_kk)
      cu_tracker <- c(cu_tracker, cu)
      cv_tracker <- c(cv_tracker, cv)
    
      
      if(case_kk == 1){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2
      }else if(case_kk == 2){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- cu*v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- cu*w_kk2
      }else if(case_kk == 3){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- cv*v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2
      }else{
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- v_kk2/
          (1+mcp_d(u_kk.F,aa,lambda_2,TRUE)/tau/(u_kk.F+eps) +
             mcp_d(v_kk.F,aa,lambda_3,TRUE)/tau/(v_kk.F+eps))
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2/
          (1+mcp_d(u_kk.F,aa,lambda_2,TRUE)/tau/(u_kk.F+eps))
        # 用 0 初始化时以下不合适，会总被压缩为 0
        # print(paste("case 4: ", sum(diff_v_est < 1e-9), sum(diff_w_est < 1e-9)))
        # diff_v_est[diff_v_est < 1e-9] <- 0
        # diff_w_est[diff_w_est < 1e-9] <- 0
      }
    }
  }
  diff_v_list[[iter]] <- diff_v_est
  diff_w_list[[iter]] <- diff_w_est
  
  # xi,zeta 的更新
  dual_xi_list[[iter]] <- dual_xi_list[[iter-1]] +
    (matrix(H_p%*%as.vector(coef_beta_est),ncol=1) - diff_v_list[[iter]])
  dual_zeta_list[[iter]] <- dual_zeta_list[[iter-1]] +
    (matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) - diff_w_list[[iter]])
  
  # diff_v_list[[iter]] <- matrix(H_p%*%as.vector(coef_beta_est),ncol=1) + dual_xi_est/tau
  # diff_w_list[[iter]] <- matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) + dual_zeta_est/tau
  # dual_xi_list[[iter]] <- dual_xi_list[[iter-1]] +
  #   tau*(matrix(H_p%*%as.vector(coef_beta_est),ncol=1) - diff_v_list[[iter]])
  # dual_zeta_list[[iter]] <- dual_zeta_list[[iter-1]] +
  #   tau*(matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) - diff_w_list[[iter]])
  
  pi_est <- apply(q_c_matrix, 2, sum)/n
  pi_list[[iter]] <- pi_est
  
  # update q_c matrix
  # 用没有重参数化的形式
  q_c_matrix_back <- q_c_matrix
  q_c_matrix <- dnorm(y,
                      mean = data%*%coef_full_ori_list[[iter]],
                      sd = 1/extend_x_to_row(rho_est, n)) *
    extend_x_to_row(pi_list[[iter-1]], n)
  nan_id <- which(apply(q_c_matrix, 1, sum) == 0)
  if(length(nan_id == 0) > 0){ print(paste(iter, nan_id)) }
  q_c_matrix[nan_id,] <- q_c_matrix_back[nan_id,]
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  
  # coef_diff_std <- (sum(coef_full_list[[iter]]-coef_full_list[[iter-1]])**2)/
  #    (sum(coef_full_list[[iter]])**2 + 1e-4)
  # if(coef_diff_std < 1e-6){
  #   return()
  # }
}
cdist <- coef_dist(coef_full_ori_list[[iter]], coef$coef_full)
# print(coef_full_list[[iter]])
print(coef_full_ori_list[[iter]])
print(table(case))
plot(unlist(lapply(coef_full_ori_list, coef_dist, coef$coef_full)), ylab = "",
     main = paste(q_c_seed, aa, lambda_1, lambda_2, lambda_3, tau))
cat("q_c_seed", q_c_seed, "a", aa, 
    "l1", lambda_1, "l2", lambda_2, "l3", lambda_3, "tau", tau)
ci_est <- apply(q_c_matrix, 1, which.max)
ci_prob <- apply(q_c_matrix, 1, max)
ci_matrix <- t(apply(q_c_matrix, 1, function(x){as.numeric(x == max(x))}))
y_hat <- rowSums(ci_matrix * data%*%coef_full_list[[iter]])
mse <- sum((y-y_hat)^2/n)
sc_score <- sc(ci_est, ci_sim)

print(cdist)
print(mse)
```






