---
title: "rho_k 更新式正确性验证"
author: "Yan Ren"
date: "2024-02-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

在计算中发现，当 $rho_k$ 更新时总是减小，相对的额 $\sigma_k$ 总是扩大趋势，这是不和常理的，这里研究在 $\epsilon$ 给定，参数都为真值的情况下，$\rho_k$ 用更新式计算出来是什么，是否符合常理

1. 若计算正确，真实情况考虑不再使用其进行更新
2. 若计算不正确，找到问题原因，再重复上面思路

# 准备工作

这部分完全与其他文档相同


```{r}
rm(list = ls(all = TRUE))
library(ggplot2)
library(dplyr)
library(Matrix)
library(flexmix)
library(readr)
source("sim.R")
source("tools.R")
source("func.R")
```

```{r}
n <- 500
p <- 8
q <- 4
epsilon_sd <- 0.5
epsilon_sd_init <- 0.5
sigma_est <- as.numeric(epsilon_sd_init)
signal_size <- 1
beta_vlen <- 3
alpha_vlen <- 2
save_path <- "temp.csv"
dt_seed <- 9
K_up <- 4  # 估计时的最大类别，应该不少于 group_num_sub

cotype_x <- "En"
cotype_z <- "En"
# epsilon_sd <- 0.5
beta_nonzero <- c(-2, -2, 2, 2)*signal_size # 长度应和真实 group_num_sub 保持一致
# beta_nonzero <- c(-3, -1, 1, 3) # 长度应和真实 group_num_sub 保持一致
alpha_nonzero <- c(-3, -1, 1, 3)*signal_size
# alpha_nonzero <- c(-2, -2, 2, 2) # 验证最简单情况不需要 alpha
# alpha_nonzero <- c(0, 0, 0, 0) # 验证最简单情况不需要 alpha
# beta_vlen <- 3
# alpha_vlen <- 2

q_c_seed_max <- 20
group_num_main <- 2                    
group_num_sub <- 4    
hier_struc <- list(c(1,2),c(3,4))
prob_sub <- rep(1/group_num_sub, group_num_sub)  
reverse <- FALSE
```

```{r}
whole.data <- generate_all_data(dt_seed, n, p, q, prob_sub, hier_struc, 
                                beta_nonzero, alpha_nonzero, beta_vlen, alpha_vlen, 
                                cotype_x, cotype_z, epsilon_sd, reverse)
X <- whole.data$data$X
Z <- whole.data$data$Z
data <- whole.data$data$data_full
coef <- whole.data$coef
# coefv <- lapply(coef, as.vector) # 按照类别拉长
ci_sim <- whole.data$ci_sim
y <- matrix(whole.data$y, ncol=1)

# =============================== prepare =================================
comb_pair <- combn(K_up, 2)
H_p <- kronecker(t(apply(comb_pair, 2, get_e_mat, K_up)),
                 diag(p)) %>% Matrix(sparse = TRUE)
H_q <- kronecker(t(apply(comb_pair, 2, get_e_mat, K_up)),
                 diag(q)) %>% Matrix(sparse = TRUE)


# =============================== result =================================
colnames_all <- c("dt_seed", "q_c_seed", "aa", "tau", "l1", "l2", "l3",
                  "cdist", "ci_prob_mean", "mse", "sc", "ari", "fit_sum", "fit_mean",
                  "penal", "bic_sum", "bic_mean", "main_grn", "sub_grn", 
                  "rho_init", "rho_est", "valid_hier", 
                  "group_detail", paste0("case_", 1:4), 
                  "iter_total", "iter_type", "tag")


result <- as.data.frame(matrix(NaN, nrow = 2, ncol = length(colnames_all)))
colnames(result) <- colnames_all
result$dt_seed <- dt_seed
```

# 开始验证

```{r}
q_c_seed <- 1
fix_para <- list(dt_seed = dt_seed, q_c_seed = q_c_seed, lambda_1 = 0.3,
                 aa = 1.2, tau = 1)
l2_seq <- c(0.5)
l3_seq <- c(2)
trail_set <- expand.grid(list(l3 = l3_seq, l2 = l2_seq))

aa = fix_para$aa
tau = fix_para$tau
lambda_1 = fix_para$lambda_1
lambda_2 = l2_seq[1]
lambda_3 = l3_seq[1]
q_c_seed = fix_para$q_c_seed
coef_full_init = whole.data$coef$coef_full*rho_init
iter_type= "stop"
iter_max = 200
rho_clip = 2
plot_performance = TRUE
eps = 1e-7
eps_abs = 1e-2
eps_rel = 1e-3
```

以下分析 ADMM 函数内部

```{r}
# cbind((X%*%coef_beta_est[,k] + Z%*%coef_alpha_est[,k]), y, ci_sim)
```


```{r}
tau <- ifelse(tau == 0, 1e-4, tau) # 防止 tau == 0 导致分母为0情况
sigma_est = ifelse(sigma_est == 0, 0.01, sigma_est)
rho_init <- rep(1, K_up)/sigma_est

kj <- function(dim) {return((k-1)*dim+j)}
ks <- function(dim) {return((k-1)*dim+s)}
rho_list <- list(rho_init)
pi_init <- rep(1/K_up, K_up)
pi_list <- list(pi_init)
set.seed(q_c_seed)
# q_c_matrix <- get_q_c_matrix(n, K_up, ci_sim)
# 真值附近
q_c_matrix <- abs(get_q_c_matrix(n, K_up, ci_sim) + rnorm(n*K_up, mean = 1, sd = .1))
# 全随机
# q_c_matrix <- abs(t(kronecker(pi_init, matrix(1, ncol = n))) + rnorm(n*K_up, mean = 0, sd = .1))
q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)

# coef full
# coef_full_init <- coef$coef_full - coef$coef_full

# coef_full_init[(p+1):(p+q),] <- coef$coef_alpha
# coef_full_init[1:p,] <- coef$coef_beta
# coef_full_init <- coef$coef_full * t(kronecker(rho_init, matrix(1, ncol = p+q)))
coef_full_list <- list(coef_full_init)
coef_full_ori_list <- list(coef_full_init/t(kronecker(rho_init, 
                                                      matrix(1, ncol = p+q))))

# coef diff (v,w):=u
diff_v_init <- matrix(H_p %*% as.vector(coef_full_init[1:p,]), ncol = 1)
# diff_v_init <- matrix(H_p %*% as.vector(coef$coef_beta), ncol = 1)
diff_v_list <- list(diff_v_init)
diff_w_init <- matrix(H_q %*% as.vector(coef_full_init[(p+1):(p+q),]), ncol = 1)
# diff_w_init <- matrix(H_q %*% as.vector(coef$coef_alpha), ncol = 1)
diff_w_list <- list(diff_w_init)

# dual variable (xi,zeta):=eta
dual_xi_init <- matrix(0, nrow = (p)*K_up*(K_up-1)/2, ncol = 1)
dual_xi_list <- list(dual_xi_init)
dual_zeta_init <- matrix(0, nrow = (q)*K_up*(K_up-1)/2, ncol = 1)
dual_zeta_list <- list(dual_zeta_init)

resi_dual_list <- list(NULL)
resi_prim_list <- list(NULL)
eps_dual_list <- list(NULL)
eps_prim_list <- list(NULL)

case <- NULL
cu_tracker <- NULL
cv_tracker <- NULL

iter <- 2
for(iter in 2:iter_max){
  rho_est <- rho_list[[iter-1]]
  coef_full_est <- coef_full_list[[iter-1]]
  coef_beta_est <- coef_full_est[1:p,]
  coef_alpha_est <- coef_full_est[(p+1):(p+q),]
  
  diff_v_est <- diff_v_list[[iter-1]]
  diff_w_est <- diff_w_list[[iter-1]]
  
  dual_xi_est <- dual_xi_list[[iter-1]]
  dual_zeta_est <- dual_zeta_list[[iter-1]]
  
  
  # rho_k 的更新
  # update_step = ifelse(iter > 10, 0.4, 0)
  update_step = 1
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    onen <- matrix(1, nrow = n, ncol = 1)
    AA <- as.numeric(t(y) %*% W_k %*% y)
    BB <- as.numeric(-t(y) %*% W_k %*% (X%*%coef_beta_est[,k] + Z%*%coef_alpha_est[,k]))
    CC <- as.numeric(-t(onen) %*% W_k %*% onen)
    rho_k_est <- (-BB+sqrt(BB**2-4*AA*CC))/(2*AA)
    rho_k_est <- ifelse(rho_k_est <= 0.5, 1, min(rho_clip, rho_k_est))
    rho_est[k] <- update_step*rho_k_est + (1-update_step)*rho_est[k]
  }
  
  # =========================== beta, alpha update =========================
  # beta,alpha （相比矩阵形式，只修改 beta,alpha 更新）
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    for(j in 1:p){
      lower_1 <- t(X[,j]) %*% W_k %*% X[,j]
      lower_2 <- (t(H_p)%*%H_p)[kj(p), kj(p)]
      # lower_2 <- 0
      Lower <- lower_1/n + tau*lower_2
      upper_1 <- t(X[,j]) %*% W_k %*% (rho_est[k]*y - X[,-j]%*%(coef_beta_est[-j,k]) - Z%*%coef_alpha_est[,k])
      upper_2 <- (t(H_p)%*%(diff_v_est-dual_xi_est))[kj(p)] - 
        as.vector(coef_beta_est)[-kj(p)]%*%((t(H_p)%*%H_p)[kj(p),-kj(p)])
      # upper_2 <- 0
      Upper <- upper_1/n + tau*upper_2
      # coef_beta_kj <- Upper/Lower
      coef_beta_kj <- mcp_solution(Lower, Upper/Lower, aa, lambda_1)
      coef_beta_est[j,k] <- coef_beta_kj
    }
    for(s in 1:q){
      lower_1 <- t(Z[,s]) %*% W_k %*% Z[,s]
      lower_2 <- (t(H_q)%*%H_q)[ks(q), ks(q)]
      # lower_2 <- 0
      Lower <- lower_1/n + tau*lower_2
      upper_1 <- t(rho_est[k]*y - Z[,-s]%*%(coef_alpha_est[-s,k]) - X%*%coef_beta_est[,k]) %*% W_k %*% Z[,s]
      upper_2 <- (t(H_q)%*%(diff_w_est-dual_zeta_est))[ks(q)] - 
        as.vector(coef_alpha_est)[-ks(q)]%*%((t(H_q)%*%H_q)[ks(q),-ks(q)])
      # upper_2 <- 0
      Upper <- upper_1/n + tau*upper_2
      # coef_alpha_ks <- Upper/Lower
      coef_alpha_ks <- mcp_solution(Lower, Upper/Lower, aa, lambda_1)
      coef_alpha_est[s,k] <- coef_alpha_ks
    }
  }
  coef_full_est <- rbind(coef_beta_est, coef_alpha_est)
  
  # =====================================================================
  # 类别内，总体类别的
  y_hat_matrix <- matrix(0, nrow = n, ncol = K_up)
  y_hat <- matrix(0, nrow = n, ncol = 1)
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    y_hat_matrix[,k] <- W_k %*% (X%*%coef_beta_est[,k] + Z%*%coef_alpha_est[,k])
    y_hat <- y_hat + y_hat_matrix[,k]
  }
  
  resi_df <- data.frame()
  for(k in 1:K_up){
    W_k <- diag(q_c_matrix[,k])
    resi_matrix <- matrix(rep(y,4), ncol = 4) - y_hat_matrix
    y_hat_k <- (W_k %*% resi_matrix)[,k]
    print(sd(y_hat_k[y_hat_k!=0]))
    resi_df <- rbind(resi_df, cbind(y_hat_k[y_hat_k!=0],k))
  }
  # [1] 0.6170719
  # [1] 0.6263322
  # [1] 0.5574525
  # [1] 0.5119769
  colnames(resi_df) <- c("resi", "k")
  resi_df$k <- as.factor(resi_df$k)
  ggplot(resi_df, aes(x = resi, fill = k)) +
    geom_histogram(position = 'dodge')
  # =====================================================================
      
  rho_list[[iter]] <- rho_est
  coef_full_list[[iter]] <- coef_full_est
  coef_full_ori_list[[iter]] <- coef_full_est/extend_x_to_row(rho_est,p+q)
  
  diff_v_est <- matrix(H_p %*% as.vector(coef_beta_est), ncol = 1)
  diff_w_est <- matrix(H_q %*% as.vector(coef_alpha_est), ncol = 1)
  diff_v_last <- diff_v_list[[iter-1]]
  diff_w_last <- diff_w_list[[iter-1]]
  
  # v,w 的更新 2 means prime
  diff_v2_est <- H_p%*%as.vector(coef_beta_est) + dual_xi_est
  diff_w2_est <- H_q%*%as.vector(coef_alpha_est) + dual_zeta_est
  
  for(k1 in 1:(K_up-1)){
    for(k2 in (k1+1):K_up){
      ikk <- which(apply(comb_pair, 2, function(x){all(x==c(k1,k2))}))
      
      v_kk <- diff_v_est[((ikk-1)*p+1):(ikk*p)]
      w_kk <- diff_w_est[((ikk-1)*q+1):(ikk*q)]
      u_kk <- c(v_kk, w_kk)
      
      v_kk_last <- diff_v_last[((ikk-1)*p+1):(ikk*p)]
      w_kk_last <- diff_w_last[((ikk-1)*q+1):(ikk*q)]
      u_kk_last <- c(v_kk_last, w_kk_last)
      
      v_kk.F <- norm(matrix(v_kk_last), type = "2")
      w_kk.F <- norm(matrix(w_kk_last), type = "2")
      u_kk.F <- sqrt(v_kk.F**2 + w_kk.F**2)
      
      v_kk2 <- diff_v2_est[((ikk-1)*p+1):(ikk*p)]
      w_kk2 <- diff_w2_est[((ikk-1)*q+1):(ikk*q)]
      
      v_kk2.F <- norm(matrix(v_kk2), type = "2")
      w_kk2.F <- norm(matrix(w_kk2), type = "2")
      u_kk2.F <- sqrt(v_kk2.F**2 + w_kk2.F**2)
      
      cu <- positive_part(1-lambda_2/tau/u_kk2.F)/(1-1/aa/tau)
      cv <- positive_part(1-lambda_3/tau/v_kk2.F)/(1-1/aa/tau)
      if(is.na(cu)){ print(paste(iter, "cu na of k1 k2", k1, k2)); cu <- 0 }
      if(is.na(cv)){ print(paste(iter, "cv na of k1 k2", k1, k2)); cv <- 0 }
      # 判断压缩类别
      case_kk <- case_when(
        (u_kk2.F > aa*lambda_2) & (v_kk2.F > aa*lambda_3) ~ 1,
        (u_kk2.F <= aa*lambda_2) & (cu*v_kk2.F > aa*lambda_3) ~ 2,
        (w_kk2.F**2+(cv*v_kk2.F)**2 > (aa*lambda_2)**2) &
          (v_kk2.F <= aa*lambda_3) ~ 3,
        TRUE ~ 4
      )
      # tracker
      case <- c(case, case_kk)
      cu_tracker <- c(cu_tracker, cu)
      cv_tracker <- c(cv_tracker, cv)
      
      if(case_kk == 1){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2
      }else if(case_kk == 2){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- cu*v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- cu*w_kk2
      }else if(case_kk == 3){
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- cv*v_kk2
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2
      }else{
        diff_v_est[((ikk-1)*p+1):(ikk*p)] <- v_kk2/
          (1+mcp_d(u_kk.F,aa,lambda_2,TRUE)/tau/(u_kk.F+eps) +
             mcp_d(v_kk.F,aa,lambda_3,TRUE)/tau/(v_kk.F+eps))
        diff_w_est[((ikk-1)*q+1):(ikk*q)] <- w_kk2/
          (1+mcp_d(u_kk.F,aa,lambda_2,TRUE)/tau/(u_kk.F+eps))
        # 用 0 初始化时以下不合适，会总被压缩为 0
        # print(paste("case 4: ", sum(diff_v_est < 1e-9), sum(diff_w_est < 1e-9)))
        # diff_v_est[diff_v_est < 1e-9] <- 0
        # diff_w_est[diff_w_est < 1e-9] <- 0
      }
    }
  }
  diff_v_list[[iter]] <- diff_v_est
  diff_w_list[[iter]] <- diff_w_est
  
  # xi,zeta 的更新
  dual_xi_list[[iter]] <- dual_xi_list[[iter-1]] +
    (matrix(H_p%*%as.vector(coef_beta_est),ncol=1) - diff_v_list[[iter]])
  dual_zeta_list[[iter]] <- dual_zeta_list[[iter-1]] +
    (matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) - diff_w_list[[iter]])
  
  # diff_v_list[[iter]] <- matrix(H_p%*%as.vector(coef_beta_est),ncol=1) + dual_xi_est/tau
  # diff_w_list[[iter]] <- matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) + dual_zeta_est/tau
  # dual_xi_list[[iter]] <- dual_xi_list[[iter-1]] +
  #   tau*(matrix(H_p%*%as.vector(coef_beta_est),ncol=1) - diff_v_list[[iter]])
  # dual_zeta_list[[iter]] <- dual_zeta_list[[iter-1]] +
  #   tau*(matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) - diff_w_list[[iter]])
  
  # stopping criteria
  if(iter_type == "stop"){
    resi_prim <- rbind(matrix(H_p%*%as.vector(coef_beta_est),ncol=1) - diff_v_list[[iter]],
                       matrix(H_q%*%as.vector(coef_alpha_est),ncol=1) - diff_w_list[[iter]]) %>%
      norm(type = '2')
    resi_dual <- rbind(-tau * t(H_p) %*% (diff_v_list[[iter]] - diff_v_list[[iter-1]]),
                       -tau * t(H_q) %*% (diff_w_list[[iter]] - diff_w_list[[iter-1]])) %>%
      norm(type = '2')
    resi_prim_list[[iter]] <- resi_prim
    resi_dual_list[[iter]] <- resi_dual
    
    eps_prim <- sqrt(K_up*(K_up-1)/2*(p+q))*eps_abs + 
      eps_rel*max(norm(rbind(H_p%*%as.numeric(coef_beta_est), H_q%*%as.numeric(coef_alpha_est)), type = '2'), 
                  norm(rbind(diff_v_est, diff_w_est), type = '2'))
    eps_dual <- sqrt(K_up*(p+q))*eps_abs +
      eps_rel*norm(rbind(t(H_p)%*%dual_xi_list[[iter]], t(H_q)%*%dual_zeta_list[[iter]]), type = '2')
    eps_prim_list[[iter]] <- eps_prim
    eps_dual_list[[iter]] <- eps_dual
    
    if((resi_prim < eps_prim) & (resi_dual < eps_dual)){
      break
    }
  }

  pi_est <- apply(q_c_matrix, 2, sum)/n
  pi_list[[iter]] <- pi_est
  
  # update q_c matrix
  # 用没有重参数化的形式
  q_c_matrix_back <- q_c_matrix
  q_c_matrix <- dnorm(y,
                      mean = data%*%coef_full_ori_list[[iter]],
                      sd = 1/extend_x_to_row(rho_est, n)) *
    extend_x_to_row(pi_list[[iter-1]], n)
  nan_id <- which(apply(q_c_matrix, 1, sum) == 0)
  if(length(nan_id == 0) > 0){ print(paste("[nan]", iter, nan_id)) }
  q_c_matrix[nan_id,] <- q_c_matrix_back[nan_id,]
  q_c_matrix <- q_c_matrix / apply(q_c_matrix, 1, sum)
  
  
  # coef_diff_std <- (sum(coef_full_list[[iter]]-coef_full_list[[iter-1]])**2)/
  #    (sum(coef_full_list[[iter]])**2 + 1e-4)
  # if(coef_diff_std < 1e-6){
  #   return()
  # }
}
# 距离真实参数距离，只有类别数相同才能计算该指标
# cdist <- ifelse(ncol(coef$coef_full) == ncol(coef_full_ori_list[[iter]]), 
#                 coef_dist(coef_full_ori_list[[iter]], coef$coef_full),
#                 NaN)

cdist <- tryCatch({
  coef_dist(coef_full_ori_list[[iter]], coef$coef_full)
}, error = function(err) {NaN})
# 参数结果（未压缩）
cat(paste0("****[unsqueezed coef]****:\n"))
print(coef_full_ori_list[[iter]])
# case 情况（检查是否落入组别压缩的情况
case_table_full <- rep(0, 4) # v,w 更新四种情况落入次数记录
case_table <- table(case)
for(t in 1:dim(case_table)){
  case_table_full[as.integer(names(case_table)[t])] <- case_table[names(case_table)[t]]
}

if(plot_performance){
  plot(1:iter, c(resi_prim_list[[2]], unlist(resi_prim_list)), col = "Black", main = "primary")
  points(c(eps_prim_list[[2]], unlist(eps_prim_list)), col = "DeepPink")
  lines(c(resi_prim_list[[2]], unlist(resi_prim_list)), col = "Black")
  lines(c(eps_prim_list[[2]], unlist(eps_prim_list)), col = "DeepPink")
  
  plot(1:iter, c(resi_dual_list[[2]], unlist(resi_dual_list)), col = "Black", main = "dual")
  points(c(eps_dual_list[[2]], unlist(eps_dual_list)), col = "DeepPink")
  lines(c(resi_dual_list[[2]], unlist(resi_dual_list)), col = "Black")
  lines(c(eps_dual_list[[2]], unlist(eps_dual_list)), col = "DeepPink")
  # 估计参数距离真实参数距离的可视化展示
  plot(unlist(lapply(coef_full_ori_list, coef_dist, coef$coef_full)), ylab = "",
       main = paste(q_c_seed, aa, lambda_1, lambda_2, lambda_3, tau))
}

ci_est <- apply(q_c_matrix, 1, which.max)
sc_score <- tryCatch({
  sc(ci_est, ci_sim)
}, error = function(err) {NaN})
ari_score <- tryCatch({
  ari(ci_est, ci_sim)
}, error = function(err) {NaN})

ci_prob <- apply(q_c_matrix, 1, max)
ci_matrix <- t(apply(q_c_matrix, 1, function(x){as.numeric(x == max(x))}))
y_hat <- rowSums(ci_matrix * data%*%coef_full_list[[iter]])
mse <- sum((y-y_hat)^2/n)

# group result
main_group_info <- get_group_num(K_up, 
                                coef_full_ori_list[[iter]][(1:p),], 
                                diff_v_list[[iter]], p)
sub_group_info <- get_group_num(K_up, 
                                coef_full_ori_list[[iter]][(1+p):(p+q),], 
                                diff_w_list[[iter]], q)
# print(main_group_info$capgfl.matrix2)
# print(sub_group_info$capgfl.matrix2)
est_main_grn <- main_group_info$gr.num
est_sub_grn <- sub_group_info$gr.num

cappfl.diff <- main_group_info$capgfl.matrix2 - sub_group_info$capgfl.matrix2
valid_hier <- ifelse(min(cappfl.diff) >= 0, TRUE, FALSE)
diag(cappfl.diff) <- 1
group_detail <- apply(which((cappfl.diff) > 0, arr.ind = TRUE), 1, function(x){paste0("(",x[1],",",x[2],")")})
group_detail <- paste0(group_detail, collapse = "")
# BIC.var <- log(mse) + log(n*(p+q))*log(n)*(est_main_grn*(p)+est_sub_grn*(q))/n
# BIC.o <- log(mse) + log(n)*(est_main_grn*p+est_sub_grn*q)/n

bic_info <- bic_score(q_c_matrix, coef_full_ori_list[[iter]], 
                      est_main_grn, est_sub_grn, rho_est)

cat(paste("**** hypter parameter:", "dt_seed", dt_seed, "q_c_seed", q_c_seed, 
          "l1", lambda_1, "l2", lambda_2, "l3", lambda_3, "tau", tau, "a", aa, "\n"))
cat(paste("**** result:", "est_main_grn", est_main_grn, "est_sub_grn", est_sub_grn,
          "mse", mse, "sc", sc_score, "bic_sum", bic_info$bic_sum, "bic_mean", bic_info$bic_mean, 
          "valid_hier", valid_hier, "group_detail", group_detail, "\n"))
print(case_table_full)
print(coef_full_ori_list[[iter]])

return(list(cdist = cdist, 
            ci_prob_mean = mean(ci_prob),
            q_c_matrix = q_c_matrix,
            coef_full_ori = coef_full_ori_list[[iter]],
            # coef_full = coef_full_list[[iter]],
            mse = mse,
            # BIC.var = BIC.var,
            # BIC.o = BIC.o,
            fit_sum = bic_info$fit_sum,
            fit_mean = bic_info$fit_mean,
            penal = bic_info$penal,
            bic_sum = bic_info$bic_sum,
            bic_mean = bic_info$bic_mean,
            sc_score = sc_score,
            ari_score = ari_score,
            case_table_full = case_table_full,
            est_main_grn = main_group_info$gr.num,
            est_sub_grn = sub_group_info$gr.num,
            rho_init = rho_init[1],
            rho_est = paste0("(", paste(as.character(round(rho_list[[iter]],3)), collapse = ","), ")"),
            case_table_full = case_table_full,
            valid_hier = valid_hier,
            group_detail = group_detail,
            iter_total = iter,
            iter_type = iter_type))
```











